### PR TITLE
hiops moduls refer to (#1856)

### PR DESCRIPTION
**Pull request by mojtabaesfandiari**
#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by mojtabaesfandiari** [comment]
This module is refer to hiops module #1856

**Comment by miconda** [comment]
Thanks for the contribution. The patch is quite large and given the scope of the module, probably not many can spend time to do a deep review of the code. If nobody adds more, it can be merged, but first it needs the documentation of the module (the docbook xml files in doc/ subfolder and the generated README). Can you push them soon to have the module ready for a potential merge?

**Comment by henningw** [comment]
A few things to add from my side:
- many files are generated from an ASN.1 definition file (e.g. from HI1NotificationOperations.asn), but the asn1 files are missing. It would be great if they could be added, otherwise future extensions are difficult. 
- there is a CMake file included (CMakeLists.txt), is is still used? We use make as our build system in Kamailio. Otherwise it should be removed.
- there are a lot of include files from the asnc1 added (like OBJECT_IDENTIFIER.c/h, BIT_STRING.c/h etc..). These files are all provides as part of the asnc1 package and should not be included as part of the module.
- the module also introduce a new function in the core "int received_in_via( struct sip_msg *msg )" @miconda maybe you can have a look to this

I just did a quick test to use the asn1c system files - the module still compiles with them (after fixing one bug related to a crypto refactoring). So it looks quite good and the module size was reduced from ~19.000 lines to 5600 lines. :-) The only change necessary in the Makefile was to add one include:
```
DEFS+=-DKAMAILIO_MOD_INTERFACE \
        -I/usr/share/asn1c/
```

There are a couple of warnings related to the use of BSD_SOURCE, but they could be fixed also later.

After you added the documentation it can be merged, with the asn1c files removed of course. It probably makes sense to merge it manually, to prevent the whole files to be introduced into the repository and then deleted again. I can do it, no problem.

**Comment by mojtabaesfandiari** [comment]
As @henningw mentioned, I should remove  asn1c system files from the main module source. Another way that i am thinking about it is using asn1c system file just during compiling the module and remove all them after that.
It's documents is ready now, So i should get time to publish it. I'll get do that. Also some function was completely changed, for getting more compatibility with other codes, They should be published, too.
I had the same thought about this function "received_in_via" , It could be a new function in core source files.

**Comment by henningw** [comment]
As mentioned, you can finish the module docs and I can merge it manually, also removing the discussed files and adapting the Makefile.
Any comment about the question related to the asn definition files?

**Comment by mojtabaesfandiari** [comment]
The basic asn definition file erlated to Lawful Interception is available in below link:
 https://www.etsi.org/deliver/etsi_ts/101600_101699/101671/03.15.01_60/
But based on Table 7.1 and 7.3 in TS.133.108 for IMS networks, Just some of hiX-parameters (The X parameter is refered to 1,2,3 interfaces)would be used. So we might have to change some of asn file before compiling or we could use them with no changing and just focused on mandatory parameters.

**Comment by henningw** [comment]
@mojtabaesfandiari - any update on this pull request? I think the still open topics are related to docs and the asn1 definitions. If you can't provie the asn1 definitions for some reasons, let us know.

**Comment by mojtabaesfandiari** [comment]
@henningw - because of developing lreproxy engine, i had not more time.  Now, i could come back to hiops module developing and completing it.
I will update it next days.

**Comment by miconda** [comment]
Short note to say that probably branching of 5.4 will happen soon, if you want this merged for 5.4.x release series, then it has to be made ready during the next days.

**Comment by henningw** [comment]
@miconda I had a conversation with the author of the pull request, he wants to rework the code substancially. I don't think this should be merged in this form.

**Comment by mojtabaesfandiari** [comment]
Yes, As @henningw is mentioned, some rework substancially is doing right now, I don't think it's over for this branching.

**Comment by mojtabaesfandiari** [comment]
Because of there are a lot of changes in source code, i have to close this PR and create new one later.

**Comment by soroshsabz** [comment]
@mojtabaesfandiari Where is the new branch? please link them to this

**Comment by mojtabaesfandiari** [comment]
Unfortunatly the latest development of hiops module dose not published
Becuase of some issue

**Pull request closed without merging**
