### PR TITLE
Implement load and restore of contact attributes

### PR DESCRIPTION
**Pull request by que273**
Implement load and restore of usrloc contact attributes in the t_load_contacts, t_next_contacts and t_next_contact_flows functions in tm module.

Includes documentation of the new tm parameter 'xavp_contact'

### CODE REVIEW

**Comment by que273** [comment]
Does anyone have any comments on my fix?
Can I merge and backport?

**Comment by kamailio-sync** [comment]
Hugh Waite writes:

> Does anyone have any comments on my fix?
> Can I merge and backport?

I think I implemented those tm functions.  Does your fix require any
config file changes to the present use of those functions?  If not, I
have nothing against them.

-- Juha

**Comment by que273** [comment]
The tm module needs to know the name of the attributes AVP, which is currently passed as a modparam to the usrloc module. Therefore to 'activate' this bugfix, you need to pass the same modparam to the tm module.E.g.
`modparam("usrloc|tm", "xavp_contact", "ulattrs")`
If the modparam is not given to tm, the system will behave as before.
There are no changes to the way the functions are called.

**Comment by juha-h** [comment]
Hugh Waite writes:

> The tm module needs to know the name of the attributes AVP, which is
> currently passed as a modparam to the usrloc module. Therefore to
> 'activate' this bugfix, you need to pass the same modparam to the tm
> module.E.g. 
> `modparam("usrloc|tm", "xavp_contact", "ulattrs")`
> If the modparam is not given to tm, the system will behave as before.
> There are no changes to the way the functions are called.

What happened to the fix?  Did it go to 4.3?

-- Juha

**Comment by miconda** [comment]
No, is not in 4.3 --- actually, this pull request is not even merged in master.

As I see the comments above, the discussion was still open. From my point of view, it can be merged and backported if it is a fix.

**Comment by juha-h** [comment]
Hugh Waite writes:

> The tm module needs to know the name of the attributes AVP, which is
> currently passed as a modparam to the usrloc module. Therefore to
> 'activate' this bugfix, you need to pass the same modparam to the tm
> module.E.g. `modparam("usrloc|tm", "xavp_contact", "ulattrs")`
> If the modparam is not given to tm, the system will behave as before.
> There are no changes to the way the functions are called.

i'm still confused about xavp_contact tm module parameter.  when i
implemented t_load_contacts(), t_next_contacts() and
t_next_contact_flows() functions, contacts_avp and contact_flows_avp
defined the xavps that those functions used as described in tm README on
those functions.

now there is another variable xavp_contact.  tm README tells about it
that it is used for storing attributes per contact, but does tell how
the xavp gets set.  usrloc README tells that xavp gets set at lookup (if
i got it right), but is also tells "The tm module parameter xavp_contact
must also be set to the same value to use the t_load_contacts and
t_next_contacts functions".

does that mean that t_load_contacts()/t_next_contacts() does not anymore
work if xavp_contact parameter is not defined for tm and usrloc modules?

-- juha

**Comment by que273** [comment]
If the usrloc parameter "xavp_contact" is set, the given XAVP is populated with the contact attributes when the "lookup" function is called. The usrloc README example uses the name 'ulattrs'.

The tm module parameters 'contacts_avp' and 'contact_flows_avp' are populated when the t_load_contacts() function is called. These store the data from the branch structures but, before my changes, did not know anything about the attributes loaded by usrloc. 

My changes mean that the usrloc attributes are now loaded into the 'contacts_avp' data when t_load_contacts() is called. However, the tm module needs to know the name of the XAVP that usrloc stored these attributes in, hence the new parameter and why they must have the same value.

If you do not set the 'xavp_contact' parameter in usrloc, then attributes are not stored / loaded when you call 'register' / 'lookup'. It is therefore not needed in tm module either.
If you supply the parameter to usrloc, but NOT tm, then the attributes are ignored by the load/next_contacts functions and the bug will still be present.

**Comment by kamailio-sync** [comment]
Hugh Waite writes:

> The tm module parameters 'contacts_avp' and 'contact_flows_avp' are
> populated when the t_load_contacts() function is called. These store
> the data from the branch structures but, before my changes, did not
> know anything about the attributes loaded by usrloc.

thanks for your explanation.  by usrloc attributes you mean all the
fields of location table?

-- juha

**Comment by kamailio-sync** [comment]
This fix regards the tag-value pairs that are stored in the 'location-attrs' table.

I am adding custom values to the REGISTER transaction just before calling save() and need them to be restored per branch when calling lookup().

Hugh


-----Original Message-----

**Pull request merged**
