### PR TITLE
core: Explicitly cast void* to char*

### PR DESCRIPTION
**Pull request by jamesaimonetti**
When compiling a custom module, including `shm_mem.h` caused the
following compilation error:

In file included from ../../core/mem/shm_mem.h:32,
                 from custom_code.cpp:40:
../../core/parser/../ut.h: In function ‘char* shm_char_dup(const char*)’:
../../core/mem/shm.h:67:49: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
   67 | # define shm_malloc(s)         _shm_root.xmalloc(_shm_root.mem_block, (s))
      |                                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 void*
../../core/parser/../ut.h:811:9: note: in expansion of macro ‘shm_malloc’
  811 |  rval = shm_malloc(len);
      |         ^~~~~~~~~~

gcc version: `gcc (Debian 9.2.1-22) 9.2.1 20200104`

#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
Thanks! I pushed the patch manually, because the commit message was not formatted properly (the subject of PR has the format for the commit message):

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-rules

**Comment by jamesaimonetti** [comment]
@miconda thanks! Noted on the commit message. To clarify for me, what I put should have been a comment here on the PR and not in the commit message itself, yes?

**Comment by miconda** [comment]
It is about the first line of the commit messages which should be prefixed with the component name. The title of PR is:

```
core: Explicitly cast void* to char*
```

which is fine for first line of commit message.

But your commit message had the first line:

```
Explicitly cast void* to char*
```

not indicating the component (core in this case).

**Comment by jamesaimonetti** [comment]
Ah right, I submitted the PR before reviewing the commit requirements, then editing the PR itself not the commit message. Thanks again for the feedback.

**Pull request closed without merging**
