### PR TITLE
topos: disable multiple comma separated values in One Single Via, Record-Route or Route header if needed

### PR DESCRIPTION
**Pull request by emvondo**
Topos module always put a single Via header with multiple comma separated values.
Even if this behaviour is RFC compliant there should a possibilty to disable that behaviour four uas that dont support/handle that.

this pull request adds a new parameter topos module to disable that behaviour if needed otherwise the default topos compact form is used.

```
modparam("topos", "separate_header_values", 1) # for Via only 
modparam("topos", "separate_header_values", 2) # for Record-Route only 
modparam("topos", "separate_header_values", 4) # for Route only 

modparam("topos", "separate_header_values", 7) # for Via, Record-Route  and Route 


The following options are available:

 (1) - disable multiple comma separated values for Via  header
 (2) - disable multiple comma separated values for Record-Route header
 (4) - disable multiple comma separated values for Route header
```

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #3216

### CODE REVIEW

**Comment by patrickarton** [comment]
Hello can you please remove the uncessary condition if (c==0 || c== 1) {}  and leave only the body of that condition please and remove also the unused c variable. we dont need it.

Thanks.

**Comment by emvondo** [comment]
Hello can you please remove the uncessary condition if (c==0 || c== 1) {}  and leave only the body of that condition please and remove also the unused c variable. we dont need it.

should be like this 

```
int tps_reappend_via_separate_header(sip_msg_t *msg, tps_data_t *ptsd, str *hbody)
{
        str hname = str_init("Via");
        int i;
        str sb;
        char *p = NULL;

        if(hbody==NULL || hbody->s==NULL || hbody->len<=0 || hbody->s[0]=='\0')
            return 0;

        sb.len = 1;
        p = hbody->s;
        for(i=0; i<hbody->len-1; i++) {
            if(hbody->s[i]==',') {
                if(sb.len>0) {
                    sb.s = p;
                    if(sb.s[sb.len-1]==',') sb.len--;
                    if(tps_add_headers(msg, &hname, &sb, 0)<0) {
                        return -1;
                    }
                }
                sb.len = 0;
                p = hbody->s + i + 1;
            }
            sb.len++;
        }


        if(sb.len>0) {
                sb.s = p;
                if(sb.s[sb.len-1]==',') sb.len--;
                if(tps_add_headers(msg, &hname, &sb, 0)<0) {
                    return -1;
                }
        }


        return 0;
}

```

Thanks.

**Comment by miconda** [comment]
@emvondo: if you want to change the commit of the PR, you can update on your local copy and force push to the same git branch.

**Comment by emvondo** [comment]
> @emvondo: if you want to change the commit of the PR, you can update on your local copy and force push to the same git branch.

Thanks Daniel.

its done.

**Comment by henningw** [comment]
Ok, sounds good. As you probably know, the documentation (XML docbook) needs to be extended as well, to be ready for the merge. But its usually a good idea to do that at the end after all code changes were done.

**Comment by emvondo** [comment]
> Ok, sounds good. As you probably know, the documentation (XML docbook) needs to be extended as well, to be ready for the merge. But its usually a good idea to do that at the end after all code changes were done.

Thanks for feedback.

i pushed updates for Via , Record-Route and Route header.

**Comment by henningw** [comment]
Thank you, lgtm. @miconda any comments from your side? Otherwise I think it could be merged, preferable squashed to one commit.

**Comment by miconda** [comment]
The name of the parameter `separate_header_values` should be changed to `header_mode` to be even more generic and reused if anything else related to header management needs to be added in the future (e.g., add Via before or after Route).

From implementation point of view, the current solution is "good enough" because it is doing a basic split on comma, working with the common format seen for these headers. Otherwise, at least the `Record/-Route` can have comma in its value, being defined as `name-addr` by grammar and in the eventuality of a display name, comma is allowed inside. Not sure if Via is allowed to have quoted value parameter, because I think inside it is also allowed to have comma.

Anyhow, given that this commit adds this behaviour for particular deployments when some UA doesn't support headers with multiple comma separated values, I am fine to merge the implementation as it is, after renaming the parameter.

**Comment by emvondo** [comment]
> The name of the parameter `separate_header_values` should be changed to `header_mode` to be even more generic and reused if anything else related to header management needs to be added in the future (e.g., add Via before or after Route).
> 
> From implementation point of view, the current solution is "good enough" because it is doing a basic split on comma, working with the common format seen for these headers. Otherwise, at least the `Record/-Route` can have comma in its value, being defined as `name-addr` by grammar and in the eventuality of a display name, comma is allowed inside. Not sure if Via is allowed to have quoted value parameter, because I think inside it is also allowed to have comma.
> 
> Anyhow, given that this commit adds this behaviour for particular deployments when some UA doesn't support headers with multiple comma separated values, I am fine to merge the implementation as it is, after renaming the parameter.

Thanks for feedback @miconda  changes done.

**Comment by henningw** [comment]
Thank you all, merged.

**Pull request merged**
