### PR TITLE
htable: fix crash if deleted entry is reused

### PR DESCRIPTION
**Pull request by lazedo**
resets 'first' when esize == 0

### CODE REVIEW

**Comment by lazedo** [comment]
these crashes were caught by running with `-x tlsf`

**Comment by miconda** [comment]
@lazedo - I am not sure be46742 is actually effective and fixes anything -- `first` should become NULL if the last item in the slot (entry) is removed, because it->next should be NULL at that moment.

Can you describe what was the issue you faced? Maybe the problem is in another part and it->next is wrong, but that will have bad effects in other cases.

The commit 18ba95a seems ok.

**Comment by lazedo** [comment]
@miconda thanks for the comment. i  think you're right. i re-tested with only the second commit and it seems to be working.

**Comment by miconda** [comment]
@lazedo - ok, thanks for the feedback and fix! You can merge that commit and backport as needed to stable branches.

**Comment by lazedo** [comment]
@miconda backported to 4.4 and 5.0

**Pull request merged**
