### PR TITLE
p_usrloc: use a global p_usrloc_columns variable in db_load* functions

### PR DESCRIPTION
**Pull request by lbalaceanu**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Proposing a small refactoring around code that creates columns parameter for queries in the database when all/most columns are used. If considered useful, this can be adapted for udomain.c file in usrloc module.

### CODE REVIEW

**Comment by henningw** [comment]
Looks good to me. It similar code is used in usrloc udomain.c, the same refactoring could be of course also done there.

**Comment by lbalaceanu** [comment]
Thank you Henning, let's see if there are other comments.

**Comment by miconda** [comment]
If the array is used only in that file, I would suggest to make it static and maybe it would be also good rename it to p_usrloc_columns (or similar) to have the module prefix in the name, being a global variable.

**Comment by lbalaceanu** [comment]
Hi @miconda,

Do I "Squash and merge" or "Rebase and merge" this PR? Do you consider worthwhile to do a similar PR for usrloc?

Thank you

**Comment by miconda** [comment]
Hello, squashing is for combining moro commits of the same PR in a single one (if I haven't gotten it wrong), but here is only one, so rebase and merge should do it.

Even with more commits in same PR, rebasing and merge should be done when the commits are sort of independent. Squashing would be suitable when a commit amends another one (e.g., fixing fomratting of a previous commit).

**Comment by henningw** [comment]
I think it would be also a good addition for the usrloc module. It certainly makes the code better understandable (some integer IDs vs. easy names).

**Comment by lbalaceanu** [comment]
Hi @henningw, 

Will make a similar PR for usrloc.

Thank you

**Pull request merged**
