### PR TITLE
core: removing the condition for second record_route ipv6 header

### PR DESCRIPTION
**Pull request by surendratiwari3**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
when we are sending the call from ipv6 tls registered endpoint to kamailio and kamailio use the dispatcher module to forward that call to tcp sip server then second record route header have ipv6 address without [].so another sip server is saying 400 bad record route header.
before (with error):
Record-Route: <sip:2600:1F1C:74E:E100:E89F:BEB1:10AF:1CB1:5060;transport=tcp;r2=on;lr=on;ftag=msDr8yzIe5obR7fSfD-jPiJPFcJoVwwr;did=ae1.8861>

after (correct):
Record-Route: <sip:[2600:1F1C:74E:E100:E89F:BEB1:10AF:1CB1]:5060;transport=tcp;r2=on;lr=on;ftag=msDr8yzIe5obR7fSfD-jPiJPFcJoVwwr;did=ae1.8861>

### CODE REVIEW

**Comment by surendratiwari3** [comment]
@miconda please review this also for record_route header

**Comment by miconda** [comment]
Do you have advertise address to the listen socket?

**Comment by miconda** [comment]
I just pushed another patch (referenced above), because there were other cases when the same condition was used. The new patch is taking a safer path by checking if the ipv6 address starts with `[`.

Can you test and report if ok?

**Comment by surendratiwari3** [comment]
@miconda yes ,i have advertise address to the listen socket.

**Comment by surendratiwari3** [comment]
@miconda i will test the same.we are expecting all ipv6 patch to be merged with stable branch so we can start using those only.

**Comment by miconda** [comment]
If testing with master is ok, then I will backport. Just report if it works fine or not.

**Comment by surendratiwari3** [comment]
@miconda i tested with master branch.its working fine.it will be good if you can commit all changes related to ipv6 to all stable releases specially to 5.x.x branches.reference to following pull request:
https://github.com/kamailio/kamailio/pull/1319
https://github.com/kamailio/kamailio/pull/1315
https://github.com/kamailio/kamailio/pull/1291

**Comment by miconda** [comment]
Patches should be backported by now in the 5.x.x branches, if you still find an issue, open another item on the tracker.

**Comment by SurendraPlivo** [comment]
@miconda thanks.

**Pull request closed without merging**
