### PR TITLE
uri_db: rework the possibiltiy to use any sip uri

### PR DESCRIPTION
**Pull request by dunst0**
Adding the possibility to check any sip uri against the uri_db table and updates the log macros from LM_ to the new ones.

### CODE REVIEW

**Comment by miconda** [comment]
The commits for new features should not be mixed with changes for formatting or renaming of functions/macros in existing code, because it is not easy to review what are the actual new additions. Please rework the changes and make a commit dedicated only to the new feature.

Moreover, LM_* macros are also new ones that prefix the log messages with function name, etc... no need to change those macros at all. If we decide to replace/remove them, then it will be easier to do substituttion on a LM_XYZ than on XYZ.

**Comment by dunst0** [comment]
Thanks for the remarks, I will rework the changes.

**Comment by dunst0** [comment]
@miconda hope it is Ok how I did the changes you asked for.

**Comment by miconda** [comment]
Thanks!

**Pull request merged**
