### PR TITLE
tests/travis: migrate to docker environment

### PR DESCRIPTION
**Pull request by linuxmaniac**
- use jessie as default distribution

### CODE REVIEW

**Comment by linuxmaniac** [comment]
- clang build is broken on 4.1 right now https://s3.amazonaws.com/archive.travis-ci.org/jobs/92951963/log.txt from https://travis-ci.org/kamailio/kamailio/jobs/92951963

@miconda Should I just disable clang build for 4.1?

**Comment by miconda** [comment]
That error is probably only for 4.1, because for recent versions we renamed the 'printf' member of rpc API structure. Can you disable compiling with clang only on branch 4.1?

**Comment by linuxmaniac** [comment]
Yes, this last version only builds gcc

**Comment by miconda** [comment]
OK -- missed your explicit note about 4.1 -- clang compilation can be disabled for it.

**Pull request merged**
