### PR TITLE
core: timer_proc don't execute timers on shutdown phase

### PR DESCRIPTION
**Pull request by linuxmaniac**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [X] Tested changes locally

#### Description

If kamailio is in the shutdown phase proc timers should not be executed since memory objects are getting destroyed and cores could happen

### CODE REVIEW

**Comment by miconda** [comment]
I think `ksr_shutdown_phase()` has to be used in this case, because the timers are different processes, `destroy_modules_phase()` is for main/parent process only.

**Comment by linuxmaniac** [comment]
Nothing explodes in my tests

**Comment by linuxmaniac** [comment]
@miconda do you think this can be merged?

**Comment by miconda** [comment]
Yes, thanks!

**Pull request merged**
