### PR TITLE
rtpengine: remove square brackets from IPv6 address for getaddrinfo

### PR DESCRIPTION
**Pull request by Den4t**
rtpengine: IPv6 address in square brackets interpreted as FQDN.

- After loading from DB, rn_address is in form:` [x:x:x:x:x:x:x:x]:nnnn`, getaddrinfo function expect ipv6 in node argument without square brackets, otherwise, the argument is interpreted as FQDN.

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
@Den4t: have you checked that setting 0 in place of `]` is not having other side effects? I didn't notice any restore.

@rfuchs: any opinion on this patch?

**Comment by Den4t** [comment]
@miconda 
>>have you checked that setting 0 in place of ] is not having other side effects? I didn't notice any restore.

Yes, hp - is a pointer to pkg_malloc-ed hostname variable, this var is freed right after getaddrinfo and not used any more.
I tested this patch localy, work as expected.

**Comment by rfuchs** [comment]
> @Den4t: have you checked that setting 0 in place of `]` is not having other side effects? I didn't notice any restore.
> 
> @rfuchs: any opinion on this patch?

Looks good to me

**Comment by miconda** [comment]
Thanks, merging it!

**Pull request merged**
