### PR TITLE
lcr: add counters per gateway

### PR DESCRIPTION
**Pull request by Ozzyboshi**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #3372

#### Description
Implementing the suggesting lcr counters per gateway

### CODE REVIEW

**Comment by miconda** [comment]
The patch seems substantial in size, probably @juha-h, as main author of lcr module, should look over it before merging.

**Comment by juha-h** [comment]
I did some reading of the code and looks like it does not affect current behavior nor have any performance impact if the the stats are off.

But if I understood correctly, in the PR, matching of a SIP request/reply to an lcr gw is done based on IP address/port (`fetch_gw_id` function).  On my LCR module web page, I have:
```
LCR Instance 'default' Gateway 'test'

Inbound Properties
Common Name or IP Address | Transport

Outbound Properties
IP Address or Domain Name | Port | Transport
```
That is, it is possible that LCR  module does not have any knowledge of the IP address/port of a gateway.

The only way I can find if a request comes from a gateway specified by Common Name is in the script like this:
```
        $var(gw_in_id) = $sht(htable=>cn::$tls_peer_subject_cn::gw_id);
```
That is, looking a common name match from htable.

So unless I didn't read the code correctly, I don't consider it a good idea to have a stats feature that applies only to some gateways.

**Comment by Ozzyboshi** [comment]
Yes,counters will be only incremented if ip and port are maching as you said.
This is because ip and port is how I usually store in the lcr table and my commit is just based on my needs.
Maybe someone in the future can improve my commit to cover all cases.
For now I just added a notice on the docs describing this behaviour.

**Comment by juha-h** [comment]
Alessio Garzi writes:

> Yes,counters will be only incremented if ip and port are maching as you said.
> This is because ip and port is how I usually store in the lcr table and my commit is just based on my needs.
> Maybe someone in the future can improve my commit to cover all cases.
> For now I just added a notice on the docs describing this behaviour.

As I wrote, I don't consider it a good idea to include a feature that
only works in some situations.

Is there some reason why you can't implement the same in the script
without modifying lcr module?

**Pull request closed without merging**
