### PR TITLE
Providing dp_reload function to the cfg

### PR DESCRIPTION
**Pull request by luismartingil**

### CODE REVIEW

**Comment by oej** [comment]
Why not support reload from text file too? Why only database?

(Sorry for all the questions)

**Comment by luismartingil** [comment]
Hi @oej, this just mimics the actual RPC and IM reload implementation...

**Comment by oej** [comment]
No it doesn't. 
```
/*
 * RPC command to reload dispatcher destination sets
 */
static void dispatcher_rpc_reload(rpc_t* rpc, void* ctx)
{
        if(!ds_db_url.s) {
                if (ds_load_list(dslistfile)!=0) {
                        rpc->fault(ctx, 500, "Reload Failed");
                        return;
                }
        } else {
                if(ds_reload_db()<0) {
                        rpc->fault(ctx, 500, "Reload Failed");
                        return;
                }
        }
        return;
}
```
From dispatcher.c - notice the reload from table?

**Comment by luismartingil** [comment]
Notice this _PR_ is about dialplan (not dispatcher)...

`/*
 * RPC command to reload dialplan table
 */
static void dialplan_rpc_reload(rpc_t* rpc, void* ctx)
{
	if (dp_connect_db() < 0) {
		LM_ERR("failed to reload rules fron database (db connect)\n");
		rpc->fault(ctx, 500, "DB Connection Error");
		return;
	}

	if(dp_load_db() != 0){
		LM_ERR("failed to reload rules fron database (db load)\n");
		dp_disconnect_db();
		rpc->fault(ctx, 500, "Dialplan Reload Failed");
		return;
	}

	dp_disconnect_db();
	return;
}
`

**Comment by oej** [comment]
Haha me bad. Sorry!

**Comment by luismartingil** [comment]
@miconda I'll just leave this _PR_ as it is, please let me know if you want to integrate this change and if you'll merge the changes and close the _PR_ or you want me to do it. Thanks!

**Comment by oej** [comment]
Still laughing. My head was full of dispatcher code as I was reading that code for other reasons, so I fall into a trap. Awfully sorry for that.

**Comment by oej** [comment]
Will review again and possibly commit.

**Pull request merged**
