### PR TITLE
rtpengine: fix pkg mem leak in send_rtpp_command()

### PR DESCRIPTION
**Pull request by vijaykumar-exotel**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #3777
#### Description

- freed request.s after sending request to websocket in send_rtpp_command method.

### CODE REVIEW

**Comment by henningw** [comment]
Looks good to me. The lwsc module seems to malloc its own memory for the sdata, so it should be freed in rtpengine module code.

**Comment by vijaykumar-exotel** [comment]
Hi @henningw , 
memory is getting allocated in line 3660 ,  which was not getting freed.
request.s = pkg_malloc(len + 1);

**Comment by henningw** [comment]
> Hi @henningw , memory is getting allocated in line 3660 , which was not getting freed. request.s = pkg_malloc(len + 1);

Sure. :-) I checked in the lwsc module (which is actually called from the rtpengine module in this function part) to no have a double free. If nobody else comment, I will merge it tomorrow.

**Comment by vijaykumar-exotel** [comment]
Sure. Thanks @henningw

**Pull request merged**
