### PR TITLE
p_usrloc: Add use_domain_crc32 modparam

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Needed a way to use_domain but calculate crc32 for user part only.

### CODE REVIEW

**Comment by smititelu** [comment]
checks errors on docker pull

**Comment by linuxmaniac** [comment]
That's on me. Working on a solution

**Comment by linuxmaniac** [comment]
@smititelu can you please rebase and push force the PR

**Comment by smititelu** [comment]
Thanks @linuxmaniac .

**Comment by miconda** [comment]
@smititelu: fine for me, you can merge it.

**Pull request merged**
