### PR TITLE
ims_registrar_scscf: 200OK changes according to RFC3261

### PR DESCRIPTION
**Pull request by alexyosifov**
Added corrections for 200OK reply on Re-Registration
according to RFC3261 - registrar respond with multiple bindings in case
of multiple bindings.
Added a new parameter skip_multiple_bindings_on_reg_resp
for 200OK reply used for Re-Registration. Default value is 0.
If set to 1 - registrar replies only with current contact, not with
multiple bindings.

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
@alexyosifov: thanks for this PR! Given that you are quite active with the IMS extensions and we lack contributors there, I am going to grant access to the repository so you can push commits directly, or accept and merge PRs on those components.

You can still do PRs to these modules if you want other developers to comment on the changes. Changing code to other modules or components should still be done with PR to allow the developers to review and avoid conflicts of working on the same code part at that moment.

**Comment by miconda** [comment]
@alexyosifov: invitation for developers team sent, once you accept it, you should be able to merge this PR, which you can do at your convenience.

**Comment by alexyosifov** [comment]
@miconda Thank you for your trust!
It will be merged in 2-3 days if there are no other comments.

**Comment by linuxmaniac** [comment]
@alexyosifov please, before merge, rebase so we can avoid the merge in git history

``Merge pull request #3146 from alexyosifov/skip_multiple_bindings_on_reg_resp``

**Pull request merged**
