### PR TITLE
change ims_diameter_server to allow binary data transcoding

### PR DESCRIPTION
**Pull request by szcom**
#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Diameter request MAR and corresponding response MAA both contain authentication vectors in binary form. Ims_diameter_server lacks functionality to convert binary arrays to json and back. This pr is a couple of minor fixes to rectify the issue:
* when converting Diameter binary vector to json use %02x in sprintf() to form a proper hexdump which is possible to decode on json side. The hexdump is sent in "data" key value pair as string.
* introduce new key value pair "hexdump" in json which will contain hex dump of binary vector formed on json side. ims_diameter_server converts it to Diameter AVP using hex dump to binary transcoding.

### CODE REVIEW

**Comment by miconda** [comment]
Could you make a single patch and format the commit message as per contributing guidelines?

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format

If not coming handy to you, is still ok. Once @ngvoice and others approve this PR, I can merge it manually, fixing the commit message format -- so do not merge it from the web interface here.

**Comment by szcom** [comment]
@miconda ok, sorry

**Comment by miconda** [comment]
I guess @ngvoice has been busy.

One question @szcom - is this change backwards compatible, in the way that is not breaking things when used together with older versions? If not, maybe it is better to add a mod param to control that, making it also easier to decide to merge.

**Comment by ngvoice** [comment]
Hi,

sorry, we seem to do "Worldwide voice"*) these days... ;-)

Reviewed and Okay!

Thanks for the commit,
Carsten

*) "Worldwide-Voice" was the claim of my former employer, but they never lived up to it.....

**Pull request merged**
