### PR TITLE
added RURI-pattern matching and priority

### PR DESCRIPTION
**Pull request by eschmidbauer**
Hello,
This pull request adds 2 features. 
--Prioritize the trusted records (highest to lowest priority)
--Match from-uri AND request-uri, if either is blank only one is matched.
Please review the pull request and let me know if any other changes are needed.
Thank you.
Emmanuel

### CODE REVIEW

**Comment by eschmidbauer** [comment]
Hello,
Any chance this can be reviewed before the feature request window closes?
Thanks,
Emmanuel

**Comment by miconda** [comment]
Master branch will be frozen again after at least 6 months, plenty of time to get new features in v4.4.

The patch got big because you changed the order of existing columns, not adding new column as last one, but inserting in between, so it was not trivial to analyze quickly when I tried a while ago as I found a bit of spare time.

Most likely I can allocate some time next week, as v4.3 will be out this week.

**Comment by eschmidbauer** [comment]
Thank you for the response.
Yes, I did re-order the fields to make it more comprehensive in the long run.
I've been running this patch on my test machine for several weeks without any issues.
I hope you will consider reviewing and testing soon as we want to put this in production.
Thanks,
Emmanuel

**Comment by miconda** [comment]
Some comments:

  * loading ordered on priority is using an SQL extension, making the module to fail when used with db_text, db_mongodb or other no-sql backends. This has to be reworked to get rid of the ordering extension specific to sql or made a configuration file option (module parameter)
  * is it a reason to restrict the matching only to r-uri parts of user@domain? May be useful to match also on transport or other parameters. I would live the matching against the full value of the r-uri inside the code. In the config one can set the $ru to whatever it likes to match
  * the code around the printing of sort_order is looking weird, as you add sort_order.len (which is set before to 0) to the buffer -- it is harmless but doesn't look good when someone is checking the code

**Comment by miconda** [comment]
Add the changes to the db schema -- you have to update the xml file in lib/srdb1/schema/.

**Comment by miconda** [comment]
And extend the documentation of the module with the appropriate description and new parameters -- changes have to be done to xml files in modules/permissions/doc/

**Comment by eschmidbauer** [comment]
Hello, 
made changes as you requested.
Please see latest commit.
Thanks,
Emmanuel

**Comment by miconda** [comment]
The commit message is not relevant for the all changes done by the patch, but reflects the last operation you did as per comments in this discussion. It is not suitable for the log of source code changes history.

I will apply the patch manually this time if all ok with the review. But for the future be sure you follow the guidelines for commit messages from:

  * http://www.kamailio.org/wiki/devel/git-commit-guidelines#commit_message

Note also that you can have many commits in the same pull request. No need to rework a new patch always, you can add another patch to complete the changes done with previous patches.

**Comment by eschmidbauer** [comment]
Hello,
You can download the full git diff (it applies clean to master branch) here http://paste.debian.net/download/231826
Thank you.
Emmanuel

**Comment by miconda** [comment]
I applied the patch manually, split in few commits, per components.

The diff for each commit is available also on github, at:

  * https://github.com/eschmidbauer/kamailio/commit/72259b0a9b1f0f9d96e12e4bfa11ed8dbcf5dfcf.diff

Add .diff to the commit path.

I fixed the upgrade of table version for trusted.

You have to make a new pull request to update the docs regarding the priority, to specify what kind of value represents higher priority.

**Pull request closed without merging**
