### PR TITLE
Bugfix trash expires

### PR DESCRIPTION
**Pull request by christoph-v**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally against Version 5.1.0
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

When old (maybe forgotten) Contacts expire in S-CSCF, then current - wanted - calls will be deleted, which is not wanted. Reason is the usage of "=" Operator instead "==" Operator in ims_usrloc_scscf module.

### CODE REVIEW

**Comment by linuxmaniac** [comment]
@christoph-v can you please send this change as one commit, please. ``git rebase -i origin/master`` and ``git push --force`` are your friends

**Comment by christoph-v** [comment]
Should be reduced to one commit, now. Please try again

**Comment by miconda** [comment]
@ngvoice - any comment on this change? It looks like a simple fix, but better to have a second review on it.

**Comment by christoph-v** [comment]
@SurendraPlivo : yes, we tested the fix with following test case:
1) Register first contact (expires 3600)
2) Register second contact (expires 120)
3) Initiate call from first contact
4) wait a few minutes
5) Call should NOT be torn down by S-CSCF, when second contact expires (without fix, it IS)
6) send bye, end the test case

**Pull request merged**
