### PR TITLE
cmake: Link internal libraries to core and remove them from modules

### PR DESCRIPTION
**Pull request by xkaraman**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #4041

### CODE REVIEW

**Comment by miconda** [comment]
If I am not misunderstanding the PR and changes in some cmake-files, the internal libs are still compiled as libraries (.so files).

The target is to have them compiled as part of the core, so there will be just kamailio binary and no .so files other than the modules. In other words, the `.c` and `.h` files in the `src/lib/.../` are part of the core and, as an example. should be compiled into `kamailio` in the same way `src/core/mem/*.{c,h}` are compiled.

With the old-Makefiles, once I did the changes for #4041 , the core files are including the internal lib files, see:

- https://github.com/kamailio/kamailio/blob/master/src/Makefile.sources#L13-L21

**Comment by xkaraman** [comment]
Ahh, ok no produced libraries at all and compile everything into the kamailio binary! I will make sure to update the PR accordingly.

**Comment by xkaraman** [comment]
@miconda This should be as expected now. All the libs are compiled in the kamailio binary and the modules are linked against that.

**Comment by miconda** [comment]
Thanks! Fine for me to merge, any tunings that might be needed can be done later once testing

**Comment by henningw** [comment]
Just a note, on a fresh checkout of kamailio there is currently a problem related to the generation of the parser files after this PR. @xkaraman is working on it.

**Comment by xkaraman** [comment]
@henningw This should be fixed in 9ff2bb869dafca8521a0da7f112c3846f86c5f7e.

**Pull request merged**
