### PR TITLE
ims_dialog: Add support for database backend

### PR DESCRIPTION
**Pull request by mtryfoss**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #3602 

#### Description
Added missing code for database backend to work. Tested basic scenarios locally for all db modes.
DB schema could be tweaked according to my thoughts in issue #3602, but that also applies to several other modules which are done in the same matter. Because of that, I didn't consider such a change now.

### CODE REVIEW

**Comment by mtryfoss** [comment]
Seems like there's some issue with the CodeQL Analyzer (runner image out of disk space)?

**Comment by miconda** [comment]
Thanks! CodeQL can indeed fail from other reasons than the code, can be ignored if that happens.

Regarding the patch of the PR, I could spot only a database delete operation being added. The commit message says `Add support for database backend`. Was there code for database support but not activated? If yes, only the db delete operation was missing?

**Comment by mtryfoss** [comment]
Like I wrote in the ticket related to this task, most of the stuff was there already - but it both caused a crash and was not fully functional. Entries were being written to the database, but was not restored correctly on startup.

I assume the old dialog module was used as a basis and that the code for db operations was not finalized with the new structure.

The missing delete was probably a result of that, since this new module got two tables ("in" and "out") compared to only one in the old module.

**Comment by mtryfoss** [comment]
My plan is to have this merged and then continue working on db operations for the ims_charging module. I just wanted to have this completed first, since the other part will not work without it.

**Comment by miconda** [comment]
Thanks for the details, I am not using the module, I wanted to be sure nothing was omitted -- I am going to merge it.

**Pull request merged**
