### PR TITLE
sanity: use debug log level when content length header is missing

### PR DESCRIPTION
**Pull request by lassebm**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
This is to align behavior with the remaining checks. The example configuration enable the content length sanity check and prior to this change would warn when SIP messages without body were received.

### CODE REVIEW

**Comment by ovoshlook** [comment]
But WARNING looks correct behaviour because of [RFC](https://tools.ietf.org/html/rfc3261#page-169) specifications of content-length header, why it should be changed to DBG?

**Comment by henningw** [comment]
Yes, it is indeed a SHOULD. In the end one could simply deactivate it in the cfg (with the sanity flag) or just increase the log level to not include WARN.

**Comment by henningw** [comment]
Close this one

**Comment by lassebm** [comment]
I agree with closing after reading the RFC section once again 👍

**Pull request closed without merging**
