### PR TITLE
pkg: fixed SystemD service install path

### PR DESCRIPTION
**Pull request by guss77**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
- `systemd/system/service` is not a real directory. Services should be in `systemd/system` to be loaded by SystemD.
- Also, fixed typo in `%files`.

### CODE REVIEW

**Comment by miconda** [comment]
The commit message first line is not formatted according to the contributing guidelines:

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format

You can reformat the commit message if you want, then the PR can be merged directly.

Otherwise the patch can be applied manually this time and you keep in mind for future commits.

Note also that the specs of oracle linux were not properly maintained lately, if you want to update their content for the last version, see the spec file from obs folder, that should be pretty actual.

**Comment by sergey-safarov** [comment]
Oracle dist based in RHEL dist and must be packaged using this [packaging files](https://github.com/kamailio/kamailio/tree/master/pkg/kamailio/obs)

This already documented at Oracle [README.md](https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/oracle/README.md)

I prefer to delete not maintained oracle packaging files and leave only `README.md` file.

**Comment by guss77** [comment]
> I prefer to delete not maintained oracle packaging files and leave only `README.md` file.

Sounds like a valid solution - if the position of the project is that RPM builds should be based on `pkg/kamailio/obs` instead of any of the `pkg/kamailio/oracle` files, I can work with that.

I'm currently building RPMs for my use based on the oracle file, and as it has a few problems, I keep patching it locally for each release - which is getting tedious. I'll update my packaging to use the `obs` file and will submit patches as relevant (and I'll make sure to write comments as required, next time).

**Comment by sergey-safarov** [comment]
You are welcome to update OBS packaging file.

**Pull request closed without merging**
