### PR TITLE
pkg: fixed location of ChangeLog

### PR DESCRIPTION
**Pull request by adubovikov**
the packaging system couldn't find ChangeLog, since the sources has been moved to a src directory.

### CODE REVIEW

**Comment by adubovikov** [comment]
@linuxmaniac please check if it's correct solution, because I got an error about "ChangeLog has been not found"...

thank you!

**Comment by linuxmaniac** [comment]
what? ChangeLog file is located in the same spot
https://github.com/kamailio/kamailio/blob/master/ChangeLog

Another problem is that file is not changed since 4.4.0

**Comment by adubovikov** [comment]
the location of ChangeLog has been not changed, but the location of the sources has been changed.

here is log:

```
shurik@iris02:~/KAMAILIO$   wget https://www.kamailio.org/pub/kamailio/latest/src/kamailio-5.0.1_src.tar.gz
--2017-06-01 14:21:52--  https://www.kamailio.org/pub/kamailio/latest/src/kamailio-5.0.1_src.tar.gz
Resolving www.kamailio.org (www.kamailio.org)... 193.22.119.66, 2a00:d60:0:400::2
Connecting to www.kamailio.org (www.kamailio.org)|193.22.119.66|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11614011 (11M) [application/x-gzip]
Saving to: ‘kamailio-5.0.1_src.tar.gz’
 
kamailio-5.0.1_src.tar.gz                                   100%[==========================================================================================================================================>]  11.08M  19.4MB/s   in 0.6s
 
2017-06-01 14:21:58 (19.4 MB/s) - ‘kamailio-5.0.1_src.tar.gz’ saved [11614011/11614011]
 
shurik@iris02:~/KAMAILIO$   tar xzf kamailio-5.0.1_src.tar.gz
shurik@iris02:~/KAMAILIO$ cd kamailio-5.0.1/
shurik@iris02:~/KAMAILIO/kamailio-5.0.1$ cd pkg/kamailio/deb/
shurik@iris02:~/KAMAILIO/kamailio-5.0.1/pkg/kamailio/deb$ mv debian debian-orig
shurik@iris02:~/KAMAILIO/kamailio-5.0.1/pkg/kamailio/deb$ ln -s jessie debian
shurik@iris02:~/KAMAILIO/kamailio-5.0.1/pkg/kamailio/deb$ cd ../../..
shurik@iris02:~/KAMAILIO/kamailio-5.0.1$   make deb
make -C src/ deb
make[1]: Entering directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
Makefile:107: config.mak: No such file or directory
target architecture <x86_64>, host architecture <x86_64>
making config...
dpkg-buildpackage: source package kamailio
dpkg-buildpackage: source version 5.0.1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Victor Seva <vseva@debian.org>
dpkg-buildpackage: host architecture amd64
dpkg-source --before-build src
.....
dh_lintian
dh_installchangelogs ChangeLog
install: cannot stat ‘ChangeLog’: No such file or directory
dh_installchangelogs: install -o 0 -g 0 -p -m644 ChangeLog debian/kamailio/usr/share/doc/kamailio/changelog returned exit code 1
debian/rules:177: recipe for target 'binary-common' failed
make[3]: *** [binary-common] Error 2
make[3]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
debian/rules:211: recipe for target 'binary-arch' failed
make[2]: *** [binary-arch] Error 2
make[2]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
make[1]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
 ```
and after fix: ChangeLog -> ../ChangeLog
 
```
make deb
...
/usr/bin/make --no-print-directory -C lib maintainer-clean
Making maintainer-clean in srdb1
Making maintainer-clean in srdb2
Making maintainer-clean in ims
Making maintainer-clean in xcap
Making maintainer-clean in trie
Making maintainer-clean in print
Making maintainer-clean in cds
Making maintainer-clean in presence
Making maintainer-clean in srutils
Making maintainer-clean in shm_regex
Making maintainer-clean in binrpc
rm -f config.mak
rm -f modules.lst
make[3]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
dh_clean
make[2]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
dpkg-source --after-build src
dpkg-buildpackage: full upload; Debian-native package (full source is included)
make[1]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'

**Comment by miconda** [comment]
It could be that the deb building by Debian project is using a different way, not `make deb` from our makefiles.

I wonder if moving the `deb` target from `src/Makefile` to `Makefile` can be a fix... I can't test it right now myself.

**Comment by linuxmaniac** [comment]
Problem here is that make deb rules are wrong. There is were we have to make the fix.

**Comment by adubovikov** [comment]
ok. I will test @miconda solution and let you know

**Comment by linuxmaniac** [comment]
@adubovikov try this ( without your patch)
```
diff --git a/src/Makefile b/src/Makefile
index bbf5f8db8..612bea918 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -609,25 +609,27 @@ bin:
 
 .PHONY: deb
 deb:
-       -@if [ -d debian ]; then \
+       (cd ..; \
+       if [ -d debian ]; then \
                dpkg-buildpackage -rfakeroot -tc; \
                rm debian; \
        else \
-               ln -s ../pkg/$(MAIN_NAME)/deb/debian debian; \
+               ln -s pkg/$(MAIN_NAME)/deb/debian debian; \
                dpkg-buildpackage -rfakeroot -tc; \
                rm debian; \
-       fi
+       fi)
 
 .PHONY: deb-stable
 deb-stable:
-       -@if [ -d debian ]; then \
+       (cd ..; \
+       if [ -d debian ]; then \
                dpkg-buildpackage -rfakeroot -tc; \
                rm debian; \
        else \
-               ln -s ../pkg/$(MAIN_NAME)/deb/jessie debian; \
+               ln -s pkg/$(MAIN_NAME)/deb/jessie debian; \
                dpkg-buildpackage -rfakeroot -tc; \
                rm debian; \
-       fi
+       fi)
 
 .PHONY: sunpkg
 sunpkg:
```

**Comment by linuxmaniac** [comment]
FTR We don't use that rule at all in the process of building the debs

**Comment by miconda** [comment]
@linuxmaniac - I guessed that, the `make deb` was added for convenience, I use it sometimes when doing releases to see it compiles ok, or run directly dpkg-buildpackage, which I guess I did for v5.0.

@adubovikov - have you had the time to check the patch from @linuxmaniac? If all ok, then it should be pushed to git repository.

**Comment by adubovikov** [comment]
Yep. all good, only problem with sign, but this is IMHO different issue...

```
make[5]: *** No rule to make target 'maintainer-clean'.  Stop.
/usr/bin/make --no-print-directory -C lib maintainer-clean
Making maintainer-clean in srdb1
Making maintainer-clean in srdb2
Making maintainer-clean in ims
Making maintainer-clean in xcap
Making maintainer-clean in trie
Making maintainer-clean in print
Making maintainer-clean in cds
Making maintainer-clean in presence
Making maintainer-clean in srutils
Making maintainer-clean in shm_regex
Making maintainer-clean in binrpc
rm -f config.mak
rm -f modules.lst
make[4]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
make[3]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1'
dh_clean
make[2]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1'
 dpkg-source --after-build kamailio-5.0.1
dpkg-buildpackage: full upload; Debian-native package (full source is included)
 signfile kamailio_5.0.1.dsc
gpg: skipped "Victor Seva <vseva@debian.org>": No secret key
gpg: dpkg-sign.UQsQaC5d/kamailio_5.0.1.dsc: clearsign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc and .changes file
make[1]: Leaving directory '/home/shurik/KAMAILIO/kamailio-5.0.1/src'
```
```
ls  kamailio*.deb
kamailio_5.0.1_amd64.deb                       kamailio-dnssec-modules_5.0.1_amd64.deb  kamailio-ldap-modules_5.0.1_amd64.deb       kamailio-postgres-modules_5.0.1_amd64.deb   kamailio-sqlite-modules_5.0.1_amd64.deb
kamailio-autheph-modules_5.0.1_amd64.deb       kamailio-erlang-modules_5.0.1_amd64.deb  kamailio-lua-modules_5.0.1_amd64.deb        kamailio-presence-modules_5.0.1_amd64.deb   kamailio-systemd-modules_5.0.1_amd64.deb
kamailio-berkeley-bin_5.0.1_amd64.deb          kamailio-extra-modules_5.0.1_amd64.deb   kamailio-memcached-modules_5.0.1_amd64.deb  kamailio-python-modules_5.0.1_amd64.deb     kamailio-tls-modules_5.0.1_amd64.deb
kamailio-berkeley-modules_5.0.1_amd64.deb      kamailio-geoip-modules_5.0.1_amd64.deb   kamailio-mono-modules_5.0.1_amd64.deb       kamailio-rabbitmq-modules_5.0.1_amd64.deb   kamailio-unixodbc-modules_5.0.1_amd64.deb
kamailio-carrierroute-modules_5.0.1_amd64.deb  kamailio-ims-modules_5.0.1_amd64.deb     kamailio-mysql-modules_5.0.1_amd64.deb      kamailio-radius-modules_5.0.1_amd64.deb     kamailio-utils-modules_5.0.1_amd64.deb
kamailio-cnxcc-modules_5.0.1_amd64.deb         kamailio-java-modules_5.0.1_amd64.deb    kamailio-nth_5.0.1_amd64.deb                kamailio-redis-modules_5.0.1_amd64.deb      kamailio-websocket-modules_5.0.1_amd64.deb
kamailio-cpl-modules_5.0.1_amd64.deb           kamailio-json-modules_5.0.1_amd64.deb    kamailio-outbound-modules_5.0.1_amd64.deb   kamailio-sctp-modules_5.0.1_amd64.deb       kamailio-xml-modules_5.0.1_amd64.deb
kamailio-dbg_5.0.1_amd64.deb                   kamailio-kazoo-modules_5.0.1_amd64.deb   kamailio-perl-modules_5.0.1_amd64.deb       kamailio-snmpstats-modules_5.0.1_amd64.deb  kamailio-xmpp-modules_5.0.1_amd64.deb

**Comment by adubovikov** [comment]
@miconda  feel free to close the PR ;-)

**Comment by miconda** [comment]
@adubovikov - thanks for testing and feedback! Signing is a matter of providing a certificate to sign the packages, not offered by `make deb`, iirc, its about a dpkg-buildpackage parameter.

@linuxmaniac - will you push your patch and backport to 5.0?

**Comment by linuxmaniac** [comment]
@miconda yes, I'm going to do that and remove the signing phase too

**Pull request closed without merging**
