### PR TITLE
Fix wss forwarding

### PR DESCRIPTION
**Pull request by joelbax**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
The rfc7118 (https://www.rfc-editor.org/rfc/rfc7118.html) defines only `transport=ws`, where have you met `transport=wss`?

**Comment by joelbax** [comment]
@miconda  SIP.js is including it in the contact header, then, the register module keeps it. I think this is also happening with pjsip but I haven't had a chance to properly verify it. 
Also, IMHO, I think that this is still a misleading subject because, referring to Iñaki's message in jssip: https://groups.google.com/g/jssip/c/tWhZla-3Ktk, he says that it's like RFC3261 not defining `transport=tls` (that is actually defined in RTC5630) but we use it.
Maybe time to do a RTC5630 equivalent for 7118 and define some uses for wss transport? :)

**Comment by miconda** [comment]
@joelbax: I think RFC3261 mention the deprecation of `transport=tls` for `sips` scheme (ie., end to end secure transmission), but it is defined in the grammar (e.g., for hop-by-hop tls usage). See RFC3261 page 223:

```
transport-param   =  "transport="
                     ( "udp" / "tcp" / "sctp" / "tls"
                     / other-transport)

```

  - https://datatracker.ietf.org/doc/html/rfc3261

**Comment by joelbax** [comment]
@miconda  our bad, SIP.js was configured to use transport=wss. Closing this PR. 

I'm sorry for the inconvenience.

**Comment by miconda** [comment]
OK, though somehow I agree that not having wss in the transport is confusing, because it is in Via, but I wanted to be sure I haven't missed any new specs introducing it.

**Pull request closed without merging**
