### PR TITLE
stirshaken: Properly handle intermediary/chain certificates when caching certificates

### PR DESCRIPTION
**Pull request by mrtrev**
stirshaken: Properly handle intermediary/chain certificates when caching certificates
- requires patch to libstirshaken (https://github.com/signalwire/libstirshaken/pull/124) to do anything
- if patched version of libstirshaken detected, uses new methods to store all intermediary certs
- unrelated minor logging tweaks

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

The guts of this PR have been submitted to the libstirshaken side based on the suggestions of my previous PR.  I didn't mean to close it but since I hadn't created a branch, it got closed when I updated my repo.  Original PR is https://github.com/kamailio/kamailio/pull/3175

I've been running this in production for a day and it seems to be performing the same as my previous attempt.

### CODE REVIEW

**Comment by mrtrev** [comment]
@miconda @piotrgregor @henningw Tagging you as I accidentally closed the previous PR you commented on.

**Comment by gled-rs** [comment]
just curious if you see a memleak with that code and libstirshaken with PR124.

I applied the patch to branch 5.6 and can see the free memory going down since the last restart.

It seems  to be caused by the call to stirshaken_check_identity(), as commenting it and using secsipid_check_identity("") no leaks are present ( did an A/B test with same config just a line commented out ).

Params tested and still leaking:
- cache certificate on or off.
- root chain validation on or off.
- vs_*_pvname set or unset.

**Comment by mrtrev** [comment]
@gled-rs https://github.com/signalwire/libstirshaken/pull/125 should help.

**Comment by piotrgregor** [comment]
> Upon closer inspection of libstirshaken it doesn't seem to care about freeing the certificate chain in many cases which could explain it regardless if any of the recent PRs are applied.

Correct. libstirshaken didn't make a use of `xchain` only after your PR @mrtrev 

in particular this was never used https://github.com/signalwire/libstirshaken/blob/e8289b0967a7b008dd666ee888094f182f64d94d/src/stir_shaken_ssl.c#L1900

so it is on your behalf to make sure it's correctly initialised and freed

**Comment by mrtrev** [comment]
> Correct. libstirshaken didn't make a use of xchain only after your PR

Actually before I started tinkering, it was using that code you linked to, which is why it could validate certificates the first time yet failed when they loaded from cache.  It leaks memory even when loading a certificate+intermediary the first time.  It simply leaks even more now that it can load certificate+intermediary from cache.

At any rate I have submitted https://github.com/signalwire/libstirshaken/pull/125 that will ensure xchain is cleaned up in all use cases.

All 3 of these PRs can be merged independently of each other.

**Comment by piotrgregor** [comment]
I got no time to test that right now, but that could be the case. Thanks.

**Comment by gled-rs** [comment]
test in progress, but it's been only a couple hours, so will need more time to be sure. 

This looks good though, thanks @mrtrev :)

**Comment by gled-rs** [comment]
seems like the leak is gone, well done @mrtrev !

**Comment by henningw** [comment]
Thanks for the pull request and the feedback/tests. This seems to be a small extension, which also has backward compatiblity if the library does not support it. If there are no more comments, it will be merged in the next days.

**Comment by mrtrev** [comment]
@henningw Any chance this could also be cherry picked into the 5.6 branch as well?

**Comment by henningw** [comment]
I've merged it into git master. Regarding chery picking into stable branch, as far as I understood it, it seems to work generally, just without caching the certificates. So its seems to be not a bug fix, but a feature extension, and these are not introduced into stable branches.

**Comment by mrtrev** [comment]
Thanks for merging to master.

As far as the problem, I do see it as a bug fix.  Currently if you choose to cache certificates, validation will fail on any cached certificate (at least in cases where an intermediary cert is required, which is most if not all cases in Canada).  The workaround is to disable caching, which is a very high cost workaround.

**Comment by piotrgregor** [comment]
It would not fail on any cached cetificates, that's not a problem this solved... What this fixes instead, is handling of cached certificates with intermediary certs and probably a memory leak that would manifestate for any cached certificate.

**Comment by mrtrev** [comment]
Hi @piotrgregor 

The whole reason I started digging into this is precisely because I was seeing this in Kamailio logs

ERROR: stirshaken [stirshaken_mod.c:488]: ki_stirshaken_check_identity(): SIP Identity Header did not pass verification
ERROR: stirshaken [stirshaken_mod.c:560]: ki_stirshaken_check_identity(): identity check: fail

Upon investigation I determined this happened any time a certificate was cached that relied on a chain.  The first call will succeed but any subsequent calls fail until the cached certificate expires or is manually deleted.  Then the next call will validate ok, but subsequent calls fail.

This happens today with 5.6.2 on my unpatched machine.

**Comment by henningw** [comment]
Ok, if it fails in the caching mode then its indeed a bug fix. I've cherry-picked it to the 5.6 and 5.5 branches.

**Pull request merged**
