### PR TITLE
mqueue: add support for db persistency

### PR DESCRIPTION
**Pull request by jchavanton**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] New feature (non-breaking change which adds new functionality)

#### Checklist:

- [x] Tested changes locally

#### Description

- adding support for persistent mqueue in a DB

```
modparam("mqueue", "db_url", "sqlite:////kamailio_db/mqueue.sqlite")
modparam("mqueue", "mqueue", "name=acc_events;size=1000000;dbmode=1")
modparam("acc_json", "output_mqueue", "acc_events")
```

### CODE REVIEW

**Comment by jchavanton** [comment]
@linuxmaniac I guess I need to makr it as a draft until to avoid pushing to often and failing.

I just completed testing, I did some last minute modifications to ensure proper ordering, this is why I changed my mind about WIP vs ready, sorry for the noise.

**Comment by jchavanton** [comment]
@linuxmaniac I am trying to understand the LGTM failure.

```
[2020-06-16 23:12:29] [analysis] [EVALUATION 95/150] [FAIL] Error running query semmlecode-cpp-queries/Security/CWE/CWE-079/CgiXss.ql: OutOfMemory
                                 Query evaluation ran out of memory (maximum allowed memory: 2958MB).
[2020-06-16 23:12:30] [analysis]  Completed analysis for out - snapshot in 78 minutes.
```

**Comment by jchavanton** [comment]
builded and tested locally, seems like it did run out of ram, he found a real problem last time, good work

**Comment by henningw** [comment]
I guess the LGTM failure was just a fluke, now it looks ok. Any updates open from your side?

**Comment by jchavanton** [comment]
> I guess the LGTM failure was just a fluke, now it looks ok. Any updates open from your side?

nothing left to do, ready to merge.

**Comment by miconda** [comment]
Code patch looks ok, maybe some small cosmetic adjustments can be done later (e.g., vars declared at the beginning of blocks), so can be merged from that point of view. But there are some changes to file permissions, adding executable flag:

```
 mode change 100644 => 100755 src/modules/mqueue/Makefile
 mode change 100644 => 100755 src/modules/mqueue/README
 mode change 100644 => 100755 src/modules/mqueue/api.h
 mode change 100644 => 100755 src/modules/mqueue/mqueue_api.c
 mode change 100644 => 100755 src/modules/mqueue/mqueue_api.h
 create mode 100755 src/modules/mqueue/mqueue_db.c
 create mode 100755 src/modules/mqueue/mqueue_db.h
 mode change 100644 => 100755 src/modules/mqueue/mqueue_mod.c
```

Which should not be needed.

**Comment by jchavanton** [comment]
Thanks for having a look, I did persmission adjustments and moved the variable declarations to beginning of scope.
I did not run clang-format, I tried to keep the formatting that was used in the module before.

**Comment by jchavanton** [comment]
I guess I should merge it

**Comment by henningw** [comment]
Sure, go ahead

**Pull request merged**
