### PR TITLE
siptrace: fix tracing messages to database when destination uri not set

### PR DESCRIPTION
**Pull request by ionutionita92**
New additions to siptrace module broke previous functionality.
If sip_trace was used with no param and destination uri was not set
then the current message would not have been traced to database. The
current fix traces always the current message if siptrace function
was called.

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #1942

### CODE REVIEW

**Comment by ionutionita92** [comment]
I did the fix but I think the implementation as it was it's a little broken. That is because you can trace only to database using sip_trace with no arguments, but you can't trace only to database if using correlation_id(this was the case in previous versions). With the new additions you can't trace a dialog only to database. I respected previous implementation, that's why duplicate URI was mandatory, but this check is skipped if sip_trace is used with 0 or 1 argument, which I didn't notice.

**Comment by kamailio-sync** [comment]
Ionut Ionita writes:

> I did the fix but I think the implementation as it was it's a little
> broken. That is because you can trace only to database using sip_trace
> with no arguments, but you can't trace only to database if using
> correlation_id(this was the case in previous versions). With the new
> additions you can't trace a dialog only to database. I respected
> previous implementation, that's why duplicate URI was mandatory, but
> this check is skipped if sip_trace is used with 0 or 1 argument, which
> I didn't notice.

I don't understand from the above, if after this fix the very basic
existing usage of siptrace module (if flag is set sip_trace(); adds the
trace to db) works or not.

I would feel comfortable, if you would leave the 5.2 code of the simple
usage untouched and write your extensions in new sections of the code
rather than making the simple usage a special case in a more complex
implementation.

-- Juha

**Comment by ionutionita92** [comment]
Yes it works but the code in 5.2 is broken. Here's an example, maybe it's more clear:

sip_trace(); /* traces to database only no db url */
sip_trace("", "$var(correlation_id)"); /* does not work; requires valid duplicate uri */
// with my additions
sip_trace("", "$var(correlation_id)", "d"); /* does not work; requires valid duplicate uri */

So there are basically 2 functions:
- no arguments - trace to dabase only;
- with any kind of arguments - trace to duplicate uri and(if set) to database;

**Comment by kamailio-sync** [comment]
Ionut Ionita writes:

> Yes it works but the code in 5.2 is broken. Here's an example, maybe
> it's more clear:
> 
> sip_trace(); /* traces to database only no db url */
> sip_trace("", "$var(correlation_id)"); /* does not work; requires valid duplicate uri */
> // with my additions
> sip_trace("", "$var(correlation_id)", "d"); /* does not work; requires valid duplicate uri */
> 
> So there are basically 2 functions:
> - no arguments - trace to dabase only;
> - with any kind of arguments - trace to duplicate uri and(if set) to
> database;

Then leave implementation of the working part (sip_trace();) as is and
add code to fix the broken part.

-- Juha

**Comment by ionutionita92** [comment]
That's what this commit does, it fixes sip_trace(). Regarding the other part, it's not that obvious to me because if no one reported this maybe it's not an issue and that's the desired usage, elseway I would have fixed it already.

**Comment by miconda** [comment]
I am merging, because I want to do some further adjustments.

**Pull request merged**
