### PR TITLE
pkg/kamailio/obs: Fixed warning about not existen kamailio group

### PR DESCRIPTION
**Pull request by sergey-safarov**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Kamailio is installed to systemd as member of "daemon" group.
Fixed not correct group usage in spec file.

### CODE REVIEW

**Comment by miconda** [comment]
Isn't the group `kamailio` created with the install scripts from rpm? I think on debian, the group is created. It would be good to have same approach on both types of packaging, makes it easier for docs and being coherent no matter of operating system, as systemd is supposed to be same configs everywhere...

**Comment by sergey-safarov** [comment]
I looked into [kamailio.postinst](https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/deb/debian/kamailio.postinst) and can find add user command but cannot see group addition command.
@linuxmaniac could you point me to group addition on debian packaging script.

**Comment by sergey-safarov** [comment]
Looks as here options `--system --group` is create group `kamailio`

**Comment by linuxmaniac** [comment]
From the manpage of adduser:
>  If adduser is called with the --group option and without the --system option, or addgroup is called respectively, a user group will be added.

**Comment by sergey-safarov** [comment]
PR is updated, but not tested locally.
If now of, then i will test locally and squash commits.

**Comment by miconda** [comment]
The diff of the PR looks ok, so can be squashed and committed from my point of view.

**Comment by sergey-safarov** [comment]
PR is squashed and locally tested.
Now ready to merge.

**Comment by miconda** [comment]
@sergey-safarov - you can merge and backport if needed.

**Pull request merged**
