### PR TITLE
dispatcher: congestion detection load balancing

### PR DESCRIPTION
**Pull request by jchavanton**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Presented at Kamailio World 2018, load balancing doing congestion detection
https://www.youtube.com/watch?v=AD0BGaW1g58
 
More information can be found 
http://www.castmm.com/KW2018.pdf
https://github.com/jchavanton/kam_load_balancing

### CODE REVIEW

**Comment by jchavanton** [comment]
Small modifications in this PR, improved the precisions when all Gw are congested, compare to the version I was using before the presentation, the graph in my presentation was showing a lack of precision, better now ! 

all_gw_congested_tuning

**Comment by miconda** [comment]
Couple of things to clarify:

  * this is not a new algorithm, but an option to use with relative weights algorithm
  * I noticed a mutex (lock) was added per set -- it is required only in the context of using this new feature? Does it affect using relative weights without congestion control?
  * the cc attribute needs to be set in all destination records belonging to the same set when wanting to use this new feature?

**Comment by jchavanton** [comment]
Thanks for the comments and questions.

Q: this is not a new algorithm, but an option to use with relative weights algorithm
A: This is correct, I think the documentation is accurate on this point, adding new one was not needed, let me know if you think this would be more clear ?

Q: I noticed a mutex (lock) was added per set -- it is required only in the context of using this new feature? Does it affect using relative weights without congestion control?
A: Correct, it is only needed with CC, because the SIP OPTIONS ping are processed by each worker and they can endup redistributing the weight simultaneously.
Do you think we should try make the lock optional (only enforced when absolutely needed) ?
My tought was that without CC it will be used very unfrequently when a GW times out.

A: the cc attribute needs to be set in all destination records belonging to the same set when wanting to use this new feature?
- correct this is more flexible I believe since you can activate congestion detection per gateway, if CC is not set the GW will always keeps its weight.

**Comment by miconda** [comment]
OK, clarified. I am going to merge it.

**Pull request merged**
