### PR TITLE
Random fixes

### PR DESCRIPTION
**Pull request by gaaf**
Fixes all over. If not all acceptable, please cherry-pick, or let me know so i can remove them.

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally on 5.1, compile tested on master
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by henningw** [comment]
Looks good for me, thank you. I think all changes should be also backported, only the refactoring from f32c643 probably not.

**Comment by henningw** [comment]
Just for the record, 56f1243 caused a crash because of a double free. Was reverted with pull request #1839

**Comment by gaaf** [comment]
> Just for the record, [56f1243](https://github.com/kamailio/kamailio/commit/56f12436c2637a0811da9cc55f48a18e9a995ee0) caused a crash because of a double free. Was reverted with pull request #1839

Hmm, maybe that is different on master. I've been running that on 5.1 for over a year. I'll have a look.

**Comment by henningw** [comment]
Thank you - to be more precise, it was only partially reverted.

**Comment by gaaf** [comment]
I see.

I seem to have commit in my dev tree that removes that line inadvertently. The line reinstating it shouldn't have been present in PR

**Pull request merged**
