### PR TITLE
uac: enable "uac:reply" event route for UAC SIP message timeouts

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

This PR adds 1 UAC module function and 1 TM module modparam. It enables "uac:reply" event route trigger on timeout or non-2xx replies. Basically it:
- adds TMCB_ON_FAILURE callback for UAC
- copies the TM uac content into uas; thus failure route will have the uas to work with. => this part of the code was already there, i just enabled it via (another) modparam. 

So far, is basically tested on our side, without any apparent issues. More testing will follow.

Please have a look on this and tell me what you think about it.

Thank you,
Stefan

### CODE REVIEW

**Comment by smititelu** [comment]
Hi, I see PR build fails because i changed the header of UAC module api `uacb->req_send = uac_req_send;`. The solution(s) I can see right now are either:
1. Guard the uac_req_send(void/int) by some compilation #define
or
2. Get the tm module 'enable_uac_fr' config parameter value inside `uac_req_send(void)` function and decide adding TMCB_ON_FAILURE if it is enabled or not.
or
3. Adapt the test function with an parameter of "0"

**Comment by miconda** [comment]
Wouldn't it be better to try to leverage somehow `$uac_req(evroute)`? Now it has to be set to `1` to get the event route executed. The field can be turned into a flags meaning, so if it is set to 2, then adds the execution as per this PR:

  * https://www.kamailio.org/wiki/cookbooks/5.5.x/pseudovariables#uac_req_key

By that, the prototype of the function does not change.

**Comment by smititelu** [comment]
Good idea! Thank you! I will update the PR soon.

**Comment by miconda** [comment]
Thanks!

**Pull request merged**
