### PR TITLE
sipcapture: remove workaround of correlation_id

### PR DESCRIPTION
**Pull request by giavac**
- Compatible with Asterisk >= 10

(cherry picked from commit 6cb0bec7d2491ed3365dc237fc1d8608af246c3a)

### CODE REVIEW

**Comment by adubovikov** [comment]
@miconda can you please do me the ?

**Comment by miconda** [comment]
@adubovikov - ok. You should be able to do the merge as well, isn't working for you (just to be sure you have all the permissions needed)? Or you just wanted my review that is fine to backport?

**Comment by giavac** [comment]
Thanks.

**Comment by adubovikov** [comment]
no, it was just for review. I always careful for cherry picking to the stable release ;-)
next time I will do by self!

**Pull request merged**
