### PR TITLE
dmq: let server_address & notification_address can use the same IP and port

### PR DESCRIPTION
**Pull request by zhangst**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
issue : https://github.com/kamailio/kamailio/issues/1109

### CODE REVIEW

**Comment by charlesrchance** [comment]
Hi - I still don't understand why this is necessary. What combination of server/notification address values causes issues for you?

**Comment by zhangst** [comment]
For example, I have four kamailio instance for register, one kamailio instance recv REGISTER, it copy to other three kamailio instance by dmq_usrloc.
In this scene, I set notification_address to domain sip:ka.ns.com:5060 which resolve to all four kamailio instance(which recv REGISTER).In this way, **I do not need to build a separate kamailio cluster only for notification server.**

```
modparam("dmq", "server_address", "sip:10.6.1.200:5260")
modparam("dmq", "notification_address", "sip:ka.ns.com:5260")
# This configuration, ka.ns.com only resolve to 10.6.1.200, kamailio can not normal start.
it report : 
dmq [notification_peer.c:345]: add_server_and_notify(): error adding notification node
dmq [dmq.c:299]: child_init(): cannot retrieve initial nodelist from sip:ka.ns.com:5260
```

**Comment by charlesrchance** [comment]
‘’’
modparam("dmq", "server_address", "sip:10.6.1.200:5260")
modparam("dmq", "notification_address", "sip:ka.ns.com:5260")
‘’’

^^ this will work just fine as it is, provided ka.ns.com resolves to all four nodes - or at least one other than itself.

Why, in your second example, does it only resolve to itself?

**Comment by zhangst** [comment]
yes，domain only reolve to itself.

**Comment by charlesrchance** [comment]
Do you have the multi_notify modparam set?

In the special case you mention, why set the notification address at all if it’s pointing to itself and you already know this will not be added as a peer?

**Comment by zhangst** [comment]
already set multi_notify modparam.

In four nodes case, ka.ns.com is not resolve to four ip at once.
ka.ns.com resolve to ip1 in first visit, and resolve to ip2 in second visit, and so on.
This is DNS action. not kamailio.
Maybe it is not a general usage, DNS should resolve to all four ip.

I realized my problem,  DNS should resolve to all four ip. 
Thanks.

**Pull request closed without merging**
