### PR TITLE
permissions: fix crash during RPC trusted reload

### PR DESCRIPTION
**Pull request by linuxmaniac**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #2909

### CODE REVIEW

**Comment by miconda** [comment]
I am not using permissions with trusted table, but it looks like now it's going to be no parallel use of the in-memory table. It's safe against reloads done quickly one after the other, but all kamailio processes that do permissions check wait one after the other always.

If one ensures the reloads are not triggered quickly one after the other, then the patch is slowing down, specially if the number of records is high. An option would be to add a mod param to enable this lock or not at startup.

Anyhow, as I said, I am not using this feature, so I can't evaluate the impact. Maybe @juha-h can comment if he uses this feature, or some other devs.

**Comment by linuxmaniac** [comment]
Yes, you're right. I didn't realize I was destroying parallel use of the hash. I was focusing on be sure the memory was not going to go away in the middle of a search. I need to find a better solution.

**Comment by miconda** [comment]
Iirc, with other rpc commands related to db reload it was introduced a "safety delay" for them, so they cannot be done very often.

**Comment by linuxmaniac** [comment]
Yes, I implemented the delta parameter [0] but that doesn't help if you're in the middle of a search

https://github.com/kamailio/kamailio/commit/01fa7503433f4e23dea156e1034a87bbb49a4a1d

**Comment by miconda** [comment]
Some modules keep also the old data till next reload (dispatcher ?!?), I thought is the case also here.

Then the solution could be to have a list of old hash tables that are destroyed on timer, after some configurable delay. Practically, instead of destroying immediately, add it to the list with a timestamp, and destroy after N secs with a timer callback.

**Comment by linuxmaniac** [comment]
Yes, that would be a nice approach. I'm going to implement it like that.

Thank you!

**Comment by miconda** [comment]
I guess there is no possibility to perform another reload as long as the old hash table is not freed on timer. If yes, then fine for me, the new modparm has to be documented, if not done.

**Comment by linuxmaniac** [comment]
> I guess there is no possibility to perform another reload as long as the old hash table is not freed on timer. If yes, then fine for me

[here](https://github.com/kamailio/kamailio/pull/2910/commits/7ce815c2612d6277b55aabf6519c70a4ecec6502#diff-ce4f68a3bf731efbaaa1d243de3f81a8c6a068fb2c8693195558dbda1b4bb389R228-R230)  I check that no reload was done before last tick.

if a reload is called before the timer interval, nothing changed. [reload_trusted_table](https://github.com/kamailio/kamailio/blob/7ce815c2612d6277b55aabf6519c70a4ecec6502/src/modules/permissions/trusted.c#L94-L100) It was already removing the old previous values before loading new values there before the switch.


> the new modparm has to be documented, if not done.

To be added if we agree in the implementation

**Comment by miconda** [comment]
Docs can be added and then merged.

**Pull request merged**
