### PR TITLE
topos: Add db version check

### PR DESCRIPTION
**Pull request by xkaraman**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Add a database version check and fail gracefully if it does not match.

### CODE REVIEW

**Comment by miconda** [comment]
If I haven't overlooked something, it seems to be missing closing db connection on mod_init, which results in inheriting it on children after fork and conflicts during runtime.

Maybe it is better to move it in child_init with rank 1, we discussed a bit about that during K Devs meeting.

Furthermore, I recommend to add a module parameter for being able to disable this check, some other modules do it:

  - https://www.kamailio.org/docs/modules/stable/modules/auth_db.html#auth_db.p.version_table
  
It was working fine without it for many releases and it should keep a way for same behaviour like in the past. Disabling version table check is useful during upgrades, when new database table structure includes the old one, in case of needing to revert the upgrade for a while, running the old version is fine.

**Comment by xkaraman** [comment]
Updated to close the db connection and added a module parameter for being able to disable the check.

**Comment by miconda** [comment]
You also need to add documentation for the new module parameter in the xml file from doc/ subfolder.

To avoid globals conflict, add `_tps_` prefix to the new global variable in the C code, to be similar to the other variables that are made modparms by topos.

**Comment by miconda** [comment]
Thanks, merging!

**Pull request merged**
