### PR TITLE
.github/workflows: added GitHub action script to build Alpine docker

### PR DESCRIPTION
**Pull request by sergey-safarov**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Created GitHub action script to allow building Alpine docker image.

### CODE REVIEW

**Comment by linuxmaniac** [comment]
@sergey-safarov and this is the [script](https://gist.github.com/linuxmaniac/2d513333b6b0ebf3faa4b0dadb38afa1) I used to migrate from Docker Hub

**Comment by linuxmaniac** [comment]
> Maybe you can migrate images?

I can, process already started. It will take some time.

**Comment by linuxmaniac** [comment]
@sergey-safarov please take a look over https://github.com/kamailio/kamailio-ci/pkgs/container/kamailio-ci and check that everything is fine

**Comment by sergey-safarov** [comment]
The already uploaded images look good to me.
I will wait until finished uploading and recheck.

**Comment by sergey-safarov** [comment]
all images upload.
For me all is correct.
I will update PR to push into the GitHub repo.

**Comment by linuxmaniac** [comment]
Can you please re-open this PR when you have something working? Is a bit annoying receiving so much email/notifications

**Pull request closed without merging**
