### PR TITLE
textops: fix append_hf function

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [X] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

append after last eader occurance

### CODE REVIEW

**Comment by miconda** [comment]
Thanks!

**Comment by henningw** [comment]
Probably the documentation should also be fixed?

https://kamailio.org/docs/modules/devel/modules/textops.html#textops.f.append_hf

"4.24.  append_hf(txt[, hdr])

Appends 'txt' as header after first header field or after last 'hdr' header field. "

**Comment by miconda** [comment]
Pushed some notes to the docs of basic header operations functions, feel free to add more or adjust.

**Comment by henningw** [comment]
Thank you Daniel

**Pull request merged**
