### PR TITLE
dialog: Remove deprecated dlg_flag

### PR DESCRIPTION
**Pull request by xkaraman**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #2593 

#### Description

This PR removes the `dlg_flag` from the dialog module and recommends `dlg_manage()` instead in the docs.

### CODE REVIEW

**Comment by miconda** [comment]
Fine for me over all, I hope it does not impact other modules depending on dialog.

**Comment by henningw** [comment]
Thanks for the PR. There are several modules that seems to related to the dlg_flag:

* nat_traversal
* call_control
* cnxx
* acc
* qos
* sst
* pua_dialoginfo
* mediaproxy
* different IMS modules (ims_dialog will be not changed in this PR)

Some of the modules are using it only to check if there is a dialog module available. So this is probably not critical. But it needs to be investigated and probably changed. Some of the modules are just documenting it.

**Comment by xkaraman** [comment]
Only mention in the docs and no source code implications:
1. acc
2. qos
3. pua_dialoginfo
4. sst

The rest should require a separate PR probably

**Comment by xkaraman** [comment]
For the rest of modules: 
1. call_control
2. cnxcc
3. mediaproxy
4. nat_traversal

The dialog flag reading and checking was removed for the above modules.

Also, the setting of the message internal flag was removed and updated docs that they MUST call `dlg_manage()` if they want the the functionality of tracking the call.

**Comment by xkaraman** [comment]
If there aren't any more reviews, this can probably be merged!

**Comment by henningw** [comment]
Thanks, it was merged. Please send a short e-mail to sr-users list that the dialog flag was removed and list the affected modules.

**Pull request merged**
