### PR TITLE
cplc and pua_dialoginfo enhancement

### PR DESCRIPTION
**Pull request by fgaisnon**
#### Pre-Submission Checklist

- [x ] Commit message has the format required by CONTRIBUTING guide
- [x ] Commits are split per component (core, individual modules, libs, utils, ...)
- [x ] Each component has a single commit (if not, squash them into one commit)
- [x ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x ] Small bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

cplc: add a configuration route before redirected call (key: redirect_route)
same behaviour as proxy_route
cplc: deactivate 3XX responses handling (key: ignore3xx)
cplc: time based cpl did not work if several are set
cplc: add return result to kamcmd commands
cplc: documentation update (new keys, new module name, proxy_route modification)

pua_dialoginfo: disable publish notifications for subsequent requests (key: publish_dialog_req_within)
Generally all these PUBLISH generated are not usefull.

pua_dialoginfo: add new key to really deactivate caller or callee notification when the deactivated party was supervised (key: caller_entity_when_publish_disabled key: callee_entity_when_publish_disabled)
If Alice calls Bob with Alice and Bob already supervised by watchers and disable_caller_publish_flag set, PUBLISH generated for Bob will generate NOTIFY for Alice's watchers and Bob's watchers instead of just Bob's watchers.
Note that dlginfo_cell structure is updated because flag set for disabling party (disable_caller_publish_flag or disable_callee_publish_flag ) are not always present in subsequent request received by pua_dialoginfo module. So flag set on initial request are stored and used during the dialog.

### CODE REVIEW

**Comment by miconda** [comment]
The commit for cplc looks ok, the one for pua_dialoginfo is rather big and requires more time to review and understand what it does. But there is no way to do a partial merge via github (afaik).

Although not a must, it is recommended to make distinct pull requests in such cases, because the two commits are not related one to each other, if you want independent review and merge faster for some of the commits.

**Comment by fgaisnon** [comment]
Ok sorry, I note it for future commits.
However is this validation may be done before 5.5 release?

**Comment by miconda** [comment]
Existing pull requests can be merged after freezing development for 5.5 as well, should make it in 5.5.x anyhow.

**Comment by miconda** [comment]
Thanks, merging.

**Pull request merged**
