### PR TITLE
pkg/gentoo: Added ebuild files for versions 5.1.10, 5.2.6, 5.3.2 and master

### PR DESCRIPTION
**Pull request by fsantulli**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

pkg/gentoo: Added ebuild files for versions 5.1.10, 5.2.6, 5.3.2 and master

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the pull request. So it seems that there is no version inside the ebuild files. That means for minor releases they usually could just be copied or moved. 
I will merge them manually in the appropriate branches.
There seems one small error in the license definition of the packages. You specify GPL-2, but I think it should be GPL-2+ (for the "or later" version, if I remember correctly).

**Comment by fsantulli** [comment]
> Thanks for the pull request. So it seems that there is no version inside the ebuild files. That means for minor releases they usually could just be copied or moved.
> I will merge them manually in the appropriate branches.
> There seems one small error in the license definition of the packages. You specify GPL-2, but I think it should be GPL-2+ (for the "or later" version, if I remember correctly).

Hi Henning,

GPL-2 is the license used by Gentoo Ebuild files. 

For the package license we can add the proper row

**LICENSE="GPL-2+"**

into the ebuilds theirselves to comply the Kamailio license if correct.

Kind regards.

Federico Santulli

**Comment by fsantulli** [comment]
Ebuild files can be renamede to satisfy the "latest minor" but in case of dependency requirements they wont compile.

**Comment by henningw** [comment]
Thanks - yes I was referring to the Kamailio license. Ok, I can change this before the commit.

**Comment by miconda** [comment]
The 5.1 branch is end of official maintenance, not sure if it makes sense to add more to it, unless people want to have gentoo build for it, but so far was not required explicitely on mailing lists.

Then if the version is required in the file name, and we have to add/remove/rename files with each release, then better have 5.4.0 for master branch, rather than 9999.

**Comment by fsantulli** [comment]
Hi Daniel,

About the 5.1 release as i found a package i made an ebuild for it.

Btw, in the gentoo packaging system the 9999 version is used for git pull releases. Using static version 5.4.0 will require an archive to download and unpack.

I hope to be clear.

Kind regards

Federico Santulli

**Comment by henningw** [comment]
I've added the git master, 5.3 and 5.2 packages and files. For 5.1 I did not added it, as pointed out, this release is already EOL.

**Pull request closed without merging**
