### PR TITLE
make get_hdr_by_name/next_sibling_hdr_by_name case insensitive

### PR DESCRIPTION
**Pull request by nevian427**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
core: make get_hdr_by_name/next_sibling_hdr_by_name case insensitive

- Credits goes to Alexandr Dubovikov

### CODE REVIEW

**Comment by miconda** [comment]
The commit message doesn't have the format required by the contributing guide, although you have checked that box. Amend the commit message accordingly:

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format

**Comment by nevian427** [comment]
Sorry what's wrong? Looks like formatted right. Or should I elaborate in desc why this fix is required?

**Comment by miconda** [comment]
See the commit message as it appears in the patch:

  * https://github.com/kamailio/kamailio/commit/b84d4a1f09b6310522ac83546a7a34b2c52f0ecf.patch

What you had as Description in PR comment is not in the commit message.

**Comment by nevian427** [comment]
I see thanks. I thought Description was commit message :(
So I must make new commit from scratch, right?

**Comment by miconda** [comment]
The commit message is the one you give when  doing "git commit ...".

The patch is small, so probably is faster to use the diff (https://github.com/kamailio/kamailio/commit/b84d4a1f09b6310522ac83546a7a34b2c52f0ecf.diff), make a fresh clone of kamailio repo and do the commit again, with a new PR.

Otherwise, you can search on the web how to amend a commit message, but can take some time to sort out when the commit was pushed remote.

**Comment by miconda** [comment]
Pushed patch with a manual commit.

**Pull request closed without merging**
