### PR TITLE
etc: kamailio.cfg Make the FLAGS declaration slightly clearer

### PR DESCRIPTION
**Pull request by webstean**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by webstean** [comment]
Make the FLAGS declaration slightly clearer

**Comment by miconda** [comment]
Thanks, however the first line of commit message has to be prefixed with the component name, like per contributing guide:

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-rules

You can see examples with `git log etc/` executed in kamailio source code folder.

**Comment by webstean** [comment]
update commit statement

**Comment by miconda** [comment]
The guidelines are for commit message, not for pull request title and comments. I made the proposed change manually myself  this time, see commit 59b4a820aba7487552e98c8b082e7abd56fa8e81 .

**Pull request closed without merging**
