### PR TITLE
core: log parser error messages with debug level 

### PR DESCRIPTION
**Pull request by nferreyra**
#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
* Make parser error logs as debug avoiding excessive logging for negative HTTP replies.
The issue was discussed here: https://lists.kamailio.org/pipermail/sr-users/2020-February/108232.html

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the pull request.  Well, these are the core parsing functions, that are used for all kind of messages. I don't like to just change it to DBG, because it suppress all kind of parsing errors then. 
You pull request contains also three unrelated merge commits.
I think there should be another solution possible.

**Comment by miconda** [comment]
Those message can be aready skipped by setting `core_log` global parameter.

  * https://www.kamailio.org/wiki/cookbooks/5.3.x/core#corelog

No need to force them to a specific log level.

As for topos, I pushed a patch to catch http replies. Try with:

  *  https://github.com/kamailio/kamailio/commit/fad795648f8cbf12cc099dea18092ff7beee9c75

**Comment by nferreyra** [comment]
@miconda thank you for the corelog reference, it was there all the time and I didn't rtfm.
You topos patch is working fine. For the sake of consistency, shouldn't a similar patch be applied to topoh?
Thank you.

**Comment by miconda** [comment]
topoh got a similar patch, if you can test that module as well and report the results, it would be great.

**Pull request closed without merging**
