### PR TITLE
Added compression for rtpengine

### PR DESCRIPTION
**Pull request by pchero**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

rtpengine: added the message compression

- Added option for bencode message compression when the Kamailio sendint the message to RTPEngine.
- When the message size is over the configured compress_size, it compresses the message.
- For the incoming message, checks the compressed it or not using the first byte.
- If the message has compressed, uncompressing the message.
- Default is 0 - no compression in any case.

### CODE REVIEW

**Comment by miconda** [comment]
Can you provide more details about the scope of this patch? Also, you have ti add documentation to the xml file in the doc/ subfolder for the new modparam related to compress size.

**Comment by pchero** [comment]
Hi @miconda , thank you for your review.
I've fixed my MR as you commented. Could you please take a look again?

Thank you.

**Comment by pchero** [comment]
Hi @miconda , 

My new commit makes fails, but I didn't change any codes from the previous one.
Could I get some help why this makes fail?

Thank you.

**Comment by miconda** [comment]
The failure is about LGTM not being able to do the analyzis, so not related to code, but likely it was an issue on LGTM service.

You haven't commented on my question about the scope of this PR, to save bandwidth between kamailio and rtpengine? What version of rtpengine is required?

@rfuchs - any comments from you on this PR?

**Comment by pchero** [comment]
Sorry, I missed that part.

This patch is affected to the Kamailio's RTPEngine module only, but also need to be fixed from the RTPEngine's side.
https://github.com/sipwise/rtpengine/pull/1052

**Comment by pchero** [comment]
Hi @miconda ,

Thank you for your kind review. But I don't think this change is valid and useful anymore, at this moment.
So, I'm closing this MR now.

Thank you for all messages.

Kind regards,
Sungtae

**Pull request closed without merging**
