### PR TITLE
dialog: update event route statistics

### PR DESCRIPTION
**Pull request by smititelu**
If dialog was deleted while running the event route, update statistics
for early and active dialogs.

#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [X] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Please let me know if I can backport it to 5.3

### CODE REVIEW

**Comment by henningw** [comment]
Hi Stefan, thanks for the pull request. Can you elaborate a bit on the failure condition that this patch solves? Shouldn't be the dialog statistics updated by the "normal" code e.g. in dlg_handlers.c? Or are you refering to conditions when a dialog is deleted _by_ the event route?

**Comment by smititelu** [comment]
Indeed, this needs a bit more explanation.

Check out this function flow:
```
dlg_onreply() -> dlg_run_event_route() -> dlg_lookup() -> if (dlg0 == 0)

```
When dlg_run_event_route() fails (returns -1) then dlg_onreply() just returns.

Now, in the same dlg_onreply() at line 571, the statistics are updated in case of new_state==DLG_STATE_DELETED. However, because of the above, this code is not called if dlg_run_event_route() fails.

Most probably I should update this pull request to increment also the failed dialogs, as done in dlg_onreply() at line 585.

Let me know if this clarifies your questions.

**Comment by smititelu** [comment]
I've updated the "if" conditions for updating statistics in case of dlg_lookup() failure.

**Comment by henningw** [comment]
Ok, thanks for the clarification. You can merge and also backport, its a bugfix.

**Comment by smititelu** [comment]
Cool. Thanks for review.

**Pull request merged**
