### PR TITLE
dialog: run event_route[dialog:end] in case of dialog termination by …

### PR DESCRIPTION
**Pull request by krieger-od**
…interface commands

### CODE REVIEW

**Comment by miconda** [comment]
Thanks for the patch.

At quick look, it seems that the event route will be called twice in case of a dialog lifetime timeout. At line 1408 in dlg_handlers.c, the event route code is executed again after dlg_bye_all() and dlg_bye_all() executes inside the event route code. Might be an option to remove it from that place.

**Comment by krieger-od** [comment]
Thanks for this deep review. Amended that commit, it should be in this pull request now (9ccc3f510ce2d97dbe1efb690ef1d4e8f18885d5).

What about that double dlg_unref() at dlg_handlers.c near 1408 after dlg_bye_all() in case of non-zero return? Is it ok?

**Comment by miconda** [comment]
The unrefs should be ok. One is done in case bye was not sent out, to destroy dialog faster, otherwise it will wait for the reply of the bye to unref and destroy dialog.

**Comment by krieger-od** [comment]
> The unrefs should be ok. One is done in case bye was not sent out, to destroy dialog faster, otherwise it will wait for the reply of the bye to unref and destroy dialog.

I meant that the new code is this:
```
 			if(dlg_bye_all(dlg, NULL)<0)
 				dlg_unref(dlg, 1);
 			dlg_unref(dlg, 1);
```

**Comment by miconda** [comment]
Yes, that's the code.

**Comment by vinodmn** [comment]
Hi i am using kamailio 4.4.3 but still I am facing the same issue, 
**event_route[dialog:end] is not exec'd on dialog terminated by dlg.end_dlg,** ,so the CDR's are not generating properly.

**Pull request merged**
