### PR TITLE
auth: Add option to use SHA-256 instead of MD5 in digest authentication

### PR DESCRIPTION
**Pull request by AndreasHuber-CH**
This is an alternative solution to pull request: https://github.com/kamailio/kamailio/pull/627

### CODE REVIEW

**Comment by miconda** [comment]
Thanks for the contribution!

Looking at the sequence of operations, only the patch 	4a076a0 needs to be reviewed and merged, right?

**Comment by AndreasHuber-CH** [comment]
Hi. Yes, only patch 4a076a0 is relevant.

**Comment by AndreasHuber-CH** [comment]
Hi. Did anyone look at the proposed feature ?
And do you have an idea if and when you might accept this pull request ?

Regards, 
Andreas

**Comment by miconda** [comment]
These days many of us are at Kamailio World Conference in Berlin, therefore some low activity around the online resources of the project.

This looks like something I will have to review, but being one of the organizers these days I don't have much time to even breed. However, I will try to do it soon.

**Comment by AndreasHuber-CH** [comment]
Ok, no problem.

**Comment by miconda** [comment]
Thanks, the patch was pushed manually on your behalf with commit e7faf1e .

**Pull request closed without merging**
