### PR TITLE
tm: deep cloning of the request for fake environment

### PR DESCRIPTION
**Pull request by linuxmaniac**

### CODE REVIEW

**Comment by grumvalski** [comment]
seems ok to me.

**Comment by miconda** [comment]
@linuxmaniac, @grumvalski  - wondering if you had any time running some tests with the patch, just to have a feeling if you observed any side effect.

I didn't get to review yet, planning to do it during the next days.

**Comment by linuxmaniac** [comment]
I did test with our scenarios, I didn't detect any side effect

**Comment by miconda** [comment]
Can be merged and backported to 5.0, eventually later to 4.4.

Probably the deep cloning from acc makes no longer sense, I will check that myself, for now should be harmless.

**Comment by grumvalski** [comment]
Sorry for the late feedback. I did try it with some of our suspend scenarios and I haven't noticed side effects. No load though.

**Pull request merged**
