### PR TITLE
ndb_redis: add pipeline suppport for REDIS Module

### PR DESCRIPTION
**Pull request by claudiupb**
Hello, 

I have added pipeline support to the ndb_redis_module. Two functions are added: 
-redis_pipe_cmd which appends a command to be pipelined(syntax is identical with redis_cmd)
-redis_execute which sends one message with all existing pipelined commands and handles the replies

To send multiple commands in a single message, the user must call redis_pipe_cmd for each command, and then redis_execute to send all messages. 

This enhancement is not compatible with the recently added REDIS cluster support, so if that is enabled the new functions don't do anything but log an error. 

Thanks,
Claudiu Boriga

### CODE REVIEW

**Comment by miconda** [comment]
Pinging Carsten (@ngvoice) -- is it needed to wait for fixing the changes done by using shm memory or this PR can be merged?

**Comment by miconda** [comment]
@claudiupb - can you resolve the conflicts so this PR can be merged? The module was in a broken state at the time you did the PR, which needed to be fixed, sorry for the extra work.

**Comment by claudiupb** [comment]
Ok, I will resolve the conflicts

**Comment by claudiupb** [comment]
I resolved the conflicts in the PR.

**Comment by miconda** [comment]
@claudiupb - the travis-ci is reporting compilation errors with the patches, see the details the post above.

**Comment by claudiupb** [comment]
Hello, there was a problem because _redisc_srv_list type was modified.

**Comment by miconda** [comment]
Thanks, I merged it manually to get rid of the extra commit messages that didn't follow the required format -- commit ff8cfa62c41704b72301966b0919ea95b001dac7 .

**Pull request closed without merging**
