### PR TITLE
 sqlops: sqlops_do_query - Make result parameter optional in C API

### PR DESCRIPTION
**Pull request by que273**
Make the result string parameter optional in the sqlops_do_query C API function

### CODE REVIEW

**Comment by henningw** [comment]
Hello Hugh, thank you for the pull request. Wouldn't make sense to move the null check to the beginning of the function? Otherwise sql_get_result would call with a null before your check.

**Comment by henningw** [comment]
Forget my previous comment - I think we should add a null check to sql_do_query as well.

**Comment by que273** [comment]
sql_get_result does not currently check the 'name' parameter and will crash in core_case_hash if this is NULL. This is also true for sql_get_connection and sql_init_con. However, these three functions are only called from within the sqlops module.
I will add a check to the C-API/KEMI wrapper functions that call them (sqlops_do_query, sqlops_get_value, sqlops_is_null, etc.)? Is it needed inside sql_get_result as well?

**Comment by henningw** [comment]
Merged and closed.

**Pull request merged**
