### PR TITLE
fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by miconda** [comment]
Thanks!
Did you get compilation errors with some specific version of libssl? If yes, which one, because I haven't encountered any problems so far.

The commit message first line is not formatted as per contributing guide:

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-rules

The PR can be merged manually to fix it, just have it in mind for future contributions so merging can be done from the github portal.

**Comment by neheb** [comment]
OpenWrt's OpenSSL package has deprecated APIs configurable.

**Comment by neheb** [comment]
This can be simulated by passing -DOPENSSL_API_COMPAT=0x10100000L and -Werror=implicit-function-declaration .

**Comment by miconda** [comment]
OK, I will push it to master branch and see if we encounter any issues on the systems we build packages for.

**Comment by miconda** [comment]
Pushed manually with proper format for commit message.

**Pull request closed without merging**
