### PR TITLE
Db ipv6-address parsing in config file

### PR DESCRIPTION
**Pull request by vasilevalex**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #2060 

#### Description
Added parsing of IPv6 address in config file for DB URL.

### CODE REVIEW

**Comment by henningw** [comment]
Hello, thank you for the pull request. This is indeed a good addition. 
I had a look to the code - I think it is good to combine this with a small refactoring in the modules as well.

As git master branch is currently frozen, I will put this on hold until 5.3 is released in a few weeks.

**Comment by miconda** [comment]
Not supporting IPv6 is a bug, Kamailio is supposed to work on IPv6 for its common use cases. Not sure why support in db_url was not discovered so far missing IPv6, we did a review couple of years ago, but we focused on SIP routing, this was somehow overlooked.

If the review of the code is ok, then this PR should be merged, unless many devs have something agains.

**Comment by vasilevalex** [comment]
There is some code duplication, and I don't like it. But I don't know, may be it make sense, so I left it as it was.

**Comment by henningw** [comment]
Yes, we should support IPv6. But there are probably still a few places left like this. In the end most people will use DNS for internal names.
I will merge it and do the refactoring then later.

**Pull request merged**
