### PR TITLE
ims_registrar_scscf: fix aor generation in lookup()

### PR DESCRIPTION
**Pull request by alexyosifov**
- Generate AoR in lookup() from parsed uri user and
  host. Skipping all user's and host's parameters.

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by henningw** [comment]
@ngvoice - any comments from your side regarding this change?

**Comment by alexyosifov** [comment]
Hi all,
Could you take a look at the pull request?

**Comment by henningw** [comment]
There seems to be no objections from ngvoice or other developers, fine for me to merge it.
Should it be backported to stable branches?

**Comment by miconda** [comment]
Thanks!

@alexyosifov is not developer, so I am merging it. Should be backported, a note can be made here in a comment or also a PR.

**Pull request merged**
