### PR TITLE
presence - match sip uris using alternative function

### PR DESCRIPTION
**Pull request by lazedo**
added param sip_uri_match
0 - case sensitive (default)
1 - case insensitive

can be extended to a more compliant version, (sensitive user, insensitive domain). 
the parameter sets the function to call to match uris.

### CODE REVIEW

**Comment by oej** [comment]
Are we still missing docs here?

Note that the param in registrar has another name. Since this is not about the full SIP uri- i hope we always are case insensitive for domains - maybe a better name would be sip_username_match

**Comment by kamailio-sync** [comment]
yes, i know the docs are missing.

when is something other then a fix, i will gladly add the docs if the request is accepted.

"i hope we always are case insensitive for domains"

this implementation acts on the full sip uri. it is open to add a 3rd option that will take the full uri and matches sensitive on the username and insensitive on the domain.

before this it acts on the full sip uri as case sensitive, i give it the alternative and left it open enough (i think) to implement full RFC compliance.


________________________________

**Comment by oej** [comment]
If the module are comparing domains with case sensitivity today, that's a bug that needs to be fixed.

**Comment by miconda** [comment]
There are helper C functions for comparing the URI, used by:

  * http://kamailio.org/docs/modules/devel/modules/siputils.html#siputils.f.cmp_uri

Not sure how this strict uri matching can be made to work with db only mode... but I guess that is a compromise.

**Comment by juha-h** [comment]
lazedo writes:

> added param sip_uri_match
> 0 - case sensitive (default)
> 1 - case insensitive

should it rather be called sip_uri_user_match?

i still don't feel comfortable in starting to bloat kamailio with
non-standard behavior.  why don't you canonize uri user in config
script?

-- juha

**Comment by juha-h** [comment]
Olle E. Johansson writes:

> If the module are comparing domains with case sensitivity today,
> that's a bug that needs to be fixed.

exactly. i also pointed this out earlier.  if implemented, the new
function must operate on uri user only, but i would not prefer to add
this functionality at all as i mentioned in previous message.

-- juha

**Comment by lazedo** [comment]
Olle,

it acts on the sip uri not the user part of the sip uri.

**Comment by juha-h** [comment]
lazedo writes:

> it acts on the sip uri not the user part of the sip uri.

and that exactly is the problem as we have tried to tell.

-- juha

**Comment by miconda** [comment]
@juha-h - because the comparison is done on different URIs (sender, target, contact), I am not sure that would be easy to canonise in config.

Looking at the patch I think it is in the right direction to get this sorted out according to RFC but also for other cases if needed.

Now is case sensitive, perhaps the default should be made to use the internal uri comparison functions.

The patch makes it easy to decide on what kind of comparison to do. There will be no side effect on performances if we go for uri comparison function or allow other options via mod param.

@lazedo - can you make the patch for the docs of the module to reflect the new parameter? I am considering to merge at some point, followed by adding the option for RFC uri comparison, eventually making that default option.

**Comment by lazedo** [comment]
@miconda sure. one question, shuld we also <abstract the core_hash used in the module to work the same way as the match function ? abstracting to core_hash / core_case_hash ?

**Comment by miconda** [comment]
What do you mean by abstracting the core_hash / core_case_hash ? To have a function inside presence module as a wrapper?

**Comment by lazedo** [comment]
yes, working the same as the uri comparison, using function pointer.

**Comment by miconda** [comment]
I think here we can go with case insensitive hashing, the function is not slower and covers properly all cases. Adding a new parameter will make it more complex, exposing something that is pure technical and related only to the internals of the module.

**Comment by lazedo** [comment]
ok, i wasn't thinking in adding a new param and use the previous one ( sip_uri_match ) to either call core_hash or core_case_hash.
are you proposing to change the core_hash with core_case_hash independently from sip_uri_match param?

**Comment by miconda** [comment]
Yes, use core_case_hash() -- I think it is the best option: not adding any overhead and avoids extra config complexity.

**Comment by lazedo** [comment]
closing here because of rebase that didn't go well.

https://github.com/kamailio/kamailio/pull/116

**Pull request closed without merging**
