### PR TITLE
ERLANG module

### PR DESCRIPTION
**Pull request by seudin**
This module provides interact with Erlang node. The module allows sending,
receiving Erlang messages and RPC calls between each other.

### CODE REVIEW

**Comment by lemenkov** [comment]
Subscribing on this :-)

**Comment by miconda** [comment]
Looks ok at the first sight. It will be merged to catch development freeze for v4.3 and a new modules group will be created for it because it has dependency for building.

You will get write access to kamailio repository so you can maintain it here in the future.

During the testing period we can refine it, if needed.

**Comment by miconda** [comment]
Merged. Thank you for contributing the module!

**Comment by seudin** [comment]
Thank you too.

**Pull request merged**
