### PR TITLE
RPC fix for arrays on permissions module

### PR DESCRIPTION
**Pull request by kelchy**
subnet dump and address dump

### CODE REVIEW

**Comment by miconda** [comment]
Can you try by setting RET_ARRAY flag to RPC exports at:

  * https://github.com/kamailio/kamailio/blob/master/modules/permissions/permissions.c#L1015

Like at:

  * https://github.com/kamailio/kamailio/blob/master/modules/corex/corex_rpc.c#L227

If works, it should be the desired implementation in such case.

Also, for the future, first line of the commit must be prefixed with the module name, see:

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format

**Comment by kelchy** [comment]
Kelvin Chua

On Fri, Aug 19, 2016 at 2:24 AM, Daniel-Constantin Mierla <
notifications@github.com> wrote:

> Can you try by setting RET_ARRAY flag to RPC exports at:
>
>    - https://github.com/kamailio/kamailio/blob/master/modules/
>    permissions/permissions.c#L1015
>    <https://github.com/kamailio/kamailio/blob/master/modules/permissions/permissions.c#L1015>
>
>
tried it, it changes the root but still returns 1 array element


>
>
> Like at:
>
>    - https://github.com/kamailio/kamailio/blob/master/modules/
>    corex/corex_rpc.c#L227
>
> If works, it should be the desired implementation in such case.
>
> Also, for the future, first line of the commit must be prefixed with the
> module name, see:
>
>    - https://github.com/kamailio/kamailio/blob/master/.github/
>    CONTRIBUTING.md#commit-message-format
>    <https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format>
>
>
got it

**Comment by miconda** [comment]
Have you closed because you plan a new pull request? Because I understand that my suggestion didn't fix it, or?

**Comment by kelchy** [comment]
closed, will create a new pull request

Kelvin Chua

**Pull request closed without merging**
