### PR TITLE
Modules: Evapi async_relay export to kemi

### PR DESCRIPTION
**Pull request by surendratiwari3**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
evapi_async_relay is exported to kemi interface

### CODE REVIEW

**Comment by surendratiwari3** [comment]
@miconda please review

**Comment by miconda** [comment]
@surendratiwari3 - looked a bit couple of days ago, but I wanted to analyze more and see if there is any code-reuse that can be done, usually exports to kamailio.cfg and kemi should share most of their code. Hope to sort it out these days.

**Comment by surendratiwari3** [comment]
@miconda Agree. I can also support to rewrite couple of modules for exporting to kemi with reusable code.

**Comment by miconda** [comment]
Merging it, given that fixup needs to be evaluated after suspending the transaction, it is not much that we can reuse now. In the near future, I will think of making a wrapper with two arguments for the parameters that can come either as fixup param or str*.

**Pull request merged**
