### PR TITLE
permissions: exported allow_trusted() to kemi

### PR DESCRIPTION
**Pull request by arsperger**
#### Type Of Change 
- [x] New feature (non-breaking change which adds new functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally

#### Description
permissions allow_trusted function is exported to kemi. function doesn't not accept any parameters.

### CODE REVIEW

**Comment by arsperger** [comment]
just fixed previous PR which was broken. Thank you.

**Comment by miconda** [comment]
The function does not accept parameters, but it is not the right way to export the one for the configuration file, because the signature differs and cannot be found for documentation, as well as can create problems in the future because of the need to cast.

I will export it and can be used as a reference for the future, if you want to contribute on exporting missing functions to kemi. Thanks!

**Comment by miconda** [comment]
For reference - the commit 843b22b implements it.

**Comment by arsperger** [comment]
Got it, thank you!

**Pull request closed without merging**
