### PR TITLE
tm: add mandatory Max-Forwards header to local ACK

### PR DESCRIPTION
**Pull request by juha-h**
#### Type Of Change
- [ x]  Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x ] PR should be backported to stable branches
- [ x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Add mandatory Max-Forwards header to local ACK

### CODE REVIEW

**Comment by miconda** [comment]
Remember that the git commit message first line has to be formatted as per contributing guidelines, it has to be prefixed with the component name:

  - https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format

The commit messages are used for generating the changelog for releases as well as making easier to figure out what was impacted by a commit. Having the commit message in the proper format makes it easier to merge as well directly from the git PR portal.

**Comment by linuxmaniac** [comment]
@juha-h is not a bug. The format checks each commit. I already told you how to properly do it.

Just create one commit with the proper commit message prefix squashing both previous commits in the branch.

**Comment by juha-h** [comment]
Victor Seva writes:

> Just create one commit with the proper commit message prefix squashing
> both previous commits in the branch.

Goes beyond me.  In baresip project, nothing like that needs to be
done.  If there is new commit to PR, all checks are automatically
re-run.

**Comment by juha-h** [comment]
juha-h writes:

> Goes beyond me.  In baresip project, nothing like that needs to be
> done.  If there is new commit to PR, all checks are automatically
> re-run.

... and red marks turn green without any extra action.

**Comment by linuxmaniac** [comment]
since it's a branch in kamailio repo I did it myself.

```
git rebase -i origin/master
```

squashed both commits and added the tm prefix

**Comment by linuxmaniac** [comment]
The idea behind it's that all commits are properly formatted.

**Comment by juha-h** [comment]
Is it OK to cherry-pick this to 5.8 branch?

**Comment by miconda** [comment]
Yes, it can be cherry-picked, it is about a mandatory header.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> Yes, it can be cherry-picked, it is about a mandatory header.

Done.

**Pull request merged**
