### PR TITLE
core: Zero terminate str copies made with (pkg|shm)_str_dup()

### PR DESCRIPTION
**Pull request by gaaf**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [x] Related to PR #2512

#### Description

As discussed in #2512, zero-terminating all copies is preferred as most str
usage is already with zero-terminated str.s.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks, it can be merged!

**Comment by miconda** [comment]
Merged myself. Somehow I thought @gaaf has commit access already, but I was mistaken.

**Comment by gaaf** [comment]
> Somehow I thought @gaaf has commit access already, but I was mistaken.

That was before the migration to github.

**Comment by henningw** [comment]
The docs in str.h should be probably changed as well (here is documented that str is not null-terminated). Also probably a good idea to review other invocation of this utilty functions in the modules, now there might be double null-termination done somewhere (might be harmless in most cases, though).

**Comment by gaaf** [comment]
Something like this: #2520 ?

I think that chances of double zero-termination are low when using these functions as it required 2 allocations in succession. Most uses of zero-terminated str will be open-coded to prevent that.

**Pull request merged**
