### PR TITLE
Adding CDR as JSON functionality 

### PR DESCRIPTION
**Pull request by lbalaceanu**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

These commits create a CDR addressed engine, similar to the one that acc module exports for acc message accounting. Such an engine made an extension module like acc_json possible. This CDR engine is then used in acc_json to write the functionality for logging CDRs in JSON format.

I have added functions to the API exported by acc module instead of creating another separate CDR API, as I thought this is cleaner.
I only implemented the acc_json logging to syslog (no message queue support yet).

### CODE REVIEW

**Comment by jchavanton** [comment]
Extending the acc API adding CDR support to acc_json seems like good options.

You did not think it was worth supporting queuing in mqueue, so that the same 2 outputs can be used syslog or mqueue ?

**Comment by lbalaceanu** [comment]
Hi @jchavanton,
I think the queuing is worth it. I will add this.
Thank you

**Comment by miconda** [comment]
@lbalaceanu @jchavanton - if the current PR is fine with the existing functionality, then it can be merged and mqueue support can be added as an enhancement later.

**Comment by jchavanton** [comment]
True, this is one way to proceed.

**Comment by lbalaceanu** [comment]
Hi,
Please allow one or two days before merging, so that I can also add the mqueue thing.
Thank you

**Comment by miconda** [comment]
No problem to wait even more days, if there is ongoing work in short term. I just wanted to avoid keeping here this PR for long time, while others can be interested in using/testing it, as the mqueue support is not a limitation of the current PR, but like an enhancement with new features.

**Comment by lbalaceanu** [comment]
Hi guys,

I modified the commits to contain the CDR writing to the message queue as well. Please let me know what you think.

**Comment by jchavanton** [comment]
Hi, nice I like it, supporting the same outputs for ACC and CDR is a big plus in terms of cohesion.
mqueue can be quite handy.

**Comment by lbalaceanu** [comment]
Should we then merge and close the pull request?

**Comment by miconda** [comment]
Go ahead and merge - somehow I didn't noticed that the mqueue support was added, but I see that @jchavanton was ok with the change.

**Comment by smititelu** [comment]
hi @miconda,

is it ok for this to be backported to 5.3 ? Or shall be considered available only starting from 5.4?

Thank you,
Stefan

**Comment by henningw** [comment]
@smititelu - this is a (larger) feature extension to the module. So it is not possible to backport it to a stable branch. But it will be as usual available in the next major release, 5.4.0.

**Comment by smititelu** [comment]
Thank you @henningw for clarification.

**Pull request merged**
