### PR TITLE
lrkproxy-fixed issue#2663

### PR DESCRIPTION
**Pull request by mojtabaesfandiari**
#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
@mojtabaesfandiari - you merged a lot of changes for what should have been a small patch.I reverted your pull request. Do not merge commits that affect other components (core, lib, modules) than your specific module.

What did you try to do?

**Comment by mojtabaesfandiari** [comment]
Sorry, Actually i have done my changed related to issue#2663 on my fork, then i just tried to merge my master branch with orgin master. Let me know what should i do in this situation?

**Comment by henningw** [comment]
I think the main problem is the confusing merge commit message. Have a look to this page:
https://sip-router.org/wiki/git/quick-start-guide


-> by default perform a rebase instead of a merge when pulling into the local master branch (highly recommended, it gets rid of a lot of confusing merge origin/master messages). It's equivalent to adding –rebase to git pull command line. (recommended)

git config branch.master.rebase true

**Comment by mojtabaesfandiari** [comment]
@henningw Thanks for helping.
@miconda Thank you

**Pull request merged**
