### PR TITLE
acc: use appropriate types for core values

### PR DESCRIPTION
**Pull request by mikomarrache**
Use appropriate types for core values:
  -> start and end as dates (instead of strings)
  -> duration as double (instead of string)

### CODE REVIEW

**Comment by linuxmaniac** [comment]
@mikomarrache just fix, amend  and push using force to your branch.

**Comment by mikomarrache** [comment]
@linuxmaniac I fixed the error in the branch.
What do you mean by amend and push using force?

**Comment by linuxmaniac** [comment]
I meant If you wanted to fix the original commit without having to create another one

**Comment by miconda** [comment]
You can also push a new patch to fix the issue in your branch and should appear in this pull request. Then it can be merge, but also the schema has to be changed and version increased for acc_cdrs table, via lib/srdb1/schema/acc_cdrs.xml. To generate the new db/sql creation scripts, run 'make dbschema'.

**Comment by mikomarrache** [comment]
I changed lib/srdb1/schema/acc_cdrs.xml as you asked and also included the fix.

I'm just a very beginner with Github, should I check out the branch, run the command and then commit?

Can you please provide me the right commands to checkout and commit?

Thanks
Mickael

**Comment by miconda** [comment]
Well, you did what I said by pushing to your branch, all the patches appeared in the pull request.

**Comment by miconda** [comment]
Thanks! The pull request will be merged.

**Comment by linuxmaniac** [comment]
And what about upgrades from 4.2 to 4.3??
Is there any way to migrate the old values?
What is the upgrade procedure here?

**Comment by miconda** [comment]
Maybe mysql can do conversion when running column change command:

```
ALTER TABLE acc_cdrs CHANGE COLUMN start_time ...
```

If not, we have to advise to backup the data, drop and recreate the table.

**Pull request merged**
