### PR TITLE
pv: Add support to $hfl $hflc for Diversion header

### PR DESCRIPTION
**Pull request by xkaraman**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
This PR adds support for $hfl(Diversion)[] and $hflc(Diversion).

This parse_diversion.c was inspired by [parse_pai_ppi.c](https://github.com/kamailio/kamailio/blob/master/src/core/parser/parse_ppi_pai.c). I am not sure if it's breaking the existing implementation and usage. 

Should probably also be documented in https://www.kamailio.org/wikidocs/cookbooks/devel/pseudovariables/#hflname-header-field-with-list-of-bodies. 

Any feedback and review is welcome.

### CODE REVIEW

**Comment by miconda** [comment]
Just adding the note that chaning the structure of parsed Diversion header may impact cloning to transaction and freeing of the sip message and transaction. Someone has to do a proper review for those parts before merging.

**Comment by henningw** [comment]
Xenofon did a review of the modules that uses diversion (diversion, sipcapture). The diversion module was tested with the PR. The sipcapture does only seems to store the header content in a string database field, so it should be fine. Regarding the SIP msg cloning, I reviewed the sip_msg_clone.c file. The diversion uses the same approach as the PPI and PAI headers, so it seems to be ok. There is no usage of the relevant diversion header types in tm. The main parser free function was adapted.

**Comment by miconda** [comment]
Thanks!

**Comment by miconda** [comment]
Patches applied manually to resolve conflicts.

**Comment by xkaraman** [comment]
Great! Thanks for merging! You can find the docs PR in https://github.com/kamailio/kamailio-wiki/pull/45.

**Pull request closed without merging**
