### PR TITLE
misc_radius doc : more information freeradius-client

### PR DESCRIPTION
**Pull request by ycaner06**
added information about how to active freeradius-client library

### CODE REVIEW

**Comment by oej** [comment]
Shall we really remove radiusclient-ng - is it a dead project?

Would it be possible to fix this in the makefile instead of suggesting a manual change?

**Comment by linuxmaniac** [comment]
fix the makefile?
we can switch the default to the newer one but we need a way to switch in order to support older distros

We already use this:
https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/deb/jessie/rules#L23-L24

**Comment by oej** [comment]
So why are the doc files talking about radiusclient-ng and not FreeRadius?

**Comment by oej** [comment]
http://kamailio.org/docs/modules/devel/modules/auth_radius.html

**Comment by miconda** [comment]
I am not familiar with the distribution of freeradius client library, I know that at some moment was only available in latest opensuse or fedora. I am fine to switch to freeradius client lib as long as the latest stable popular os distros have it.

**Comment by miconda** [comment]
Merging the pull request, to get the commit in. If there is anything else to be sorted out, a new issue can be created.

**Pull request merged**
