### PR TITLE
tm: add support for dropping messages in local-request event route

### PR DESCRIPTION
**Pull request by grumvalski**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Currently it is not possible to drop a local generated message in tm:local-request event route because there is no context associated when running the event route. With this PR I tried to solve this introducing a new returned error (E_DROP) and a context into t_run_local_req.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks!

I couldn't spot quickly the initialization of the context, something like:

```
init_run_actions_ctx(&ra_ctx);
```

**Comment by grumvalski** [comment]
right, added now.

**Comment by miconda** [comment]
OK, fine for me.

**Comment by henningw** [comment]
One remark - the E_DROP error is planned to be used for all kinds of drop() or only for the local request event route type? If the latter - maybe making the name a bit more specific to highlight that is only used for this particular case.

**Comment by grumvalski** [comment]
I haven't spotted any other usage for the moment. I could rename it like E_LOCAL_DROP.

**Comment by henningw** [comment]
Ok, this might be better understandable in the years to come. :-) Good addition, thanks.

**Comment by miconda** [comment]
If you keep it in core, then E_DROP is fine, it can be used in the future for similar purposes. If you rename it and make it specific to tm usage for local request route, then place the define in the tm module. We should not populate core with module specific needs.

**Comment by grumvalski** [comment]
I did put it in the core to avoid conflicts with other returned codes and for beeing used in the future (in case). I'll leave it in the core.

**Pull request merged**
