### PR TITLE
tls: update documentation (TLS v1.0 & 1.1 deprecation)

### PR DESCRIPTION
**Pull request by ffloimair**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Update TLS module documentation in regards of deprecation of TLS v1.0 and v1.1. Existing references updated and new reference added.
No code change!

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the PR. If I understand the commit correctly, its about the deprecation of v1.0. and v1.1. Could you maybe quickly adapt the commit message to that?

**Comment by ffloimair** [comment]
Thanks for spotting this @henningw.
I somehow mistyped the the wrong version into the commit message. I have changed it now and pushed the update.

**Comment by henningw** [comment]
Thank you

**Comment by ffloimair** [comment]
@henningw Is it possible to get this cherry-picked to 5.7 branch (and maybe even 5.6). Since it's documentation only and is valid to any version I think this would be desirable.
I read to contributing guidelines but I didn't fully understand whether a cherry-pick requires another PR or can be done separately.

**Comment by henningw** [comment]
Hi. The cherry-picking does not require another PR. It will be usually done as part of the release process for a minor version on the stable branches.

**Comment by ffloimair** [comment]
OK. Thanks for the clarification.

**Pull request merged**
