### PR TITLE
cdp: Fix for undefined symbols when using older/unsupported OpenSSL

### PR DESCRIPTION
**Pull request by mtryfoss**
This was originaly fixed in #3601, but that did not handle the change in #3612 very well.

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Fix for undefined symbols when using older/unsupported OpenSSL.
This was originaly fixed in #3601, but that did not handle the change in #3612 very well.

### CODE REVIEW

**Comment by henningw** [comment]
Thanks. The PR #3601 was merged already. I did looked to this change, but did not spotted why the error clearing added yesterday caused additional problems here?

**Comment by mtryfoss** [comment]
There's a big "#if OPENSSL_VERSION_NUMBER >= 0x10100000L" in cdp_tls.c, basically making the whole file empty for older versions.

sp->tls_conn would never be true in do_read() and do_write() if there was no supported openssl, so I didn't find any need to change those functions - until your mod yesterday which included a function defined in cdp_tls.c :)

**Comment by mtryfoss** [comment]
Sorry - closed by mistake. Reopened.

**Comment by henningw** [comment]
Thanks for the clarification.  Lets wait until the CI tests are done and then it will be merged, if there are no more comments.

**Pull request merged**
