### PR TITLE
nathelper - add received_ui pvar

### PR DESCRIPTION
**Pull request by lazedo**
allows comparison with persisted value in usrloc.

if($ulc(exp=>received) == $received_uri) {
  ....
}

### CODE REVIEW

**Comment by miconda** [comment]
This looks like $su from pv module.

**Comment by lazedo** [comment]
yes it does, but there is a difference. receive_uri returns the value as is persisted in usrloc,the proto is uppercase.
$su, $received_uri - sip:192.168.27.2:8305;transport=tcp - sip:192.168.27.2:8305;transport=TCP

**Comment by miconda** [comment]
String comparison should be lower case.

Besides that, there are string transformation 'tolower' and 'toupper'.

It is no need for another variable. Eventually the two functions should be made to use a common function stored in core.

**Comment by lazedo** [comment]
i agree, but not when is part of a select statement.
"select * from usrloc where received = $su" would not work.

**Comment by miconda** [comment]
I am sure sql has functions for tolower or toupper or case insensitive match.

**Comment by lazedo** [comment]
that depends on the engine, right ? the point is, the value is stored in mixed case. i'm trying to get a match of the value that is stored. 
nat_traversal also has a source_uri pv that matches what it internally calculates, nathelper should do the same.

**Comment by lazedo** [comment]
...or we can patch nathelper to lower case what it puts in received_avp ? and also make sure $su returns lowercase ?

**Comment by miconda** [comment]
I dont know about nat_traversal, perhaps is some quite old code.

I already said that the two functions should be made a wrapper to a common function stored in core. That will ensure consistency. I think transport in lowrr case is the common out there.

I can take care later today or tomorrow.

**Comment by lazedo** [comment]
fair enough. thank you.

**Pull request closed without merging**
