### PR TITLE
uac: Export two new functions for reg/unreg and rpc for reg

### PR DESCRIPTION
**Pull request by xkaraman**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

This PR exports some new functions for handling registration and deregistration in the uac table without waiting for timer to fire.

All of the following function require the parameters of the already available RPC function call `reg_unregister`:

- `kamcmd uac.reg_register`: Register for kamcmd similar to `uac.reg_unregister`
- `uac_reg_send_register`: Config function to register immediately without waiting for timer
- `uac_reg_send_unregister`: Config funtion to unregister immediately without waiting for timer
- Move required structures/functions to .h

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the PR. Could you also add documentation to the XML files for this extensions?

**Comment by henningw** [comment]
Thanks, lets wait a bit more for other feedback and then merge it.

**Comment by miconda** [comment]
Fine for me.

**Comment by oej** [comment]
What happens if a filter hits multiple accounts? Will all of them unregistered/register?

**Comment by henningw** [comment]
The newly added functions behave in a similar way like the existing RPC functions. Did not tested it, but from the code it should stop at the first match.

**Comment by oej** [comment]
Then that should be clearly documented

**Pull request merged**
