### PR TITLE
Make tcpops module usable on BSD

### PR DESCRIPTION
**Pull request by mslehto**
Tested with FreeBSD 10 and Linux 3.2 (Debian Wheezy 7.6).
List of other platforms gathered with [FreeBSD and Linux Kernel Cross-Reference](http://fxr.watson.org/fxr/trackident?i=TCP_KEEPIDLE)

### CODE REVIEW

**Comment by camilleoudot** [comment]
Thanks for the patch.
I'm not sure where `tcp_options.h` gets the `TCP_KEEP*` macros defined from, do I miss something?

**Comment by mslehto** [comment]
I have those in netinet/tcp.h.
It is included by tcp_main.c and modules/tcpops/tcpops.c
Can this still work?

**Comment by camilleoudot** [comment]
then it would make sense to also include `netinet/tcp.h` in `tcp_options.h`, to avoid any issue in the future if `tcp_options.h` is re-used elsewhere

**Comment by camilleoudot** [comment]
Merged, thanks for enabling the functionality on BSD

**Pull request merged**
