### PR TITLE
secsipid: fix build errors for older versions of secsipid lib

### PR DESCRIPTION
**Pull request by linuxmaniac**
#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally

#### Description
Nightly builds broke due to https://github.com/kamailio/kamailio/commit/c8d56ed3afa19c29279e54fffd40b9810bb0d67c
https://kamailio.sipwise.com/job/kamailiodev-nightly-binaries/2517/console

### CODE REVIEW

**Comment by linuxmaniac** [comment]
I have no clue how to get the defined version of the golang lib. I give up

**Comment by miconda** [comment]
Didn't `#if SECSIPID_VERSION >= 0x1030000` work? It should be the way to check the version.

**Comment by linuxmaniac** [comment]
I got confused due to ``src/modules/secsipid_proc/secsipid.h`` having the definition. Yes is should work.

**Comment by miconda** [comment]
I removed those .h files, were propagate over the time when there was no libsecsipid install. They are no longer needed.

**Pull request merged**
