### PR TITLE
nathelper: add optional set_contact_alias([trim]) parameter

### PR DESCRIPTION
**Pull request by eschmidbauer**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #2308 

#### Description
add support for trimming an already existing alias parameter when calling `set_contact_alias()`

### CODE REVIEW

**Comment by miconda** [comment]
Thanks!

If nobody has anything against, this can be merged before branching 5.4 to fix the situation of "strange" UA that take the alias from 200ok of REGISTER and use it for subsequent requests.

**Comment by miconda** [comment]
@eschmidbauer - my comment was to wait a few days before merging to see the opinion of other developers, not to merge.

**Comment by miconda** [comment]
There is also an issue reported by LGTM scanner: 'Local variable hides global variable', see above comments from their bot.

**Comment by eschmidbauer** [comment]
Apologies, I misunderstood. I can revert the commit

**Comment by eschmidbauer** [comment]
reverted and resubmitted PR (https://github.com/kamailio/kamailio/pull/2390) with update to address the LGTM scanner issue

**Comment by miconda** [comment]
A fair amount of time should be allowed for comments, considering time zones, traveling, etc ...

With the revert, I noticed that a new function was actually added to the core. If wanted there, then it should have been a separate commit for it. We want commits per components, so maintainers of each component can see easier their code is affected.

**Comment by eschmidbauer** [comment]
ive updated the new PR with 2 separate commits, one for core and one for the module

**Pull request merged**
