### PR TITLE
Python exception handling fixes

### PR DESCRIPTION
**Pull request by smurfix**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [X] PR should be backported to stable branches
- [X] Tested changes locally
- [X] Related to issue #4045

#### Description

Python's C interface contract states that C code must *either* raise an exception and return NULL, *or* return a Python object.

Doing both will raise a `SystemError` exception which obscures the original problem. It may also cause a memory leak.

### CODE REVIEW

**Comment by miconda** [comment]
I think the code is better how it is because the second parameter of the function you gave as example in the issue has to be a valid string. In the current form, it indicates there is a problem with the parameter, rather than having it silently not doing anything when it was expected to be a change of the value. As commented in the issue, use sr-users mailing list if you want to discuss further.

**Comment by smurfix** [comment]
You seem to have misunderstood me here. I am **not** trying to suppress the exception. I am trying to make sure that the programmer gets the **correct** exception (`TypeError`) handed to them.

The Python C interface documentation is pretty clear on this point. You MUST return NULL instead of a `PyObject*` when your C code has set an exception. The resulting `SystemError`, on top of the `TypeError` the calling Python code *should* be getting, is a pretty clear and unequivocal demonstration of this, and it even says what's wrong ("SystemError: <built-in function sets> returned a result with an exception set"). See my bug report for the example stack trace.

**Comment by smurfix** [comment]
NB: Two years ago I found another example of this problem which was fixed in b7911b6.

**Comment by henningw** [comment]
Re-opened, as there seems to be still discussions necessary if the python KEMI interface should be adapted to the interface documentation.

**Comment by miconda** [comment]
OK, thanks for explaining further -- as a not much expert in python, it looked like hiding it by not providing the right parameter, so if I got it wrong, then it is fine to merge.

**Comment by smurfix** [comment]
Thank you.

**Pull request merged**
