### PR TITLE
LRKProxy module(Light RTP Kernel Proxy)

### PR DESCRIPTION
**Pull request by mojtabaesfandiari**
#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
@mojtabaesfandiari: thanks for renaming the module. You still have to add the `doc/` folder in the module with the xml docbook files that can be used to generate the README. Can you add them in this PR?

At the end, probably I will merge the PR manually to set a proper description in the commit message, to correspond to a new module addition, rather than indicating a rename of a former pull request.

**Comment by mojtabaesfandiari** [comment]
@miconda Sure, I will add doc/ folder,too. I might take a little time. I will do it as soon. Thanks

**Comment by jchavanton** [comment]
@mojtabaesfandiari I was watching your presentation as Fosdem, you mention that LREproxy can provide NAT traversal for endpoint ?

**Comment by mojtabaesfandiari** [comment]
@jchavanton Absolutely yes, Like as other B2BUA services that supports.

**Comment by mojtabaesfandiari** [comment]
The LRKProxy engine is updated and renamed, too.
https://github.com/mojtabaesfandiari/pylrkproxy

**Comment by jchavanton** [comment]
@mojtabaesfandiari interesting, I did not see any symmetric latching, HNT hosted NAT traversal logic in the code, can you point out more precisely where this is in the code ?



For the sake of clarity,  B2BUA is related to signaling just like user-agent is a SIP concept, in this specific use case it can not be a B2BUA since Kamailio is a proxy.  I get that you probably meant anything relaying media can replace an SBC/B2BUA.

**Comment by mojtabaesfandiari** [comment]
@jchavanton I underestand what  you mean. You could have a look in kernel space section code in pylrkproxy engine in https://github.com/mojtabaesfandiari/pylrkproxy/tree/master/lib/c/kernel_space.ko.
In Kernel space code, we use destination ports of packets as a index to find next endpoint in session.

**Comment by miconda** [comment]
@mojtabaesfandiari - thanks for the xml docs and the efforts to adjust it to be integrated in Kamailio. I will prepare the PR for a manual merge to look like a fresh import of a new module, then you can get commit access to push future commits to it. You can still use pull requests if you prefer this kind of work flow.

**Comment by miconda** [comment]
Merged with commit:

  * https://github.com/kamailio/kamailio/commit/08738ba5a0ee03afa4e47f7174e25a1cf23f05b4

Further discussions can be done via mailing lists or via new issues on the tracker.

**Comment by miconda** [comment]
@mojtabaesfandiari - sent you invitation to get write access to the github repo to maintain the module. While compiling the module with clang, I found a warning that has to be addressed, reported at:

   * https://github.com/kamailio/kamailio/issues/2663

**Pull request closed without merging**
