### PR TITLE
core:tcp allow to handle TCP connections with tcp_accept_haproxy=yes flag even message does not contain PROXY protocol header

### PR DESCRIPTION
**Pull request by ovoshlook**
Covers setups when kamailio behind the service with HAPROXY protocol support but in other hand it also serves requests from other services that available per direct connection (such as B2BUA in the same local network).

#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally

#### Description
- function tcpconn_read_haproxy() returns 2 if PROXY header NOT found. 
- Message about no header shown at the debug level.
- No errors
- TCP connection successfully establishes

### CODE REVIEW

**Comment by miconda** [comment]
I applied the patches manually, with some updates to log messages. Test and if any issues, report on bug tracker. Thanks!

**Comment by ovoshlook** [comment]
tested - works fine. IS it possible to push it into 5.3.x branch as well? I know there more changes in the tcp_main a 5.4.0
I can prepare PR for 5.3 branch.

**Comment by vaizki** [comment]
Documentation still states in the core cookbook:

> Please note that enabling this option will reject any inbound TCP connection that does not conform to the PROXY-protocol spec.

So I started looking at making this a per-listen socket option.. And then ran into this commit. Apparently all connections would be accepted now in 5.6, including my Prometheus scraping through xhttp? So the only side effect of having non-proxyprotocol connections is a debug-level message about it?

**Comment by ovoshlook** [comment]
Hi 
I think,  I just forgot to update this part of the doc.
It should be working fine for any connection type and yes. It should be only a debug-level message

But feel free to test it and let us know if something is wrong.

**Pull request closed without merging**
