### PR TITLE
bugfix IMS_Rx dialog callback

### PR DESCRIPTION
**Pull request by annema-Kontron**
ims_dialog bugfix for registering dialog callbacks
ims_qos bugfix for Rx register dialog callback

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches --> 5.3
- [x] Tested changes locally --> Tested locally based on 5.1.6
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

ims_dialog bugfix for registering dialog callbacks

In Rx scenarios of parallel forking (several INVITEs with same CALLID
and FROMTAG sent to PCSCF) and INVITE for orig and term handled in
same PCSCF (means also INVITEs with identical  CALLID and FROMTAG) the wrong
dialog is selected for registering the callback (i.e. the callback
for sending STR) when 200OK from terminator is processed.
Root cause is that dialog is searched with callid-fromtag-totag but at
the time of dialog insertion (processing of INVITE) no totag is available.
fix is to get ctx dialog at 200OK processing before suspending the
transaction - save dialog until AAA is received - use this dialog for
registering the STR callback.

ims_qos bugfix for Rx register dialog callback

In some scenarios like parallel forking several INVITE with identical
CALLID and FROMTAG sent to PCSCF which inserts dialogues for each INVITE.
When 200OK is received in PCSCF the dialog callback must be registered
for the respective dialog. Currently sometimes the wrong dialog is selected
by searching with CALLID FROMTAG and TOTAG thus leading to problem
no STR is sent at BYE. Fix is to pickup the right dialog before suspending
the transaction during AAR/AAA processing and reuse this saved dialog
after AAA reception for registering the dialog callback.

### CODE REVIEW

**Comment by christoph-v-kontron** [comment]
Just for your info: Annemarie @annema-Kontron is our colleague, who will be responsible for pull requests in the future.

Christoph Valentin

**Comment by miconda** [comment]
If no there comments, it will be merged soon.

**Comment by henningw** [comment]
Looks fine to me. The log messages mentions some conflicting files, maybe it makes sense to merge it manually and adapting the log messages.

**Comment by annema-Kontron** [comment]
Hi,

I am very glad to hear you are satisfied and take the changes into consideration.

Best Regards,

Annemarie

Von: Daniel-Constantin Mierla <notifications@github.com>
Gesendet: Samstag, 28. März 2020 08:34
An: kamailio/kamailio <kamailio@noreply.github.com>
Cc: Mandl Annemarie <Annemarie.Mandl@kontron.com>; Mention <mention@noreply.github.com>
Betreff: Re: [kamailio/kamailio] bugfix IMS_Rx dialog callback (#2263)


If no there comments, it will be merged soon.

**Comment by christoph-v-kontron** [comment]
> 
> 
> Looks fine to me. The log messages mentions some conflicting files, maybe it makes sense to merge it manually and adapting the log messages.

For manual merge of the PR, do you need any support from our side (kontron), or can that be done by kamailio developers?

**Comment by henningw** [comment]
It is all fine, thanks. I will do it later today.

**Comment by henningw** [comment]
Merged manually in git master, thanks again.
- e2a1b967fd6e
- 2768f8ce1cf

**Comment by henningw** [comment]
backported to 5.2 and 5.3 branches

**Comment by annema-Kontron** [comment]
That’s great,  thanks a lot.

Von: Henning Westerholt <notifications@github.com>
Gesendet: Montag, 30. März 2020 19:08
An: kamailio/kamailio <kamailio@noreply.github.com>
Cc: Mandl Annemarie <Annemarie.Mandl@kontron.com>; Mention <mention@noreply.github.com>
Betreff: Re: [kamailio/kamailio] bugfix IMS_Rx dialog callback (#2263)


Closed #2263<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkamailio%2Fkamailio%2Fpull%2F2263&data=02%7C01%7CAnnemarie.Mandl%40kontron.com%7Cb236e6595f5746977e1708d7d4cce9dd%7C8c9d3c973fd941c8a2b1646f3942daf1%7C0%7C0%7C637211849492769723&sdata=e9avDEqliGqYWomb4UjACUtCwld1KLhYJsPpfxyYlsc%3D&reserved=0>.

**Comment by annema-Kontron** [comment]
Thanks a lot 😊

Von: Henning Westerholt <notifications@github.com>
Gesendet: Montag, 30. März 2020 19:11
An: kamailio/kamailio <kamailio@noreply.github.com>
Cc: Mandl Annemarie <Annemarie.Mandl@kontron.com>; Mention <mention@noreply.github.com>
Betreff: Re: [kamailio/kamailio] bugfix IMS_Rx dialog callback (#2263)


backported to 5.2 and 5.3 branches

**Pull request closed without merging**
