### PR TITLE
pkg/kamailio: Fixed systemd unit failure on server boot

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by amessina** [comment]
I'm not sure you need After=network.target and network-online.target, but based on https://fedoraproject.org/wiki/Networking/Ideas/ServiceOrdering, you will want Wants=network-online.target

**Comment by sergey-safarov** [comment]
Please look https://github.com/kamailio/kamailio/pull/1104/files
Think IP_FREEBIND is preferred implementation.

**Comment by amessina** [comment]
@sergey-safarov -- agree that I'd like Kamailio to have a way to bind to :::5060/udp, :::5061/tcp/tls for example.

That being said, I'm not sure of the Kamailio internals.  Just binding with IP_FREEBIND might not mean that functions within Kamailio detect addresses properly, etc.

**Comment by miconda** [comment]
Closing this one, it looks it requires the backport of #1089 in order to be coherent.

**Pull request closed without merging**
