### PR TITLE
rtpengine: added support for DTLS transports

### PR DESCRIPTION
**Pull request by jerzyptak**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [x] Related to issue #1458

#### Description

Added ability to explicitly request usage of DTLS transports UDP/TLS/RTP/SAVP and UDP/TLS/RTP/SAVPF via rtpengine API.

### CODE REVIEW

**Comment by miconda** [comment]
@rfuchs - should this be backported to 5.1 branch? I can do it before the release tomorrow.

**Comment by rfuchs** [comment]
@miconda it's not really a bugfix, and FTR what this commit does has been possible before too, using `transport-protocol=UDP/TLS/...` (which is what people have been using)

**Comment by rfuchs** [comment]
@miconda that being said, since 5.1 isn't actually out yet, you're welcome to cherry pick it in

**Comment by miconda** [comment]
OK, thanks for clarifications. Tomorrow I plan to release the 5.1.2 and ponder what to backport.

**Comment by jerzyptak** [comment]
Yes, this is not a bugfix, it is just a streamlining change that removes the need to use the undocumented feature `transport-protocol=UDP/TLS/...`.

**Comment by aalba6675** [comment]
@rfuchs this commit has broken my use of `rtpengine_manage(DTLS=off)`. Now the key DTLS is not passed to rtpengine but hijacked to set transport.

Without DTLS=off rtpengine adds two lines to SDP
a=setup:actpass
a=fingerprint:xxxxxxxxxxxxxxxxxxxxxxxxxxx

This seems harmless, but FreeSWITCH expecting SDES fails. UACs based on PSJIP are working. I think that is why my kamailio scripts always had DTLS=off to make FreeSWITCH happy.

**Comment by miconda** [comment]
@aalba6675 - do not comment in two places for the same issue, it is hard to track where the relevant information is written. As you opened a bug, comment there and reference the PR with #NUMBER .

**Pull request merged**
