### PR TITLE
sca: terminate all error and debug messages with a new line 

### PR DESCRIPTION
**Pull request by TheGrandWazoo**
Reported by oej GH #580. Includes whitespace cleanup and normalizing.

### CODE REVIEW

**Comment by miconda** [comment]
I see the file utils/kamctl/mysql/ims_dialog-create.sql being also changed. Was is automatically generated?

**Comment by TheGrandWazoo** [comment]
Must of been. I did not even touch that.

**Comment by TheGrandWazoo** [comment]
I did a simple pull request to make sure I was conforming to the the standards. Thank you for showing me that doc.

**Comment by miconda** [comment]
Committing changes that you are not aware of it's not a good thing, because it can break exiting code. Somehow you changed ims_dialog-create.sql and if we don't know why you did it, then it cannot be merged. You can use "git status" before any commit to see what files are affected by the commit.

Regarding the removal of outbound_proxy, I see that it was set in a structure. Have you checked that the structure is not passed to the dependency modules like tm, sl where the field might be used?

**Comment by miconda** [comment]
Thanks! I pushed the pull request manually on your behalf to get the end result of it (commit), avoiding changing and reverting other files.

You can push the other patches you have for sca module as new pull requests.

**Pull request closed without merging**
