### PR TITLE
core: add a module hook for post-fork cleanup

### PR DESCRIPTION
**Pull request by aalba6675**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [X] Related to issue #2885

#### Description
This PR provides a hook for modules when all `fork_process()`s are completed.
This is so that the module in the main process context can perform post-fork cleanup.

### CODE REVIEW

**Comment by aalba6675** [comment]
A user of this hook would be the app_python3 module: it needs to know when all the child processes are forked, then the main process would perform internal state cleanup. 

See the description of `PyOS_AfterFork_Parent`: https://docs.python.org/3/c-api/sys.html

**Comment by aalba6675** [comment]
How this feature will be used in app_python3 - this gives a hook to call `PyOS_AfterFork_Parent`:
```
/**
 *
 */
static pid_t main_pid = 0; /* record pid_t of main process */

static int child_init(int rank)
{
	if(rank==PROC_INIT) {
		/*
		 * this is called before any process is forked
		 * so the Python internal state handler
		 * should be called now.
		 */
#if PY_VERSION_HEX >= 0x03070000
		PyOS_BeforeFork() ;
#endif
		main_pid = getpid();
		return 0;
	}
	if(rank==PROC_POST_FORK) {
		/*
		 * this is called after all processes are forked
		 * so the Python internal state handler
		 * should be called.
		 */
#if PY_VERSION_HEX >= 0x03070000
		PyOS_AfterFork_Parent() ;
#endif
		return 0;
	}
	_apy_process_rank = rank;

	/*
	 * If non-daemonize we are called in the main context
	 * with rank = PROC_SIPINIT
	 */
	if (main_pid != getpid()) {
		/* we really are a child process */
#if PY_VERSION_HEX >= 0x03070000
		PyOS_AfterFork_Child();
#else
		PyOS_AfterFork();
#endif
	}
	if (cfg_child_init()) {
		return -1;
	}
	return apy_init_script(rank);
}
```

**Comment by miconda** [comment]
Introduction of another execution of init_child() with a different rank impacts all the modules, it may have side effects for modules that handle only the ranks expected so far. Therefore, even the patch is small, has to be analysed the impact.

An alternative would be to add another core event with arming in the mod_register().

I will think a bit about and see what would be the best.

**Comment by aalba6675** [comment]
Unfortunately I found code snippets like this:

```
static int child_init(int rank)
{
        int i, j;
        int len;
        xhttp_rpc_mod_cmds_t *cmds;
        /* rpc_export_t *rpc_e; */

        if(rank==PROC_MAIN || rank==PROC_TCP_MAIN)
                return 0; /* do nothing for the main process */
```

So some modules are "aware" of which ranks refer to the main process.

**Comment by aalba6675** [comment]
@miconda — have you had the chance to consider a better solution to this issue?
I am thinking of going through the various modules and see how they check for rank:

   /* ???? have an escape for a module if the module needs to do 
     * does something for PROC_INIT, PROC_MAIN and rank > 0 (and small negative integers PROC_TCP etc)
     * then do nothing and return here ???? */
  if (rank < PROC_MAIN_ONLY) return 0;  // PROC_MAIN_ONLY == -128 
  
Then to apply this PR I could set

    PROC_POST_FORK = -129
    // other new ranks can be created with values < -128 and all modules would not be affected

**Comment by miconda** [comment]
@aalba6675 - had a busy week, I thought of introducing a mechanism that should allow modules to specify in mod_init() if they want to execute special types of ranks for child_init(), so it will not impact other modules at all (because I remember when PROC_INIT was introduced, we discovered some side effect long time after). I hope to find some time for it this week.

**Comment by miconda** [comment]
I pushed the commit 7f89e4cc5c84b720928c2936c9e2e0630aebec9e for this purpose.

You have to execute `ksr_module_set_flag(KSRMOD_FLAG_POSTCHILDINIT)` inside `mod_init()` and then handle rank `PROC_POSTCHILDINIT` in `child_init()`.

Hoping it offers what is needed for this one.

**Comment by aalba6675** [comment]
Thank! Closing with d2c22d2.

**Pull request closed without merging**
