### PR TITLE
dispatcher: ds_list_exist support pv as param (only logging level adjustment was kept)

### PR DESCRIPTION
**Pull request by jchavanton**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Change parameter one to support pseudo variables
```
if (ds_list_exist("12001") {
...
}
```
or
``` 
$var(id) = 10;
if (ds_list_exist($var(id)) {
...
}
```

### CODE REVIEW

**Comment by lazedo** [comment]
@jchavanton this is ok but you could already do 
```
if (ds_list_exist("$var(id)") {
```

**Comment by miconda** [comment]
The current approach is Kamailio specific and I think it is fine to keep it, because it already allows giving the variable as parameter. The fixup proposed to be used in this patch is inherited from SER side.

**Comment by jchavanton** [comment]
Thanks for the feedback,

Weird, I decided to change it because it was not accepting the was (complaining at startup).
I will dig it further.

We could add deprecated comments here and there to point to the favored alternatives.

**Comment by jchavanton** [comment]
```
$var(list) = 10;
if (ds_list_exist($var(list))) {
...
```

```
 0(8) CRITICAL: <core> [core/cfg.y:3507]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 200, column 21-44: function ds_list_exist: parameter 1 is not constant
```

**Comment by jchavanton** [comment]
I see this is working :
```
$var(list) = 10;
if (ds_list_exist("$var(list)")) {
...
```

I guess I have what I need ...

**Comment by jchavanton** [comment]
I looked again at the macros, I will always search in `core/mod_fix.h`
```
FIXUP_F2FP(igp_null      , 1   , 1   ,   1, FPARAM_INT|FPARAM_PVS, 0)
#define FIXUP_F2FP(suffix, minp, maxp, no1, type1, type2) \
```

**Comment by jchavanton** [comment]
I converted the PR to a small logging level adjustments.

**Comment by lazedo** [comment]
the `INFO` level for this message is actually misleading ops that get into panic saying `something's not working` when is perfectly normal not to have entries in some group. just merge it :)

**Comment by miconda** [comment]
I consider it should be merged as well: there is no relevant need to have a log message other than debug to confirm one or the other goal of the function -- in this case the function is to detect if a destinations group exists or not, by returning appropriate code in each case, so custom log messages can be printed in config routing blocks.

Anyhow, to differentiate between error and not found, I will change a bit the return codes. So, I am going to close this one and push a slightly different commit soon.

**Pull request closed without merging**
