### PR TITLE
topos_htable new module

### PR DESCRIPTION
**Pull request by stefan-mititelu-idt**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Looks like htable module already exports API functions, but currently no other module uses them.
Added 2 more API functions for table creation (so other modules can be able to create their own hash tables if they want to)

### CODE REVIEW

**Comment by stefan-mititelu-idt** [comment]
Added new commit to this PR to fix htable pkg cell "str" pointers.

**Comment by stefan-mititelu-idt** [comment]
Thanks @miconda.

Next week we will be doing some more testing for this new module, focusing on load-testing it. I will come with an update on this PR, right after.

**Comment by stefan-mititelu-idt** [comment]
force-pushed PR with a few changes since previous time:
- a few bug fixes for topos_htable
- call storage end dialog callback for topos received negative replies of INVITE/SUBSCRIBE => so will be cleaned up faster
-  didn't need the "mode" param for set_expires api function of htable module

**Comment by miconda** [comment]
Is this PR ready for review to merge? Or is still some work to be done and pushed here before?

**Comment by miconda** [comment]
OK, thanks, I am merging it -- I focused on the small changes done to the existing modules, the new module can be adjusted as needed if issues are found.

**Pull request merged**
