### PR TITLE
usrloc: call contact expired call back for a domain with db_mode: DB_ONLY

### PR DESCRIPTION
**Pull request by adil-mafzool**
usrloc: call contact expired call back for a domain with db_mode: DB_ONLY; database rows are removed by the timer function: db_timer_udomain

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ X] PR should be backported to stable branches
- [X ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Currently call contact expired call back for a domain with db_mode: DB_ONLY doesn't callback function for "usrloc:contact-expired" to carry out call back application actions since database rows are removed by the timer function: db_timer_udomain. There is addition of new function  udomain_contact_expired_cb which will only call the call back function when contact are being removed from the database.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks for the contribution!

This will bring coherence with the other values for db_mode, so if the other devels have nothing against, it can be merged, even if we are in the freezing phase for v5.2.0.

The only adjustment I would make is to add a mod param to control the execution of the new function, because it can be a lengthly execution when there are many records in the database and this functionality is not needed always.

**Comment by henningw** [comment]
@miconda: It is not strictly a bugfix - but as you said it brings coherence to the module with the other values for db_mode. So I have nothing against the exception to merge it now in the current phase of development. To addea module parameter is a good idea as well.

@adil-mafzool: I have one question about your patch: you create both a new urecord and a ucontact in the timer callback function, and I think both are allocated in new memory. But you only cleanup the ucontact, not the urecord after the callback processing. Is this not necessary or it is cleanup at another place?

**Comment by adil-mafzool** [comment]
@miconda: Adding db_mode would be required since db_timer_udomain is now being called for different db_modes.
@henningw: Had seen that but since the concept was duplicated from ``preload_udomain``` where ucontact was being freed where as urecord was not. It looks like urecord is using static memory function get_static_urecord and doesn't use shm_malloc.

**Comment by miconda** [comment]
This is not a pure fix to a bug -- I said I am fine to merge it in this phase of testing the upcoming 5.2.0 release because it brings coherence with the other db modes. With git is easy to clone the repo and maintain back ports as you need.

**Comment by adil-mafzool** [comment]
@miconda thats ok!!

**Comment by henningw** [comment]
Thank you, merged into master branch.

**Pull request merged**
