### PR TITLE
p_usrloc: Fix #1265: missing columns in location.sql file.

### LINKED ISSUE #1265: p_usrloc: location.sql missing RUID_COL and REG_ID_COL
## p_usrloc: location.sql missing columns

[location.sql](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/location.sql) should include columns corresponding to `RUID_COL` and `REG_ID_COL`) from [p_usrloc_mod.c](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/p_usrloc_mod.c#L65)

### Log Messages
```
kamailio: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Unknown column 'reg_id' in 'field list' (1054)
kamailio: ERROR: <core> [db_query.c:132]: db_do_query_internal(): error while submitting query
kamailio: ERROR: p_usrloc [ul_db_query.c:110]: db_exec_query(): could not query table location.
```
```
kamailio: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Unknown column 'ruid' in 'field list' (1054)
kamailio: ERROR: <core> [db_query.c:132]: db_do_query_internal(): error while submitting query
kamailio: ERROR: p_usrloc [ul_db_query.c:110]: db_exec_query(): could not query table location.
```
### Solutions
Adding columns referenced by [p_usrloc_mod.c](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/p_usrloc_mod.c#L65) to match `kamdbctl`'s [usrloc-create.sql](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/utils/kamctl/mysql/usrloc-create.sql#L3)

### PR DESCRIPTION
**Pull request by asiplas**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #1265 

#### Description
Add columns referenced by [p_usrloc_mod.c](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/p_usrloc_mod.c#L65)

### CODE REVIEW

**Comment by lbalaceanu** [comment]
Thank you for your fix.

**Comment by miconda** [comment]
Are these changes done first in the xml schema with table definition from src/lib/srdb1/schema? If done only in sql files, then it is done in the wrong place.

**Comment by lbalaceanu** [comment]
Hello Daniel,

location.sql is the only changed file. I see in the src/lib/srdb1/schema/location.sql that this is documented as belonging to usrloc and that the columns are present there.

Should I create a similar xml for p_usrloc used tables? 

Thank you

**Comment by miconda** [comment]
Ohh, actually the sql file was in the module folder, I thought is in the utils/kamctl/{mysql,postgres,...}. So it is in the wrong place.

Yes, the best is to create xml definition as for location (usrloc module), then you can do 'make dbschema' to get the sql files generated. You may need to update the Makefile in the schema folder.

**Pull request merged**
