### PR TITLE
nathelper: don't fail if 'a=rtcp' has no IP

### LINKED ISSUE #2768: nathelper: 'a=rtcp' without IP generates an ERROR
### Description
As described at [RFC3605](https://datatracker.ietf.org/doc/html/rfc3605#section-2.1)
```
rtcp-attribute =  "a=rtcp:" port  [nettype space addrtype space  connection-address] CRLF
```
So IP info is optional.

#### Log Messages

```
Jun 7 09:55:57 sp2 lb[46796]: ERROR: DEFAULT_ROUTE nathelper [nathelper.c:1796]: nh_extract_mediaip(): no `IP[4|6]' in `a=rtcp' field
Jun 7 09:55:57 sp2 lb[46796]: ERROR: DEFAULT_ROUTE nathelper [nathelper.c:1617]: replace_sdp_ip(): can't extract 'a=rtcp' IP from the SDP
```

#### SIP Traffic

```
INVITE sip:jsung2@192.168.88.194;line=8c86b7427b1107f SIP/2.0
Via: SIP/2.0/UDP 192.168.88.194;branch=z9hG4bK4f82.52fb005dac4fe078dd5593a1bebfa33b.0
From: <sip:4316607564835@xxxx>;tag=40FED3EF-60BDED10000D2F23-71F92700
To: <sip:jsung2@xxxx>
CSeq: 939 INVITE
Call-ID: CDqyvKE3ryYIRkecp_7cXA..
Max-Forwards: 69
Allow: INVITE, ACK, CANCEL, BYE, NOTIFY, MESSAGE, OPTIONS, SUBSCRIBE
P-Asserted-Identity: <sip:4316607564835@sip.lab.com>
Diversion: <sip:4316607564835@xxxx>;privacy=off;counter=1
Supported: timer
Session-Expires: 1800
Min-SE: 90
Content-Type: application/sdp
Content-Length: 316
Contact: <sip:btpsh-60baedf4-645b-3@192.168.88.194>

v=0
o=Z 1623059728682 1 IN IP4 192.168.88.194
s=Z
c=IN IP4 192.168.88.194
t=0 0
m=audio 20252 RTP/AVP 8 0 9 98 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:9 G722/8000
a=rtpmap:98 telephone-event/48000
a=fmtp:98 0-16
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:20253
```

### Possible Solutions

fix for nathelper will follow

### Additional Information

```
version: kamailio 5.5.0 (x86_64/linux)
```

### PR DESCRIPTION
**Pull request by linuxmaniac**
Examples from RFC3605:
>    m=audio 49170 RTP/AVP 0
>    a=rtcp:53020
>
>    m=audio 49170 RTP/AVP 0
>    a=rtcp:53020 IN IP4 126.16.64.4
>
>    m=audio 49170 RTP/AVP 0
>    a=rtcp:53020 IN IP6 2001:2345:6789:ABCD:EF01:2345:6789:ABCD

fix #2768

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #2768 (replace XXXX with an open issue number)

#### Description

don't fail if there's no IP info if line is 'a=rtcp'

### CODE REVIEW

**Comment by miconda** [comment]
Is it somehow related to PR #2737?

**Comment by linuxmaniac** [comment]
> Is it somehow related to PR #2737?

No, it's not.

**Comment by miconda** [comment]
It seems to be a conflict looking at the commits in the two PRs, if the offsets are not messing my evaluation -- yours is changing replace_sdp_ip() function with:

```
-	if(!hasreplaced) {
+	if(!hasreplaced && memcmp("a=rtcp", line, 6) != 0) {
 		LM_ERR("can't extract '%s' IP from the SDP\n", line);
 		return -1;
 	}
```

The #2737 removes there:

```
-	if(!hasreplaced) {
-		LM_ERR("can't extract '%s' IP from the SDP\n", line);
-		return -1;
-	}
```

Maybe @dwagin can check this PR as well.

It has to be decided if they need to be combined or one skipped, ...

**Comment by arsperger** [comment]
Hello @linuxmaniac 
seems this use case somehow escaped from my attention, when I was looking into the fix for #2459.  
Thank you for fixing it up.

**Comment by linuxmaniac** [comment]
It seems both are trying to fix the same issue. I didn't notice #2737
@dwagin can you please check it my solution works for you?

**Comment by miconda** [comment]
If no further comments soon, we can merge this one being simpler and tested by @linuxmaniac. And the other one can be reworked if its developer comes back later and considers to fix other issues as well.

**Pull request merged**
