### PR TITLE
tcp/docs: Added tcp_accept_iplimit config sample

### PR DESCRIPTION
**Pull request by arnivoit**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [X] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
We noticed that configuration option tcp_accept_iplimit was included in newer kamailio versions (most notably 5.7.4), and it was a breaking change for us. Added sample configuration value in /etc/kamailio.cfg file - already tested in our production deployment.

### CODE REVIEW

**Comment by henningw** [comment]
Looks good to me, its also just a comment in the end. Lets wait a bit more for feedback and then merge it.

**Comment by miconda** [comment]
Fine for me to add it to the default config file `etc/kamailio.cfg`, but the commit message should be updated to reflect that, not the prefix `tcp/docs:` is not suggesting at all it is about `etc/kamailio.cfg`.

**Comment by henningw** [comment]
Thanks, it was merged manually due to a wrong commit message.

**Comment by henningw** [comment]
commit 30a0fe2ea4b1b5

**Pull request closed without merging**
