### PR TITLE
ims_qos: check and log for NULL sessionId

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [X] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Check for NULL sessionId from PCRF, which can lead to kamailio crash.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks!

**Comment by smititelu** [comment]
can I backport this to 5.7 and 5.6?

**Comment by henningw** [comment]
It is a bugfix, sure. Small note regarding future patches, its actually not necessary to include the function name prefix in the log message, it should be added automatically from the LM_ERR etc.. macros.

**Comment by smititelu** [comment]
OK, thank you.

**Pull request merged**
