### PR TITLE
ims_isc: add-on for third-party registration

### PR DESCRIPTION
**Pull request by christoph-v-kapsch**
Change in ims_isc/checker.c and ims_isc/checker.h:
   add to isc_match two new flags include_register_request
   and include_register_response in addition to service_info
   Both info are retrieved from HSS during SAR/SAA
Change in ims_isc/third_party_reg.c/.h:
   Add REGISTER Request or REGISTER Response or Service Info
   to the body of the REGISTER message that is sent to the
   AS, if it is requested by content of HSS (SAR/SAA)
Change in ims_registrar_scscf/userdata_parser.c and
          ims_usrloc_scscf/usrloc.h:
   Parse the additional flags, when they are received from HSS
   and store in the subscription.

Conflicts:
	src/modules/ims_isc/third_party_reg.c
	src/modules/ims_rdn/userdata_parser.c

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
         ---> apologies, we did this commit long ago, when we did not know the rules of the project
                 main changes are in ims_isc, two small changes in ims_registrar_scscf and ims_usrloc_scscf
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally based on a local branch derived from 5.1.0
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

The feature is a small add-on to third party registration in S-CSCF
The feature assumes two new flags in HSS database, where additional to the "Service Info XML" an "insertRegisterRequest" flag or an "insertRegisterRepsonse" flag can be set. These flags are sent with the SAR/SAA exchange to the S-CSCF, where the new feature does a prioritization:
If Service Info present -> add service info to body of 3rd Party REGISTER Request
else if insertRegisterRequest -> add original REGISTER request to body of 3rd Party REGISTER request
else if insertRegisterResponse -> add original REGISTER response to body of 3rd Party REGISTER request
else -> add no body to 3rd Party REGISTER request.
Multipart Body is not supported.
More info about the insertRegisterRequest and insertRegisterResponse flags can be found in applicable 3GPP standards.

### CODE REVIEW

**Comment by henningw** [comment]
Hi Christoph, thank you for the pull request. Could you please create one commit for each affected module, that it can be applied individually? Have a look to our documentation: 
https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md

**Comment by christoph-v-kapsch** [comment]
Hi Henning,
Sorry, my problem is the commit was already done originally this way. How could I split one commit "file-by-file"? Is this possible? Sorry it's the first time I have this problem, need a hint.
Thx

**Comment by henningw** [comment]
Hi Christoph, understand.. It is also possible to merge it manually just from the patch, I will do it next week if there are no more comments to this extension.

**Comment by christoph-v-kapsch** [comment]
Hi Henning
Thank you.
What do you need as input from our side?

**Comment by henningw** [comment]
Could you add also some documentation for this new flags and/or module behaviour? If there are no module parameter etc.., a paragraph in the general module docs would be fine. You can simply add it as a new commit to this branch.

**Comment by christoph-v-kapsch** [comment]
Hi Henning,
Added a commit for the doc xml of the ims_isc module. I did not yet change the README file. Should I do that or would you like to collect more changes, before changing README?

**Comment by henningw** [comment]
Thank you for the addition. About the README - please don't include it in the pull request. The README is auto-generated after every doc XML file update.

**Comment by henningw** [comment]
Thank you, the pull request was merged manually in git master.

**Pull request closed without merging**
