### PR TITLE
core: PV_IDX_NONE to point that pv had no index

### PR DESCRIPTION
**Pull request by linuxmaniac**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally

#### Description

if index is 0 there were no way to know if the index was there

$x_hdr(A) = "value" needs to append a value
$(x_hdr(A)[0]) = "value" needs to set the value

pv_parse_spec(str *s, pv_spec_p p) was always setting p->pvp.pvi.type
to 0 == PV_IDX_INT

### CODE REVIEW

**Comment by linuxmaniac** [comment]
If no objections, I will merge this PR tomorrow

**Comment by henningw** [comment]
No objections, just one question - is my assumption correct that this will not change the PV behaviour for existing ***common*** use cases?

**Comment by linuxmaniac** [comment]
> No objections, just one question - is my assumption correct that this will not change the PV behaviour for existing _**common**_ use cases?

I didn't spot any other problems a part of the ones fixed at 9ac856fc3794699c09717264694956f2f3f148f7

**Comment by henningw** [comment]
Ok, thank you.

**Pull request merged**
