### PR TITLE
branch_failure route in case 503 and dns failover

### PR DESCRIPTION
**Pull request by vlitvinov**
#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

When we use DNS failover in case of timeout kamailio executes the branch_failure route. In the case of the 503 - on_reply route. This commit is to equate behavior in both cases. So if there are more candidates we will always execute branch_failure route and on_reply route only if this is the last candidate.

### CODE REVIEW

**Comment by miconda** [comment]
The onreply_route is designed for executing when a sip reply is received and should be kept like that otherwise many configs will get unexpected results. Even without dns failover, the onreply route is not executed on retransmission timeout, but the failure route block.

Branch failure event route was added later and I am not sure how coherent its behaviour is. If it is not executed on 503, the it should be. But also onreply_route should be executed on 503 when the response is received from the network.

From my perspective, if you want to change when the onreply route is executed, you have to make it configurable, via a modparam, with the default behaviour being the one so far.

**Comment by miconda** [comment]
You have to also document the new module parameter in the doc/ folder of tm. PR can be merged once the docs are update and no other comments to PR are made.

**Comment by henningw** [comment]
@vlitvinov any update from your side?

**Comment by miconda** [comment]
This got somehow out of sight for pretty long, but looking now at combined diff it seems that order of code execution changes and can have significant impact. As I understand, the loop with `t_send_branch()` is now executed before `onreply_route` handling. If I got it right, that can have unwanted effects, like sending out new branches before handling the response.

This PR needs proper review and testing before merging.

**Comment by vlitvinov** [comment]
This is the main idea do not execute on_reply route in case 503 and available failover endpoint. The same behavior as with timeout.
There is no possibility to know did we try all candidates. In our case when we use the rtpengine we do delete but after that we can have successful reply from other failover candidate.
As I understand the behavior will change only in case when reply status will be changed in the reply route (to or from 503 in default). So only in case when we want to try or visa-versa don't want to try other candidates, but again we don't know anything about candidates.
This changes were done more than year ago and already works on few thousands installations without any problems (but only with new behavior).

Please let me know if any additional checks can be done from my side.

**Comment by henningw** [comment]
Thank you for providing the update. Right now there seems to be some conflicts probably after some refactoring changes that have been done. Could you maybe re-base your changes and then developers could have another close look.

**Comment by vlitvinov** [comment]
Hello. Thank you for your reply. Re-based.

**Pull request closed without merging**
