### PR TITLE
NATS: add new function `nats_publish()`

### PR DESCRIPTION
**Pull request by eschmidbauer**
#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Adds Publish function to NATS module.

### CODE REVIEW

**Review by miconda — APPROVED** [review]

**Comment by miconda** [comment]
Fine to merge it from my point of view, only one comment as I noticed in the makefile it needs both libuv and libevent. I thought they are alternative for each other, not expecting to be needed at the same time, but maybe they are required in this manner because of dependencies.

**Comment by smititelu** [comment]
I've basically tested this PR locally and works good. Nice work!

Thanks,
Stefan

**Comment by eschmidbauer** [comment]
> Fine to merge it from my point of view, only one comment as I noticed in the makefile it needs both libuv and libevent. I thought they are alternative for each other, not expecting to be needed at the same time, but maybe they are required in this manner because of dependencies.

@miconda thank you for the feedback. I agree with you, we should probably not use two different eventing libraries. 
I will work on switching to libuv for the publish worker and submit a new PR.

**Comment by eschmidbauer** [comment]
@miconda @smititelu 
I've updated this PR to use libuv _only_ and added parameter `num_publish_workers` which allows you to have N number of publish workers. Thanks!

**Comment by miconda** [comment]
@eschmidbauer - fine to merge from my point of view.

**Pull request merged**
