### PR TITLE
core: allow empty matches

### PR DESCRIPTION
**Pull request by btriller**
Anchors like ^ and $ match beginning resp. ending of strings but their
matches are zero length, which is ok.
The anchors can be used to pre-/append a prefix/suffix via e.g.
subst_hf("X-My-Header", "/^/prefix /", "a");
subst_hf("X-My-Header", "/$/ suffix/", "a");

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
Patch is small, but I wonder what side effects it can bring to existing configs, this behaviour likely is there for almost 2 decades. Maybe a global param can be added to control it. Any other opinions?

**Comment by henningw** [comment]
Yes, i also think it should be probably configurable, and probably default deactivated. If there is another way of achieving this (for example in the textops module, maybe this is an even better way instead of adding another core parameter and code path.

**Comment by miconda** [comment]
@btriller - looking again at this one, wouldn't it be the same to do:

```
subst_hf("X-My-Header", "/^(.+)$/prefix \1/", "a");
subst_hf("X-My-Header", "/^(.+)$/\1 suffix/", "a");
```

instead of:

```
subst_hf("X-My-Header", "/^/prefix /", "a");
subst_hf("X-My-Header", "/$/ suffix/", "a");
```

**Comment by miconda** [comment]
And as another idea, maybe adding new functions like suffix_hf()/prefix_hf() would be even better, not to rely on regex matching for these basic operation.

**Comment by btriller** [comment]
> @btriller - looking again at this one, wouldn't it be the same to do:
> 
> ```
> subst_hf("X-My-Header", "/^(.+)$/prefix \1/", "a");
> subst_hf("X-My-Header", "/^(.+)$/\1 suffix/", "a");
> ```
> 
> instead of:
> 
> ```
> subst_hf("X-My-Header", "/^/prefix /", "a");
> subst_hf("X-My-Header", "/$/ suffix/", "a");
> ```

Knowing that
```
% echo blub|sed 's/^/prefix /'
prefix blub
% echo blub|sed 's/$/ suffix/'
blub suffix
```
works, it felt weird to write
```
subst_hf("X-My-Header", "/^(.)/prefix \1/", "a");
subst_hf("X-My-Header", "/(.)$/\1 suffix/", "a");
```
As most of the time, there are other ways to do it (above suggested or `remove_hf()`, looping over all headers and `append_hf()`).
I understand the concerns, so I don't mind if the PR is closed.

**Comment by miconda** [comment]
Closing it then, in this form it changes how it used to work so far.

You can propose another PR that makes this new behaviour configurable or adds new functions to offer the functionality.

**Pull request closed without merging**
