### PR TITLE
Modules:xmlrpc event_callback added for ksr routes

### PR DESCRIPTION
**Pull request by surendratiwari3**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Rightnow, There is no event_callback for xmlrpc in ksr. This PR helps to define the event_callback for ksr routes. once we will get the xmlrpc then if event_callback is defined then defined ksr routes get executed. default functionality will work as it is.

### CODE REVIEW

**Comment by miconda** [comment]
You have to add docs for the new parameter in the xml file from the doc subfolder. It can be a new commit pushed in the same branch/pull request.

**Comment by surendratiwari3** [comment]
@miconda sure. doing it now.

**Comment by surendratiwari3** [comment]
@miconda its done now.:-) thank you for pointing it out.

**Comment by miconda** [comment]
The example in the docs uses some modules that are not exported by kamailio, like `headers` and `core`. You have to update it to use what is exported via `KSR`.

**Comment by surendratiwari3** [comment]
@miconda Agree. 👍

**Comment by surendratiwari3** [comment]
@miconda please let me know if something more to do with this pull request.

**Comment by miconda** [comment]
Thanks! Merged manually.

**Pull request closed without merging**
