### PR TITLE
exec: docs - added security warning

### PR DESCRIPTION
**Pull request by sandrogauci**
- Added warning about potential for OS Command Injection
- Updated invalid examples

previous example gives the following error:
pv_parse_spec2(): error searching pvar "rU.txt"

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Misuse of the exec module functions is a security concern. This PR updates the documentation to help Kamailio administrators use these functions securely.

### CODE REVIEW

**Review by oej — APPROVED** [review]

**Comment by miconda** [comment]
Thanks!

**Comment by Jonnypleasehelp** [comment]
Thanks for your help

**Review by Jonnypleasehelp — COMMENTED** [review]
Thanks

**Comment by Jonnypleasehelp** [comment]
Yes I understand I don't really know what I am doing it's an expert task so I have decided on the paid option which will be great. This has troubles me for 4 years dating from 31/04/2018. Its maid my life hell and I have become Ill with trying to stay in control.  Thank you so much you are wonderful. Xx

**Review by Jonnypleasehelp — COMMENTED** [review]
Yes I am learning as we go along it's all new language for me

**Pull request merged**
