### PR TITLE
topos: remove contact header for CANCEL,BYE,PRACK REQUESTS

### PR DESCRIPTION
**Pull request by emvondo**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

According to RFC 3261 & 3262 CANCEL , PRACK and BYE requests and their associated responses (most of them) must not have contact header

### CODE REVIEW

**Comment by miconda** [comment]
Thanks for the PR!

I couldn't find an explicit statement about CANCEL and Contact header in the RFC, I haven't searched much, though. IBM site claims it is a SHOULD NOT:

  - https://www.ibm.com/support/pages/apar/PM77734

I will think how this could be added with some flexibility around it.

**Comment by henningw** [comment]
@miconda I think this is the relevant table in section 20 [link](https://datatracker.ietf.org/doc/html/rfc3261#section-20)

Seems to be pretty clear, if I read it correctly.

```
      -: The header field is not applicable.

   "Not applicable" means that the header
   field MUST NOT be present in a request.  If one is placed in a
   request by mistake, it MUST be ignored by the UAS receiving the
   request.  Similarly, a header field labeled "not applicable" for a
   response means that the UAS MUST NOT place the header field in the
   response, and the UAC MUST ignore the header field in the response.
```

```
      Header field          where   proxy ACK BYE CAN INV OPT REG
      ___________________________________________________________
      Contact                 R            o   -   -   m   o   o
      Contact                1xx           -   -   -   o   -   -
      Contact                2xx           -   -   -   m   o   o
      Contact                3xx      d    -   o   -   o   o   o
      Contact                485           -   o   -   o   o   o
```

**Comment by miconda** [comment]
@henningw: ok -- I made it configurable just in case other methods have same requirements, or one needs the old behaviour for whatever reason.

At the end it didn't break the behaviour due to the must ignore statement:

```
   If one is placed in a
   request by mistake, it MUST be ignored by the UAS receiving the
   request.
```

Closing this one.

**Comment by henningw** [comment]
Thanks, great solution.

**Pull request closed without merging**
