### PR TITLE
Refactor cdp log

### PR DESCRIPTION
**Pull request by fedefava86**
This is a complete refactor of cdp log. In particular:

- It removes escape chars for colors in log: they are most of the times not interpreted so they are messing up the logs

- It refactors some log level, moving to ERROR from WARN some errors during peer connections

- In DEBUG level, cdp is too much verbose and also syslogs complains about rate-limiting. Instead of removing some logs (which is quite unfair), let's introduce a new modparam (debug_heavy) in order to activate some logs which gives some side informations about peers status. This modparam is not active by default but this can be enabled easily re-introducing previous debug logs

### CODE REVIEW

**Comment by miconda** [comment]
The patch cc68bea adds a new parameter for the module -- you have to add documentation for it in the files from doc/ subfolder of the module.

**Comment by fedefava86** [comment]
@miconda You are right. Completely agree with you. Done.

**Comment by miconda** [comment]
Thanks, I am going to merge it.

On the other hand, if you want to clean a bit more the log messages, you can remove the name of the function from the log message, because now it is added automatically.

For example:

```
LM_INFO("peer_connect(): Trying to connect t...
```

should become:

```
LM_INFO("Trying to connect t...
```

**Comment by fedefava86** [comment]
Ok @miconda , thanks for the hint. I will do it as soon as possible

**Pull request merged**
