### PR TITLE
registrar: fix xavp_rcd memory consumption

### PR DESCRIPTION
**Pull request by lazedo**
xavp_rcd keeps accumulating values leading to shm exaustion

### CODE REVIEW

**Comment by miconda** [comment]
Are not the xavps deleted automatically when the processing of the request is finished? There should not be an explicit delete from the modules, unless strictly necessary for functionality of some feature, but the xavps and avps should not leak when processing normal SIP traffic.

Or are you using them in some event routes?

**Comment by lazedo** [comment]
@miconda it seems so, maybe the problem lies in the delete ? i'm using in script to create a json with the `ruid` and memory is always growing. removing just these parts, memory is back to normal.

```
modparam("registrar", "xavp_rcd", "ulrcd")
...
after successful save
$var(amqp_payload_request) = $_s({"Event-Category" : "directory", ..., "RUID" : "$xavp(ulrcd=>ruid)", ... });
....
```

**Comment by miconda** [comment]
Which memory is growing? SHM, PKG or system memory?

**Comment by lazedo** [comment]
shared memory tracked by
[root@dev-01 kamailio]# kamcmd mod.stats core shm
Module: core
{
*xavp_new_value(94): 4808*
}

only one client registering every 60 sec

**Comment by miconda** [comment]
Can you attach log messages with debug=3 for a registration request?

**Comment by lazedo** [comment]
[kamailio.log.gz](https://github.com/kamailio/kamailio/files/973067/kamailio.log.gz)
used gzip

**Comment by lazedo** [comment]
Hi Daniel,
i isolated all the requests and made sure only registration was being processed.
turns out that the problem must be elsewhere as the memory is now stable.
however, the first registration uses a suspend/continue and in this case the xavp memory is not released.

[kam.log.gz](https://github.com/kamailio/kamailio/files/986341/kam.log.gz)

**Comment by lazedo** [comment]
@miconda sorry, wrong report. the patch was applied, that's why memory is stable. initial registration issues still occurs (xavp not released after t_continue() )

**Comment by lazedo** [comment]
@miconda this is the log without the patch applied.

[kam.log.gz](https://github.com/kamailio/kamailio/files/986380/kam.log.gz)

**Comment by miconda** [comment]
Back on this after Kamailio World event -- so the issue is exposed when t_suspend()/t_continue() is used for REGISTER requests? Are you using these functions in kamailio.cfg or is via kazoo module?

**Comment by lazedo** [comment]
@miconda Hi Daniel, kazoo module does the suspend/continue, but this is only for the initial registration. the 2nd registration doesn't go thru suspend/resume but we're also getting memory leaks here.

**Comment by miconda** [comment]
If there is no suspend/continue, then the issue can be that the registrar module doesn't add the xavp to core list, being left unliked, otherwise the xavps (as well as avps) are destroyed at the end of executing request_route. This would have been revealed so far if there is an issue with overall avps/xavps management.

**Comment by miconda** [comment]
Btw, what version you are using in this case? 5.0 or 4.4?

**Comment by miconda** [comment]
While looking at the t_continue() I discovered that it may overwrite a previous set faked environment, which can happen if the function is used in failure_route, as a result xavps/avps lists can be lost without being freed. With the commit 9ff4dd36ad63f60905a49f8c0e437f997e54ae70, this situation should be solved.

I am not sure this is solving your case, but it would be good if you test with this patch.

I am also going to look at the registrar module to see if I spot something wrong there. Deleting the xavps in the module as proposed by this pull request is not the proper solution, it may be a workaround for some specific case, but not fixing the real cause.

**Comment by lazedo** [comment]
using master (with your latest commits). tried the referenced commit but still have memory leak for 1st request (suspend/continue). the xavp is being created after continue (registrar reply) , it seems receive_msg cleanup is not reached (or is early reached due to suspend) in this case ?
and i agree this is not the recommended fix, its only hiding possible issues.
also, i applied the patch only to reply.c in registrar and it fixes re-register.

**Comment by miconda** [comment]
Is this with the standard kazoo platform kamailio.cfg? Can you point me to the repo with the config at the line where the xavp is created? I may help seeing the config and understanding the use case.

**Comment by lazedo** [comment]
https://github.com/2600hz/kazoo-configs/blob/master/kamailio/registrar-role.cfg

the xavp is not created in the script.
its created by registrar build_contact (reply.c) all cases or 
registrar registered4 (lookup.c) that calls xavp_rcd_helper.

check route `ATTEMPT_AUTHORIZATION`

for re-register, this line https://github.com/2600hz/kazoo-configs/blob/master/kamailio/registrar-role.cfg#L120 check if the device is already registered and skips to save location (no suspend/continue), leak seems to occur in registrar build_contact (reply.c).

**Comment by lazedo** [comment]
@miconda about the first registration...

the `continue` executes in pid `6518` and it never calls `xavp_reset_list()`
registrar:build_contact (reply.c) is executed in this pid

```
 2(6487) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|start|received udp request REGISTER sip:teste.sip.90e9.com
 2(6487) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|source 192.168.16.12:50133 -> 192.168.16.125:8000
 2(6487) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|from sip:user_7z7b6s@teste.sip.90e9.com
 2(6487) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|to sip:user_7z7b6s@teste.sip.90e9.com
 2(6487) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|originated from external sources
 2(6487) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|correcting NATed contact in registration
 2(6487) INFO: <core> [core/xavp.c:461]: xavp_reset_list(): RESET XAVP
32(6517) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|authenticating user_7z7b6s@teste.sip.90e9.com via Kazoo query response
32(6517) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|end|issued auth challenge to failed registration attempt for user_7z7b6s@teste.sip.90e9.com 192.168.16.12:50133
 3(6488) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|start|received udp request REGISTER sip:teste.sip.90e9.com
 3(6488) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|source 192.168.16.12:50133 -> 192.168.16.125:8000
 3(6488) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|from sip:user_7z7b6s@teste.sip.90e9.com
 3(6488) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|to sip:user_7z7b6s@teste.sip.90e9.com
 3(6488) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|originated from external sources
 3(6488) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|correcting NATed contact in registration
 3(6488) INFO: <core> [core/xavp.c:461]: xavp_reset_list(): RESET XAVP
33(6518) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|authenticating user_7z7b6s@teste.sip.90e9.com via Kazoo query response
33(6518) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|log|caching sip credentials for user_7z7b6s@teste.sip.90e9.com
33(6518) INFO: <script>: 79956NjgwZTVmOTQ5Zjc0MjcxMTVjYjNlOTMxNGI5NDkwYjk|end|successful registered with contact uloc-5919b147-941-1 : <sip:user_7z7b6s@192.168.16.12:50133;rinstance=f24eba8fb96940a0>;+sip.instance="<urn:uuid:50e56137-edf1-5c8c-99ab-f5ebf869e00f>";reg-id=1
 6(6491) INFO: <core> [core/xavp.c:461]: xavp_reset_list(): RESET XAVP
 6(6491) INFO: <core> [core/xavp.c:461]: xavp_reset_list(): RESET XAVP
 8(6493) INFO: <core> [core/xavp.c:461]: xavp_reset_list(): RESET XAVP
 8(6493) INFO: <core> [core/xavp.c:461]: xavp_reset_list(): RESET XAVP
```

**Comment by miconda** [comment]
In this case there should be a REGISTER transaction and the xavps should be linked to the transaction structure and destroyed when the transaction is cleaned up.

**Comment by lazedo** [comment]
@miconda more info

it seems that the `faked_env( t, 0, 1);` call (restore original environent) will discard the avps xavps that can be added during processing of the script block. in this use case,  registrar save (which calls reply) is called, which creates the xavps that are not being released.

from t_suspend.c
```
		faked_env( t, faked_req, 1);

		route_type_bk = get_route_type();
		set_route_type(FAILURE_ROUTE);
		/* execute the pre/post -script callbacks based on original route block */
		if (exec_pre_script_cb(faked_req, cb_type)>0) {
			if (run_top_route(route, faked_req, 0)<0)
				LM_ERR("failure inside run_top_route\n");
			exec_post_script_cb(faked_req, cb_type);
		}
		set_route_type(route_type_bk);

		/* TODO: save_msg_lumps should clone the lumps to shm mem */

		/* restore original environment */
		faked_env( t, 0, 1);
```

**Comment by miconda** [comment]
Not really -- during the execution of the route block, the x/avp lists from tm are set in the core, so the new x/avps are stored directly in the transaction. This is used for failure_route as well and any issue should have been exposed for long time. Unless it was the case of creating a faked env inside a faked env that should be fixed by my last commit.

I looked at the kazoo code and I noticed that `kz_amqp_consumer_fire_event()` is using fake sip messages to execute event routes. Are those event routes creating xavps?

**Comment by miconda** [comment]
Anyhow, you can try to execute `xavp_reset_list()` inside kazoo module after t_continue(), and see if  it gets fixed. Then we know where to dig more.

**Comment by lazedo** [comment]
@miconda i reverted every change and added `xavp_reset_list()` after `t_continue()` in kazoo andalso after `kz_amqp_consumer_fire_event()` and leak continues.
is there a way to lookup the memory allocated values to make sure it is coming from where we think it is ?

**Comment by miconda** [comment]
Yes. Start kamailio and do some operations so you expose the leak.

Do a shm status dump:

  * http://www.kamailio.org/docs/modules/5.1.x/modules/corex.html#corex.rpc.shm_status

Then you get details of each allocated chunks -- two pointers

  * start of the memory chunk
  * start of the data inside the memory chunk

With gdb attach to any of the kamailio processes and print the content of the data pointer casted to xavp structure. Do it for several pointers so you see what is inside.

**Comment by lazedo** [comment]
@miconda thanks for the info.
after digging more , i think the issue is not related to `kazoo`. can you try the below script (note that kazoo is not used) ? also maybe fake a transaction to a external auth and set the `$xavp(ulattrs=>extra_info)` on the `continue`block ?
with this configuration, the 1st registration doesn't leak but the re-registrations do leak.

```
...
modparam("usrloc", "xavp_contact", "ulattrs")
modparam("registrar", "xavp_rcd", "ulrcd")
modparam("registrar", "xavp_cfg", "regcfg")
modparam("htable", "htable", "auth_cache=>size=16;autoexpire=7200;")
...

route[REGISTRAR]
{

    $xavp(regcfg=>match_received) = $su;
    if($sht(auth_cache=>$Au) != $null && registered("location", "$rz:$Au", 2, 1) == 1) {
        xlog("L_INFO", "$ci|register|found cached registration for $rz:$Au\n");
            $var(password) = $sht(auth_cache=>$Au);
            route(SAVE_LOCATION);
    }

    if( !is_present_hf("Authorization")) {
        auth_challenge("$fd", "0");
        exit();
    }
    
    $xavp(ulattrs=>extra_info) = '{"test" : true}';
    
    route(SAVE_LOCATION);

}

route[SAVE_LOCATION]
{

    if ($sht(auth_cache=>$Au) == $null) {
        xlog("L_INFO", "$ci|log|caching sip credentials for $Au\n");
    };
    $sht(auth_cache=>$Au) = $var(password);
    $var(save_result) = save("location", "0x04");
    if($var(save_result) == -1) {
        auth_challenge("$fd", "0");
        xlog("L_INFO", "$ci|end|issued auth challenge after failed attempt to save contact for $Au $si:$sp\n");
        exit;
    } else {
        if($var(save_result) == 1) {
            $var(new_reg) = "true";
        } else {
           $var(new_reg) = "false";
        }
    }
    xlog("L_INFO", "$ci|end|save result $var(save_result) with contact $xavp(ulrcd=>ruid) : $ct\n");
}
```

**Comment by lazedo** [comment]
@miconda i think i found it. no leaks on both 1st and 2nd registrations

**Comment by lazedo** [comment]
@miconda so 1st registrations are ok.   i was testing with db_mode = `Write-Through` (sorry about that). with for db_mode = `db_only`, all xavps are cleared after route (with async resume).

**Comment by miconda** [comment]
To summarize: all ok now with patch 3fddccd ?

Was the problem that some xavps were not linked to the root list from the core?

**Comment by lazedo** [comment]
@miconda Hi, yes, all ok with https://github.com/kamailio/kamailio/commit/3fddccd0d7a3f9662699f88d1a9a708e1c1b24bc . the problem was how we obtained the existing `xavp's` and adding new values. this part `xavp = list ? &list->val.v.xavp : &new_xavp;` did the trick, we were adding values to xavp list and not to reg_xavp_rcd xavp.

**Comment by miconda** [comment]
But even when adding to xavp list, they should be freed. Do you still have the xavp_reset_list() in kazoo module?

**Comment by lazedo** [comment]
i didn't used kazoo for testing, but i will be adding a xavp_reset_list() to event processing (not critical).
test with this script with/without the patch.
have sip client re-register every 30 and you'll see `shm` memory consumption growing (`xavp_new_value`)
```
...
modparam("usrloc", "xavp_contact", "ulattrs")
modparam("registrar", "xavp_rcd", "ulrcd")
modparam("registrar", "xavp_cfg", "regcfg")
modparam("htable", "htable", "auth_cache=>size=16;autoexpire=7200;")
modparam("async", "workers", 2)

...

route
{
...
    if (is_method("REGISTER")) {
        route(REGISTRAR);
        exit();
    }

...
}

route[REGISTRAR]
{
    $xavp(regcfg=>match_received) = $su;
    if($sht(auth_cache=>$Au) != $null && registered("location", "$rz:$Au", 2, 1) == 1) {
        xlog("L_INFO", "$ci|register|found cached registration for $rz:$Au\n");
            $var(password) = $sht(auth_cache=>$Au);
            route(SAVE_LOCATION);
    }

    if( !is_present_hf("Authorization")) {
        auth_challenge("$fd", "0");
        exit();
    }
    
    async_route("MY_RESUME", "1");    

}

route[MY_RESUME]
{
    $xavp(ulattrs=>channel_vars) = '{"channel-vars" : true}';
    $xavp(ulattrs=>other_vars) = '{"other-vars" : false}';
    route(SAVE_LOCATION);
}

route[SAVE_LOCATION]
{
    if ($sht(auth_cache=>$Au) == $null) {
        xlog("L_INFO", "$ci|log|caching sip credentials for $Au\n");
    };
    $sht(auth_cache=>$Au) = $var(password);
    $var(save_result) = save("location", "0x04");
    if($var(save_result) == -1) {
        auth_challenge("$fd", "0");
        xlog("L_INFO", "$ci|end|issued auth challenge after failed attempt to save contact for $Au $si:$sp\n");
        exit;
    } else {
        if($var(save_result) == 1) {
            $var(new_reg) = "true";
        } else {
           $var(new_reg) = "false";
        }
    }
   xlog("L_INFO", "$ci|end|ulattrs $xavp(ulattrs=>channel_vars) , $xavp(ulattrs=>other_vars)\n");
    xlog("L_INFO", "$ci|end|save result $var(save_result) with with expires ($xavp(ulrcd=>expires)) contact $xavp(ulrcd=>ruid) : $ct\n");
}
```

**Comment by miconda** [comment]
Pushed the patch split in two, as the expires part might not be needed to be backported for older releases.

If you tested and are confident in the results, then you can push any of the patches in stable branches.

**Comment by lazedo** [comment]
@miconda Thanks Daniel. i've asked for more people to confirm the fix and i'm also deploying this to our sandbox environment. will cherry-pick the 1st to 4.4/5.0 and the 2nd to 5.0 if all goes well. so far my environment is stable.

**Comment by lazedo** [comment]
@miconda i cherry-picked the 2 commits to 5.0 branch and the first to 4.4 branch.

**Pull request closed without merging**
