### PR TITLE
Add Initial CMake support 

### PR DESCRIPTION
**Pull request by xkaraman**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

This PR adds initial support for building kamailio with CMake.

See [docs](https://github.com/kamailio/kamailio-wiki/pull/63) for more information on how to build and use CMake.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks a lot for your work with the cmake support!

@xkaraman and @adubovikov did also testing of cmake branch during devel meeting in Dusseldorf, this PR should be in good shape to merge rather quick in order to allow time for everyone to test their compile options before freezing. Of course, even after freezing there can be changes to the build system, but it would be good to know by freezing time if we can go with cmake only further.

The old Makefiles can co-exist with the new cmake-based build system for a while, but if cmake one proves to be ready enough before freezing, I would propose to remove the old Makefiles, they got too complex over the past 20 years...

If no comments against till Monday afternoon or soo, I think this PR can be merged.

**Comment by henningw** [comment]
Great work Xenofon, thank you. Indeed we should aim to merge it soon, to also allow different developers to test it more.
Related to the process of merging it, we probably should squash it everything together to one commit, as it contains are over 60 commits, right? Some of the initial commits are using also a different commit message format, no prefix.

**Comment by miconda** [comment]
Fine for me to squash and merge, there are only new files, so it should not interfere with backports.

**Comment by xkaraman** [comment]
Some modules `CMakelists.txt` have `TODO: ` comments, which should initiate discussion regarding deprecated libraries used. A review of those would be also a good addition I think!

**Comment by xkaraman** [comment]
> Fine for me to squash and merge, there are only new files, so it should not interfere with backports.

There are some edited files like `forward.h` and `resolve.c` where I added some variables need to compile or some logic handling macro feature definitions for example. 

i can probably remove those changes and create a separate PR for fixing since they are not cmake-related

**Pull request merged**
