### PR TITLE
Fix issue 3929 sip_p_charging_vector destroys SIP message

### PR DESCRIPTION
**Pull request by lachbaer**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #3929

#### Description
The handling of the buffer and pointers in the siputils/chargingvector.c module was inconsistent and led to writing directly in the sip msg buffer, which resulted in the destruction of the SIP message as reported in the issue. During the testing more cases showed up where the PCV handling became ugly and inconsistent, especially in fault scenarios. Therefore more parts have been rewritten to account for those scenarios.

The $pcv(status) pseudo-variable has been added to reflect the state of the P-Charging-Vector in the message, whether it was parsed, had errors (no body or no icid-value), has been deleted or if none is there.

The sip_p_charging_vector() function returns a status value of what it has done, or if it was a no-op call.

A present PCV can only be generated once by the module, either after an explicit deletion or by a forced replacement. After that the call returns with no-op.

### CODE REVIEW

**Comment by linuxmaniac** [comment]
@lachbaer you have to fix the format on the commits. The check is commit by commit.

**Comment by lachbaer** [comment]
@linuxmaniac Thank you for the hint. I have updated the commits.

**Comment by lachbaer** [comment]
Can someone start the checks again, please? Thank you.

**Comment by linuxmaniac** [comment]
@lachbaer the problem is that the last commit has ``[skip ci]`` so the checks are skipped. 
Can you, please, rebase and move that documentation commit behind the other one so the last commit message of the PR has no ``[skip ci]`` in it?

**Comment by linuxmaniac** [comment]
please update https://github.com/kamailio/kamailio-wiki/blob/main/docs/features/new-in-devel.md with the new behavior

**Comment by lachbaer** [comment]
new-in-devel.md updated kamailio/kamailio-wiki#60

**Pull request merged**
