### PR TITLE
ims_qos: doc update and warn logs

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Primary goal is to update doc, for Rx_AAR() function, to mention is used only for replies.

I've also changed some LM_DBG to LM_WARN but I can revert that on request (don't want to overflow noone with warnings)

### CODE REVIEW

**Comment by smititelu** [comment]
@carstenbock what do you think of this?

**Review by miconda — COMMENTED** [review]
Removing the condition `if(msg->first_line.type != SIP_REPLY) {` seems legit from native kamailio.cfg scripting language as the exports limits to ONREPLY_ROUTE and the internal interpreter can detect it, but for KEMI (which might not be the case here, however, making it as a general comment), it is not possible to detect at startup where a function is going to used. Therefore, thinking of thee future, it is probably better to have runtime checks about the type of message or route block. Even for the native scripting language, there are workarounds in some cases to execute a function in another route block (e.g., execute request-specific exported functions inside a `route[x]` block that is called from on/reply route block.

From that perspective, I would not remove this check. Over all, I am fine to merge it with this change as well. Nowadays the config writer should be more careful anyhow, especially if using KEMI, to be sure functions are not used in a wrong place.

**Comment by smititelu** [comment]
Thanks for the feedback! Will update PR soon. Did not know about the ```route[x]``` stuff.

**Comment by carstenbock** [comment]
@smititelu : Looks good to me, sorry was on holiday in the last two weeks.... :-)

**Pull request merged**
