### PR TITLE
Aliasdb

### PR DESCRIPTION
**Pull request by khoegh**
I've backported some features from opensips.
- reverse alias lookup function flag
- use_domain moved from global parameter to a function flag (defaults to yes)
- New function alias_db_find uses source and destination PV instead of ruri

### CODE REVIEW

**Comment by miconda** [comment]
I would like to discuss more about the removal of use_domain parameter. It is a common parameter name across many modules and it is a easy way to turn on/off multi-domain support (even done also for alias_db in default kamailio.cfg).

I would like a coherent solution, like either removing this mod param everywhere or still keep it and also allow the per-function option to enable/disable.

Moreover, changing the default in using the domain is going to break compatibility may result in unexpected behaviour without prior visible notice, as people can reuse an old config without use_domain parameter set, so no error is triggered, but behaviour is changed. So I think the default should be without domain (this is the default across kamailio modules) and a flag to enable domain based lookup.

Keeping the use_domain won't change much the patch, the flags need to be initialized based on it:

```
if(use_domain) {
  flags |= **domain_lookup_flag**
}
```

Travis reports that the inter-module API was broken -- app_lua doesn't compile as the function prototype for alias db lookup was changed. This is an easy fix, I can take care of.

**Comment by khoegh** [comment]
Thanks, I will add use_domain again after the weekend.

**Comment by khoegh** [comment]
I re-added use_domain module parameter and added option "u" to use domain on alias_db_lookup/alias_db_find.
Will you fix the API, thanks.

**Comment by miconda** [comment]
I pushed the commit that combines this pull requests with some refactoring of the internals not to break the inter-module api as well as use straight flag meaning for domain lookup, instead of negative meaning.

It should not affect use from config, but testing would be good to do to be sure.

**Comment by khoegh** [comment]
I did some testing and it seems to work as expected.
Thanks.

**Pull request closed without merging**
