### PR TITLE
dispatcher: Fix handling of inactive destination for alg 13

### PR DESCRIPTION
**Pull request by mtryfoss**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Alg 13 did try to distribute calls to inactive destinations.
If the highest priority destination is inactive, hash is not updated
and the xavp is not set. This is resulting in failover mechanism
not working at all for the given call.

When the hash variable is not updated, it makes alg 13 behave like
round robin if the scenario above occurs. If you got two destinations
and the highest priority is out of service, 50% of the calls will fail.

Now I tried a more simple approach updating hash with the first
entry of the sorted list.

Also fixed a typo in a variable name.

### CODE REVIEW

**Comment by miconda** [comment]
@jchavanton - any comments on this PR?

**Comment by mtryfoss** [comment]
Please notice, we use this with latency stats disabled. Just a way of having distribution with round robin within each priority for more than two destinations.

For example, in normal operation use round robin against two destinations and a third as failover if both the two first goes offline.

**Comment by miconda** [comment]
@mtryfoss - have you checked ds_select_routes(), isn't it more suitable for what you need?

**Comment by mtryfoss** [comment]
It seems like that's more of a thing to combine multiple dispatcher sets using potentially different algos?
That could be useful in some other scenarios, but in the current setup this is working perfectly with the applied patch.

My point here is that algo 13 seems to be broken (failover does not work) if the first selected (highest priority) destination is marked as inactive. The xavp var is not set. 

While it's being probed but not yet inactive, the call distribution will time out - but the xavp will be set and the on failure logic can trigger as expected.

**Comment by miconda** [comment]
I am not using that algorithm, so I have no experience with expected behaviour. If @jchavanton has no comments soon, probably will be merged, I see it affects only code specific to the algorithm.

**Pull request merged**
