### PR TITLE
Add async insert support

### PR DESCRIPTION
**Pull request by UserAd**
Add asynchronous support for sipcapture module

### CODE REVIEW

**Comment by adubovikov** [comment]
HI, 
thanks for your patch, but can you please recreate it ?  I see a lot diffs for tabs and \r\n, therefore very hard to read it and find changes.

thank you again.

regards,
Alexandr

**Comment by miconda** [comment]
Re-formatting the code and/or indentation has to be a separate patch.

When the patch is recreated, follow the guidelines for commit message presented at:

  * http://www.kamailio.org/wiki/devel/github-contributions#commit_message_format

**Comment by UserAd** [comment]
So, i need to make new pull request with last commit?

**Comment by adubovikov** [comment]
yes please

**Pull request closed without merging**
