### PR TITLE
jansson: Add en-/decode to/from xavp

### PR DESCRIPTION
**Pull request by gaaf**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Add functions to encode and decode JSON from/to an xavp

### CODE REVIEW

**Comment by kamailio-sync** [comment]
Now that is a very useful contribution! Thank you!

—

**Comment by gaaf** [comment]
On maandag 19 oktober 2020 15:39:30 CEST kamailio-sync wrote:
> Now that is a very useful contribution! Thank you!
> 
> —
> Sent from mobile, with due apologies for brevity and errors.

A little too brief. Who are you?
-- 
mvg,

Alex Hermann

**Comment by henningw** [comment]
The kamailio-sync will suppress the author (Alex B. in this case). You find the full reply on sr-dev.

**Comment by miconda** [comment]
Thanks, merging it.

**Pull request merged**
