### PR TITLE
cdp: Add SCTP support

### PR DESCRIPTION
**Pull request by networkmaniac**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Added SCTP support for CDP module

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the PR, looks good to me. Lets see if there are other comments, otherwise it will be merged soon.

**Comment by miconda** [comment]
Fine to merge.

Not much acting myself in IMS modules space, but maybe for more flexibility, as a follow up commit, the comparison with `SCTP` can be done case insensitive, to allow both `sctp` or `SCTP` in the xml config. This because I noticed something similar for a node name:

  - https://github.com/kamailio/kamailio/pull/3327/commits/72801e2bc6fddd56c4ab0c8afe29dbbe8052a57a#diff-50800cc9898915b16d6e39bf34c12b94d043f895a5b4ea91d676572fd1283fa5L339

**Comment by networkmaniac** [comment]
Thanks for you opinion. Changed to case insensitive.

**Comment by henningw** [comment]
thanks, merged

**Pull request merged**
