### PR TITLE
RPM spec update

### PR DESCRIPTION
**Pull request by sergey-safarov**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Required backport to `5.2` branch.

### CODE REVIEW

**Comment by sergey-safarov** [comment]
Could you also backport https://github.com/kamailio/kamailio/pull/1711 into `5.2` branch.

**Comment by henningw** [comment]
Backport of the three commits in 5.2 done.

**Comment by sergey-safarov** [comment]
@henningw this two commits also need on `5.2` branch.
Reference to #1711 is made to prevent merge conflict on cherry-pick.

**Comment by miconda** [comment]
I am going to merge and also grant you commit access, so you can commit to the RPM specs directly and backport as needed (you can still do pull request if you want others to review -- for commits to other parts than RPM specs, keep doing pull requests so the main developer for that part has a chance to review).

**Comment by sergey-safarov** [comment]
Thanks Daniel @miconda 
Understand. Sure i will use commit permission only for rpm/alpine/docker packaging.

**Pull request merged**
