### PR TITLE
dispatcher: add option to retain existing latency stats when reloading destinations

### PR DESCRIPTION
**Pull request by charlesrchance**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Added new module param to enable retention of call stats for existing destinations when reloading the list from file or database.

Also updated to retain stats for other destinations when adding/removing individual ones via RPC.

### CODE REVIEW

**Comment by charlesrchance** [comment]
Thanks!

I agree...happy to make it the default if others think the same, but we never quite know how it's already being used and who relies on a reload to actually reset the stats.

**Comment by miconda** [comment]
Fine to merge from my point of view, if no other comments.

**Comment by henningw** [comment]
I have no strong opinion on the question regarding the default value. Merging it, thank you. If somebody thinks that it should be configured differently w/r to the default value, it can be changed later as well.

**Comment by charlesrchance** [comment]
Thanks @henningw!

**Pull request merged**
