### PR TITLE
Lost selectors

### PR DESCRIPTION
**Pull request by sergey-safarov**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

This is the selectors feature for `lost` module.
The module still in development but the core functionality is working.
 What need to do
1. separate feature into dedicated `.c` file;
2. rebase on current `lost` implementation;
3. add documentation;
4. add a unit test.

Would be fine if we can merge this into 5.5.

This branch based on e7d68556e3560f488c4f421731f78b3f9abe549e commit

For usage example please check the commit message.

### CODE REVIEW

**Comment by miconda** [comment]
First, you have to rebase and do fast-forward, because it looks like (re-)merging commits done earlier.

However, this PR seems to introduce new code and features, unrelated to fixing bugs in existing code or completing the features of specs. Being already within testing phase for 5.5, this PR should wait for master to be unfrozen, then merge, so it will be in 5.6.

**Comment by wkampich** [comment]
I am glad that the function of the `lost` module is extended. Just a small note:
- according to the latest version of NENA i3, the Call-Info header purpose changes from nena-xxx to emergency-xxx (e.g. nena-IncidentId will be replaced by emergency-IncidentId); perhaps this can already be taken into account.
- do we need a new release every time new selectors are needed? For instance in Europe we can have `purpose=EmergencyCallData.eCall.MSD` when NG eCall is rolled out. Refer to [RFC 8147](https://tools.ietf.org/html/rfc8147)

**Comment by sergey-safarov** [comment]
> according to the latest version of NENA i3, the Call-Info header purpose changes from nena-xxx to emergency-xxx (e.g. nena-IncidentId will be replaced by emergency-IncidentId); perhaps this can already be taken into account.

Think we need a write a function to convert headers to required format like
```
cast_nena_headers_prefix("nena-");
cast_nena_headers_prefix("emergency-");
```

> do we need a new release every time new selectors are needed? For instance in Europe we can have purpose=EmergencyCallData.eCall.MSD when NG eCall is rolled out.

RFC documents not changed rarely. I think we can add a selector for this RFC also like
```
@lost.emergency_call_data.ecall_msd;
```

**Comment by miconda** [comment]
Whenever this PR is ready to merge, it should be done with `Squash and Merge`, because some commits do not have the commit message formatted as per contributing guidelines.

**Comment by sergey-safarov** [comment]
yes, we expect several additional commits (docs, tests).
And then rebase + quash.

**Comment by henningw** [comment]
@sergey-safarov last update was some weeks ago, is there any update, e.g. its ready for review etc..?

**Comment by henningw** [comment]
@sergey-safarov last update was some months ago, is this still work in progress?

**Comment by sergey-safarov** [comment]
Hi Henning
Yes, this work in progress.
Dev is not available now.
Sorry, for so long delay.

**Comment by henningw** [comment]
@sergey-safarov any news? Just wanted to ask because the freeze date for the next kamailio version is upcoming.

**Comment by henningw** [comment]
@sergey-safarov any update from your side? Thank you.

**Comment by henningw** [comment]
@sergey-safarov the PR is still in draft status, not sure about the status. If it will be not completed for some reasons, just let us know.

**Pull request closed without merging**
