### PR TITLE
janssonrpcc: cleanups

### PR DESCRIPTION
**Pull request by gaaf**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Small cleanups

### CODE REVIEW

**Comment by henningw** [comment]
Sorry about the regression, the problem is that "str" is not supposed to be null terminated.
Its probably better to use "STR_VTOZ" instead of adding another str_dup implementation.

**Comment by miconda** [comment]
I would rather change pkg_str_dup() and shm_str_dup() to allocate len+1 and add the ending zero, right now there are not widely used and at the end is just adding an extra operation `newbuf->s[len] = '\0';`. IMO it will be better and safer in long term, as one can then use standard string operations with newbuf->s. For that reason, over the years the values for variables (like avp, xavp, ...) were made zero-terminated.

STR_VTOZ macro is useful when one knows that the string is stored inside a larger buffer, so temporarily setting an ending 0 doesn't go over allocated memory, otherwise can end up in segmentation fault.

**Comment by gaaf** [comment]
> I would rather change pkg_str_dup() and shm_str_dup() to allocate len+1 and add the ending zero

That was my first approach. I just thought it would provoke more discussion (see below) and I wanted to fix this bug fast, so I just kinda reverted the commits that introduced it.

The problem with adding a zero on every copy is that a ```str``` is supposed to be useful without a terminating zero. Lots of ```str``` uses are within the parser where ```str``` just points into the message buffer and has no terminating 0. Having them mixed will inevitable lead to bugs (just like the one I'm trying to fix). All developers will have to remember that only copies are 0-terminated.

Introducing a separate type for it (```strz```) will need duplicates for all existing str functions as C doesn't allow type inheritance.

Another option is to create ```pkg_str_dupz()``` and ```shm_str_dupz()``` which will 0-terminate the copies.

**Comment by miconda** [comment]
The `len` field will not include the 0, so copying such a cloned value will not be affected by ending 0. Besides the str fields that point in larger buffers (like with the sip parser fields that point inside msg->buf), most of the other str->s values are 0 terminating (e.g., most of pseudo-variables values, functions parameters evaluated by fixup_get_svalue(), ...). I am sure there are way more 0-terminated str->s fields than the non-0-terminated.

Again, here we discuss about cloning values, their result is not impacting anything else, they are supposed to be independent of other resources.

The rule is more like: do not rely on 0-terminated str->s value unless you are sure it is.

In this case it is made sure to be 0-terminated and used accordingly.

**Comment by miconda** [comment]
Thanks, I will squash and merge.

**Pull request merged**
