### PR TITLE
acc_radius : added radius time mode

### PR DESCRIPTION
**Pull request by ycaner06**
added radius time mode for new event-timestamp . Format is seconds.microseconds

### CODE REVIEW

**Comment by miconda** [comment]
Printing the float is not having any safety:

```
sprintf(smicrosec,"%f",tsecmicro);
```

Variable smicrosec has the size 18, I assume you wanted to have **10digits . 6digits**, but then enforce it because %f can have exponential representation, where the lenght can differ from system to system. Use:

```
sprintf(smicrosec,"%17.6f",tsecmicro);
```

Push this as an extra patch to your branch to show in pull request. Also, add the documentation and the PR will be merged.

**Comment by ycaner06** [comment]
Thanks Daniel. I will handle it.

**Comment by miconda** [comment]
You don't need to create a new complete path (pull request or branch) -- a second commit pushed in the same branch for this pull request will do it. Then you can have another patch to add the docs -- all will show up here if you reuse the same branch.

**Comment by ycaner06** [comment]
Really sorry Daniel. i spending your time this stuffs Because  I am rookie for C and GitHub.  i committed changes to patch-7.

**Comment by miconda** [comment]
Thanks. It will be merged.

**Pull request merged**
