### PR TITLE
Add some missing build requirements

### PR DESCRIPTION
**Pull request by guss77**
I'm building in Docker containers, and with the minimal CentOS/Fedora/whatever image you get from official repos, builds will fail without installing these.

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
Not having the commit first line as per contributing guide, I added those build requirements as part of commit 71248a2f7394b69c85f030f103afb2a8f6a5a49e, along with other changes.

If any issue introduced (eg., I added also pkgconfig which makes it easier to detect path to libs and include files), open an issue, or make a PR,  but follow the contributing guidelines so the PR can be merged from here using the web ui:

  * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-rules

**Comment by sergey-safarov** [comment]
Hi Daniel
Think this change
```
%if 0%{?rhel} || 0%{?centos_ver}
%if 0%{?rhel} > 6 || 0%{?centos_ver} > 6
BuildRequires:  pkgconfig
%endif
%else
BuildRequires:  pkgconfig
%endif
```
Is equal to
```
%if 0%{?rhel}
%if 0%{?rhel} > 6
BuildRequires:  pkgconfig
%endif
%else
BuildRequires:  pkgconfig
%endif
```
And equal to
```
%if 0%{?rhel} > 6
BuildRequires:  pkgconfig
%else
BuildRequires:  pkgconfig
%endif
```
As `pkgconfig` is present in all RPM supported dists think we can use
```
BuildRequires:  pkgconfig
```

What you think?

**Comment by miconda** [comment]
Not having CentOS/RHEL 6 around, I googled a bit and couldn't find it for sure that they ship with pkgconfig. If yes, go ahead and remove that condition and add pkgconfig to the BuildRequires listing make, gcc, etc... Thanks!

**Comment by sergey-safarov** [comment]
yes, exists
```sh
[safarov@safarov-dell kamailio-upstream]$ docker run -it centos:6
[root@c8b81ef4309e /]# pkg-config --version
0.23
```
I make changes

**Pull request closed without merging**
