### PR TITLE
ims_registrar_scscf: add a new contact state for notifications

### PR DESCRIPTION
**Pull request by kristiyan-peychev-flolive**
Add the `deregistered` state to IMS_Registrar_events_enum_t, allowing the
registrar to distinguish between UE unregsitration, which do not require
a notification to be sent, and network-originated deregistration requests.

#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
@alexyosifov - any comment on this PR?

**Comment by alexyosifov** [comment]
> @alexyosifov - any comment on this PR?

Just added a new registrar event. @kristiyan-peychev-flolive I can not see in the code where the new state is invoked. What do you mean with 'User's registration was terminated with **RTR**' Is that **RTR** a typo error? Is the **STR** correct?

**Comment by alexyosifov** [comment]
@kristiyan-peychev-flolive I got the logic - RTR (Registration-Termination-Request).
@miconda Looks OK for me.

**Comment by miconda** [comment]
Thanks!

**Pull request merged**
