### PR TITLE
app_python3: update documentation

### PR DESCRIPTION
**Pull request by aalba6675**
- update documentation and python_examples/ to reflect the new module name
- fix typo arg->args in python_examples/handler.py

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Update the documentation for module app_python3 to reflect the new name

### CODE REVIEW

**Comment by miconda** [comment]
I think the initial author of the documentation has to be kept there, because the content is largely from the old module. You can add yourself there for the updates you did, most of the docs have more than one author anyhow.

**Comment by aalba6675** [comment]
Going to fix this then squash (--force push)

**Comment by aalba6675** [comment]
Fixed and squashed  - kindly check again.

**Comment by miconda** [comment]
Thanks, merging!

For the future, do not forget that you do not need to update the README, only the xml dockbook file in doc/ subfolder.

**Pull request merged**
