### PR TITLE
kamctl: enable kamctl test from shell variable.

### PR DESCRIPTION
**Pull request by alishir**
- we can enable kamctl test by setting `KAMCTL_TEST=true kamctl`
  instead of setting TEST variable in kamctl script.

#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
@alishir - what were the errors related to commit 2c8fe55? Stretch is out for long time, nobody reported the errors so far.

**Comment by alishir** [comment]
@miconda It causes `Substitution Error`. I search for that error and I found that the cause is that `sh` links to `dash` in Debian Stretch. I change the `/bin/sh` to `/bin/bash` and error resolved.

**Comment by miconda** [comment]
Can you paste the the command you run and the entire error message printed in the terminal to try to track it properly?

**Comment by alishir** [comment]
Unfortunately I have no access to that system now, I will revert the change and test again.

**Comment by alishir** [comment]
@miconda 
Here is the output of `kamdbctl create`:
```bash
MySQL password for root:
-e \E[37;33mINFO: creating database kamailio_simple_db ...
-e \E[37;33mINFO: granting privileges to database kamailio_simple_db ...
-e \E[37;33mINFO: creating standard tables into kamailio_simple_db ...
-e \E[37;33mINFO: Core Kamailio tables succesfully created.
Install presence related tables? (y/n): n
/usr/sbin/kamdbctl: 216: /usr/sbin/kamdbctl: Bad substitution

```

**Comment by henningw** [comment]
I fear that applying 2c8fe55 will break compatibility for embedded systems again (issue #1815).
Can you execute the kamdbctl create with 'bash -x' prefixed and see where exactly it stops? Maybe it is possible to just make this substitution to confirm to POSIX standard as well.

**Comment by miconda** [comment]
It seems that the issue is expanding the variable when getting the answer for y/n question:
  * https://github.com/kamailio/kamailio/blob/master/utils/kamctl/kamdbctl.base#L216-L218

Such expression seems to be specific for bash:
  * https://mywiki.wooledge.org/Bashism

We should decide what to do to have an acceptable solution. Or maybe focus to make kamcli a (full) replacement for kamctl/kamdbctl and get rid of those old-style shell/bash scripts.

**Comment by miconda** [comment]
I applied a slightly different patch for enabling test mode from command line, enclosing the variable in double quotes - 4968e8994157f1152bf7461b16049d67e5c9cc59 .

For the bash related problems, I will open a dedicated issue on tracker to decide on a proper solution.

**Pull request closed without merging**
