### PR TITLE
tm: Update doc for t_check_trans()

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

I was looking in code at how t_check_trans() works and updated doc. Please let me know if I understood correctly how it behaves for non-acks and non-cancel, when transaction is found.

### CODE REVIEW

**Comment by smititelu** [comment]
E.g. function does not automatically exits config when transaction is found, but one might check against return code "0" in config and exit logic there.

**Comment by miconda** [comment]
Do you use t_check_trans() via KEMI or it is about native kamailio.cfg routing blocks? If later, have you changed:

  - https://www.kamailio.org/wikidocs/cookbooks/5.7.x/core/#return_mode

If an older version, I think at some point it was an issue with `return 0` not working properly.

**Comment by smititelu** [comment]
Hi, t_check_trans() via native config, return_mode default, kamailio 5.6

**Comment by smititelu** [comment]
Closing this PR as not an issue. After checking more, noticed t_check_trans() was always returning -1.

**Pull request closed without merging**
