### PR TITLE
secfilter: export functions to KEMI

### PR DESCRIPTION
**Pull request by bazrafshanmh**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

* All functions are exported to kemi

### CODE REVIEW

**Comment by bazrafshanmh** [comment]
The last time the format-check failed but I did the clang-format command with your configurations

**Comment by henningw** [comment]
Yes, the clang format check is still failing. Just to double check, you've run clang-format on your code?

**Comment by bazrafshanmh** [comment]
I ran the clang-format multiple times. but to make the code prettier and more similar to the official codes I edited them manually and made them more like other codes. this pull request will be closed

**Comment by henningw** [comment]
Especially for KEMI definitions there is a flag to tell the clang-format to ignore the format to format it pretty. Look e.g. to src/modules/evapi/evapi_mod.c, static sr_kemi_t sr_kemi_evapi_exports[].

**Pull request closed without merging**
