### PR TITLE
Extend rtpengine hashing algorithms

### PR DESCRIPTION
**Pull request by ionutionita92**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #1911 

#### Description

The goal was to have a different, more complex hashing algorithm that would offer a better distribution among nodes. We've seen in production that the current algorithm does not perform well under heavy load therefore we decided to add SHA1 hashing. After running performance tests we've decided that we need a cryptographic function in order to have the best results mostly when the callids have small entropy. 
In order to add SHA1, a new API was added in crypto module exporting a function applying SHA1 to a string. The API was used in rtpengine module over the callid. After this operation the hash was calculated as before except for applying 0xFF mask over the hash as it was done before, which restrains the power of this algorithm.

### CODE REVIEW

**Comment by miconda** [comment]
From crypto module, I am ok to merge.

For rtpengine, maybe @rfuchs can review and decide the next steps.

Somehow related, just making a note here for the future: the src/lib/srutils/shautils.{c,h} have dome of the shaXYZ functions, but not sha1 -- maybe we should add it and eventually move the files in the core, as they become more commonly used.

**Comment by rfuchs** [comment]
@miconda looks good to me, no objections

**Comment by smititelu** [comment]
@miconda is it ok for me to backport this to 4.4 branch? Or shall be considered as new feature (starting from 5.3 branch)?

**Comment by henningw** [comment]
You mentioned above in the patch description that it is a new feature. ;-) So it should be not backported, 4.4. is also EOL since 2018.

**Comment by smititelu** [comment]
ok, thanks

**Pull request merged**
