### PR TITLE
Fix typos: Remove consecutive occurrences of 'the'

### PR DESCRIPTION
**Pull request by altmas5**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Remove consecutive ocurrences of 'the' across the repo

### CODE REVIEW

**Comment by henningw** [comment]
Thank you for the pull request. It seems that you included multiple commits to module README files. This should not be changed, please change the repective XML file in the doc directories. Please also split the commits by components, as indicated in the issue template text. Thank you.

**Comment by altmas5** [comment]
Hi @henningw,

I rebased my branch and also did a commit for each lib/module, no README was changed (except for the main README.md).
The PR was automatically closed when I deleted the original commit to later make the individual commits and follow the issue template checklist. That's the reason for the close/re-open actions.

Regards

**Comment by henningw** [comment]
Ok, thank you. I will merge it. Please use for future pull request the proper prefix in the first line of the commit message, e.g. like "core: ..." or "carrierroute: ...", as documented in contribution docs. This helps to get a good Changelog out of the commits.

**Comment by altmas5** [comment]
It's an honour to have my PR merged on kamailio.
Sorry for the commit messages format.

**Pull request merged**
