### PR TITLE
Renaming userblacklist to userblocklist 

### PR DESCRIPTION
**Pull request by lbalaceanu**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

PR renames userblacklist to userblocklist and makes terminology changes to blocklist, allowlist.

### CODE REVIEW

**Comment by miconda** [comment]
You can also run `make dbschema` to regenerate the sql/db creation scripts for kamctl and push that commit as well.

Otherwise, it is ok to merge from my point of view. Thanks!

**Comment by lbalaceanu** [comment]
Thank  you. Closing the PR.

**Comment by miconda** [comment]
You closed the PR, but didn't merge it before. Is it what you wanted?

**Comment by lbalaceanu** [comment]
:) My bad

**Pull request merged**
