### PR TITLE
presence: allow control of subscription deletion

### PR DESCRIPTION
**Pull request by lazedo**
use the configuration xavp to control subscription deletion after notify
searches for `delete_subscription` value in the configuration xavp

### CODE REVIEW

**Comment by miconda** [comment]
You have to add the description in the docs for the new attribute.

**Comment by lazedo** [comment]
@miconda added documentation. would liketo port this to 4.4

**Comment by lazedo** [comment]
this pull requests represents a changing behaviour and in principle shouldn't be in 4.4, but we do have some contraints controlling the deletion of subscriptions. with this pull request we can manage a threshold of notify failures and delete the subscription based on that threshold.

**Comment by miconda** [comment]
Thanks! I can be merged!

**Pull request merged**
