### PR TITLE
pdb: make 'timeout' runtime configurable

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Make timeout modparam runtime configurable.
Also update timout execeded logs from NOTICE to ERR and add more info to them.
Also update utils/pdbt.c query tool to allow 0 carrier id.

### CODE REVIEW

**Review by henningw — COMMENTED** [review]
Thanks for the PR. The run-time cfg option looks straight-forward, good addition. You've also change the log level of a bunch of NOTICEs messages related to the timeout to ERROR and log additional information, was this done intentionally? Because its not mentioned in the commit message.

You've also change the pdbt tool behaviour in another location, this should probably be a dedicated commit with an own commit message, with the proper prefix.

**Comment by smititelu** [comment]
Hi, thanks for the feedback. I've updated the PR accordingly.

**Comment by miconda** [comment]
I guess it can be merged if no other comments.

**Comment by henningw** [comment]
Thanks for updating the PR, merged.

**Pull request merged**
