### PR TITLE
registrar: add path value to xavp_rcd

### PR DESCRIPTION
**Pull request by linuxmaniac**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally

#### Description
Add path value to xavp_rcd. This is needed when checking if a subscriber is still registered
with a certain parameter in the path.

### CODE REVIEW

**Comment by henningw** [comment]
This is a small change and a good extension, I think it is fine to merge it.

**Comment by miconda** [comment]
I am fine to merge, but probably we should add in short term a new parameter to control what attributes are cloned in xavp, some of them can be large in size like, path with couple of hops, and maybe not needed in specific cases.

**Comment by linuxmaniac** [comment]
@miconda something like `modparam("registrar", "xavp_rcd_mask", 0)` so we can define what to load?

**Comment by miconda** [comment]
@linuxmaniac - yes, but can be also the opposite condition: what to skip. What people find better.

**Comment by henningw** [comment]
I like "what to skip" more, in the end most people would probably use it on smaller installations.

**Comment by linuxmaniac** [comment]
Ok, I'm going to merge and I will work on the module parameter to define what values to skip

**Pull request merged**
