### PR TITLE
Keepalive module - prototype

### PR DESCRIPTION
**Pull request by gbour**
Hi all,   

Here is a prototype of Keepalive module I discussed on the mailing-list.
It can work standalone:
- destinations are set statically as module parameters
- *is_alive()* function allows to check destination state

It can also be used alongside with drouting module (currently only with sort_order 0)
- all destinations defined in drouting module are automatically monitored when drouting *enable_keepalive* option is set to 1
- unavailable destinations are ignored when calling do_routing() function

All comments are welcome

Thanks,
Guillaume

### CODE REVIEW

**Comment by miconda** [comment]
Thanks for contributing!

Can you make a pull request only with the new module as a single commit? It will be easier to review and see if anything needs to be adjusted. Also, add xml docbook files with the documentation of the module, as the other modules have. We are not merging new modules without having the documentation written.

For drouting make another pull request because it may need dedicated review process to get the integration with keepalive.

**Comment by gbour** [comment]
Hi @miconda 

I merge all commits for keepalive module, and added documentation

**Comment by dragos-oancea** [comment]
squash the two commits into one :)

**Comment by miconda** [comment]
Thanks! Merged manually in a single push.

**Pull request closed without merging**
