### PR TITLE
IMS DB: Adding i-cscf database/tables under utils/kamctl/mysql (orig. from misc/examples/ims/icscf.sql)

### PR DESCRIPTION
**Pull request by markusmonka**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Adding sqlfile ims i-cscf to utils/kamctl/mysql copied from misc/examples/ims/icscf
so that sql file will be automatically included in kamailio-mysql-module packages in the future

### CODE REVIEW

**Comment by miconda** [comment]
I am fine to merge it, although it would be good that ims-related tables get the corresponding xml schema definitions in the `src/lib/srdb1/schema/` and be generated from there.

**Comment by henningw** [comment]
@markusmonka Any plans to maybe also add the XML schema definitions as mentioned above?

**Comment by markusmonka** [comment]
in a quiet minute i like to watch it

**Comment by henningw** [comment]
Xenofon will have a look to it and convert it to XML files.

**Comment by henningw** [comment]
Thanks for the PR, it will be implemented with the linked PR in the XML schema, close this one.

**Pull request closed without merging**
