### PR TITLE
etc/kamailio.cfg: add new scanner UAs

### PR DESCRIPTION
**Pull request by kevin-olbrich**
Source: https://github.com/2600hz/kazoo-configs-kamailio/blob/68ccc2123e5495be89cb41b95f089535886a3453/kamailio/default.cfg#L402-L407

#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

https://github.com/kamailio/kamailio/pull/1903

### CODE REVIEW

**Comment by kevin-olbrich** [comment]
I've used the GitHub editor which seems to have broken the indent.
For best visibility I am using two tabs and two whitespace.

**Comment by kevin-olbrich** [comment]
> I've used the GitHub editor which seems to have broken the indent.
> For best visibility I am using two tabs and two whitespace.

Fixed

**Comment by sergey-safarov** [comment]
As options
Some UA use fixed string and maybe used expressions like
```
$ua == "friendly-scanner"
```

**Comment by miconda** [comment]
This one is not going to be merged, the reasons:

  * first see my comment in the other PR: https://github.com/kamailio/kamailio/pull/1903#issuecomment-475956037
  * using separate `=~` has not benefits, actually can be slower than using a single regex matching. If it gets too long, could make sense split in groups of matches to avoid long lines and have better readibility, but not one match per possible user-agent.

**Pull request closed without merging**
