### PR TITLE
ims_ipsec_pcscf: closing mnl_socket in some exceptional situations

### PR DESCRIPTION
**Pull request by dolk13**
- fix leak socket when error handling errors in creation or destruction ipsec tunnel

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Fixed socket leak on error during ipsec tunnel creation or destruction.

### CODE REVIEW

**Comment by henningw** [comment]
I looked into the existing code of the function create_ipsec_tunnel(..)

Are you sure that the "return 0" in the error cases is correct? Should it not be -1, as in the one case in the bottom of the function? If yes - then it makes probably sense to combine them all into one "goto error" case.

**Comment by alexyosifov** [comment]
> Thank you for the pull request. I looked into the existing code of the function create_ipsec_tunnel(..)
> 
> Are you sure that the "return 0" in the error cases is correct? Should it not be -1, as in the one case in the bottom of the function? If yes - then it makes probably sense to combine them all into one "goto error" case.

Hi,
I am pretty sure that all return codes in error cases should be changed to -1. I am working on this module actively and return code 0 in these error cases will cause problems for sure.

**Comment by miconda** [comment]
@henningw, @alexyosifov - looking at the patch, the pull request here is not adding any `return 0`, they existed. The patch is adding a couple of `close_mnl_socket(sock)`. If the existing `return 0` in error cases are wrong, then they need to be fixed of course. But it is not a strict relation with this PR.

**Comment by alexyosifov** [comment]
> @henningw, @alexyosifov - looking at the patch, the pull request here is not adding any `return 0`, they existed. The patch is adding a couple of `close_mnl_socket(sock)`.
> 
> If the existing `return 0` in error cases are wrong, then they need to be fixed of course. But it is not a strict relation with this PR.

Hi,
I'll fix the problem with the error codes in the next ipsec pull request from my side.

**Comment by henningw** [comment]
@miconda - I know. :-) But as @alexyosifov was working on the code right now, I wanted to ask him about his opinion.

**Comment by henningw** [comment]
Merged, will also backport to stable branches.

**Pull request merged**
