### PR TITLE
some kemi function exports 

### PR DESCRIPTION
**Pull request by smititelu**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Exported some functions to kemi. Currently testing.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks!

**Comment by smititelu** [comment]
Can I port this to 5.6?

**Comment by henningw** [comment]
KEMI extensions can be backported to stable branches. You can do it, if not probably it will be probably done as part of the release preparations for the next minor release there.

**Comment by smititelu** [comment]
Nice, thank you! Any date estimation for the next minor release?

**Comment by miconda** [comment]
You can go ahead and backport, but be aware that there was a follow up commit that I did, because exports to kemi must be with unique function names (per module), because some languages do not support variadic number of parameters.

The release will be done soon, I haven't announced yet for 5.6.x but maybe I could do it even on Tuesday (if not, several days afterwards), because I of the work being already done to prepare 5.4.9 and (upcoming) 5.5.5.

**Pull request merged**
