### PR TITLE
pkg/kamailio/deb: optimize systemd units

### PR DESCRIPTION
**Pull request by kevin-olbrich**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Please see conversation on ML for reference:
https://lists.kamailio.org/pipermail/sr-users/2018-November/103668.html

### CODE REVIEW

**Comment by linuxmaniac** [comment]
can you please follow the [commit guidelines](https://www.kamailio.org/wiki/devel/git-commit-guidelines) using `pkg/kamailio/deb` as the prefix?

**Comment by kevin-olbrich** [comment]
I have now force-pushed the changes and remove the ol/el7 service file from the changes.
Please let me know if that one should be fixed as well in a new PR.

**Comment by linuxmaniac** [comment]
@kevin-olbrich push those changes with the proper prefix `pkg/kamailio/oracle` here too, please

**Comment by kevin-olbrich** [comment]
> @kevin-olbrich push those changes with the proper prefix `pkg/kamailio/oracle` here too, please

Done

**Comment by linuxmaniac** [comment]
Thanks!

**Pull request merged**
