### PR TITLE
tls: enable statistics

### PR DESCRIPTION
**Pull request by Cederich**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

This enables tls module statistics. This is needed for the xhttp_prom module to export tls module statistics.

### CODE REVIEW

**Comment by linuxmaniac** [comment]
You need to squash both commits in one and push --force

**Comment by Cederich** [comment]
If I understand this correctly, I have to adjust the formatting, right?

**Comment by henningw** [comment]
> If I understand this correctly, I have to adjust the formatting, right?

If you are referring to the failed build format checks, yes this caused from an error in the formatting. You could execute clang-format for the changed files and force-push again.

**Comment by Cederich** [comment]
Should be alright now.

**Comment by miconda** [comment]
Thanks!

**Pull request merged**
