### PR TITLE
core: const correctness

### PR DESCRIPTION
**Pull request by liviu-rolo**
benign const qualifiers in inline functions

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
Can you provide more details why these changes are useful or necessary?

**Comment by liviu-rolo** [comment]
They are not necessary.
In fact, I needed const only in `init_dst_from_rcv` for an internal module, but, with the occasion, I added more const for consistency - including existing code like `su_cmp` and `su_getport`.
So, apart from consistency and style, they are neither useful for the community, I guess.

**Comment by kamailio-sync** [comment]
I think they are useful. I have done several changes like this in the past. It allows the Compiler to optimize better and will also prevent unintended modifications which can lead to bugs
________________________________

**Comment by miconda** [comment]
@henningw - to my knowledge, there is no optimisation that a compiler can do to const parameters of a function.

I asked because the most of the functions there were not touched for ages, so not usual suspects for unintended changes.

Moreover, the commit message is somehow contradictory, first lines suggests is makes something correct (like it was wrong before), but then in the second line says the changes are benign.

But if people thinks it is better aesthetic this way, then ok.

**Comment by henningw** [comment]
Thanks @miconda - you are right the commit message is a bit misleading, I've missed that, my fault.

**Comment by kamailio-sync** [comment]
Its about const correctness, which is a good idea especially for API or core Code. https://isocpp.org/wiki/faq/const-correctness#overview-const
________________________________

**Pull request merged**
