### PR TITLE
core: fix a seg while t_continue with nats module

### PR DESCRIPTION
**Pull request by seven1240**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

segfault

```
#0  0x0000ffffb9934840 in cfg_update_local (no_cbs=0) at ../../core/cfg/cfg_struct.h:366
366			cfg_child_cb = cfg_child_cb->next;
(gdb) print cfg_child_cb
$1 = (cfg_child_cb_t *) 0x0
```

example lua:

```
function ksr_route_nats()
	KSR.tm.t_newtran()
	local tindex = KSR.pv.gete("$T(id_index)")
	local tlabel = KSR.pv.gete("$T(id_label)")
	KSR.tmx.t_suspend()

	local req = {
		jsonrpc = "2.0", method = "route",
		id = tindex .. ':' .. tlabel,
		params = {
			from = KSR.pv.gete("$fu"),
			to = KSR.pv.gete("$tu"),
		}
	}
	local rpc = cjson.encode(req)
	KSR.info("rpc: " .. rpc .. "\n")
	KSR.nats.publish("cn.xswitch.ctrl.route", rpc)
	KSR.x.exit();
end

function handle_nats_response(data)
	msg = cjson.decode(data)
	if (not msg) or (not msg.id) then return end
	KSR.info("========= msg.id: " .. msg.id .. "\n")

	if not msg.result then
		KSR.error("response has no result\n")
		return
	end

	tindex, tlabel = msg.id:match("(.+):(.+)")
	if tindex and tlabel then
		KSR.pv.sets('$var(nats_response)', data)
		KSR.tmx.t_continue(tindex, tlabel, 'ksr_nats_continue')
	end
end
```

I'm not sure if it's the proper fix, but this pr fixed the seg. Thanks.

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the PR. The change looks sensible to me, maybe it make sense to also log an error message. Interesting also why there is no callback pointer set in this situation.  @eschmidbauer any comments regarding the patch as well?

**Comment by henningw** [comment]
Probably related to issue #3395

**Comment by eschmidbauer** [comment]
This fix looks okay to me but it's beyond the scope of the NATs module. And I'm wondering if this can be fixed in the NATS module instead of the core. The change you made here is probably called from nats in `cfg_update`. I wonder if @miconda has any insight

**Comment by seven1240** [comment]
https://github.com/kamailio/kamailio/commit/ffbb6ad2837326e7309be342ce62527c16f6db16 fixed this one. should I add some warning log or close this?

**Comment by miconda** [comment]
Closing this one.

@seven1240: if you want to add some extra logging, make a new PR.

**Pull request closed without merging**
