### PR TITLE
presence: introduce new module parameter `force_delete`

### PR DESCRIPTION
**Pull request by eschmidbauer**
- deletes expired presentity records without sending a NOTIFY
 - `force_delete` disabled by default

### CODE REVIEW

**Comment by eschmidbauer** [comment]
@miconda here is PR for new presence parameter

**Comment by phil-lavin** [comment]
Good timing. Literally just came out of a meeting where the undesirable behavior of repeated `terminated` NOTIFY messages was discussed. This is a useful addition.

You've changed a lot of whitespace that is not related to this PR. Makes it very difficult to digest :/

Appreciate this isn't your doing and you've just copied the `LM_ERR` from the rest of the code, but these log levels look a little enthusiastic. These are debug logs - perhaps info at best.

**Comment by eschmidbauer** [comment]
@phil-lavin sorry about the whitespace changes, I learned from my mistake and will fix whitespace in a separate commit from now on. The only significant change to the code is here:
```if (delete_presentity(&pres) < 0)
 				{
 					LM_ERR("Deleting presentity\n");
 					goto error;
 				}```

And if you look at full code, you'll see I just copied it from a few lines below it. You are welcome to change the log levels in a separate PR!
Thanks,
Emmanuel

**Comment by miconda** [comment]
Thanks, it will be merged!

**Pull request merged**
