### PR TITLE
Make timeout mechanism useful by adding support for supplying timeout tag

### PR DESCRIPTION
**Pull request by sobomax**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

The timeout_socket feature has been added in 2010, but from the look of it it has been designed for the "ngcp-mediaproxy-ng" and never worked with the real RTPProxy. As such both the documentation and the code needs to be adjusted to make it actually useful with the RTPProxy.

### CODE REVIEW

**Comment by sobomax** [comment]
The check fails due to unrelated issue:

`  A fatal error occurred: Could not write a relation to a file
  (eventual cause: IOException "No space left on device")
  Error: Error running analysis for cpp: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.15.0/x64/codeql/codeql database run-queries --ram=5897 --threads=2 /home/runner/work/_temp/codeql_databases/cpp --min-disk-free=1024 -v --expect-discarded-cache --no-intra-layer-parallelism". Exit code was 2 and error was: A fatal error occurred: Could not write a relation to a file
  (eventual cause: IOException "No space left on device"). See the logs for more details.`

**Comment by miconda** [comment]
Thanks!

Is the PR completed? If yes, I would merge it manually to make the commit message follow the contributing guidelines:

  - https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format

**Comment by sobomax** [comment]
> Thanks!
> 
> Is the PR completed? If yes, I would merge it manually to make the commit message follow the contributing guidelines:
> 
> * https://github.com/kamailio/kamailio/blob/master/.github/CONTRIBUTING.md#commit-message-format

Hi Daniel, yes, it's complete. Thanks for pointing out, I've updated the commit messages to hopefully conform to the guidelines.

**Comment by linuxmaniac** [comment]
amended the commit messages to use ``rtpproxy:`` as prefix. Thanks!
8ac570943f1dfd47f9d02686cc399d3cd1cdcd92
190ef9a54df33b4d053a4225e9d6257e0a045008

**Pull request closed without merging**
