### PR TITLE
xhttp_prom: optional disabling of metrics deletion

### PR DESCRIPTION
**Pull request by Maratk1n**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by vhernando** [comment]
Thank you for your contribution, but I have it fixed in the next version for the module I am going soon to upload.

**Comment by henningw** [comment]
@vhernando any update about your extensions you wanted to upload?

**Comment by vhernando** [comment]
Hello Henning,

these changes are already included in latest big patch for xhttp_prom module in master branch along with new histogram feature.

README updated too.

Regards,
Vicente.

**Comment by henningw** [comment]
@vhernando thanks for the update

**Pull request closed without merging**
