### PR TITLE
pre-commit: cmake-format and cmake-lint hooks [skip ci]

### PR DESCRIPTION
**Pull request by linuxmaniac**
@xkaraman I hope you will agree to add this jobs related to cmake files to keep things tidy.

### CODE REVIEW

**Comment by miconda** [comment]
It is fine for me.

**Comment by xkaraman** [comment]
Yes, definitely agree!!

**Comment by miconda** [comment]
If a custom config is going to be used, maybe it would be good to tune it a bit, since we are at the beginning of using cmake files. For example I would suggest a longer `line_width`, 80 was (maybe still is) for code to be easily seen on the very old terminal/console, but considering the current displays as well as terminal apps, it could be more convenient to have it like 120 or so. Otherwise we may end up in splitting lines/strings that are maybe not very long, but they are impacted by indentation.

**Comment by miconda** [comment]
Not to continue the discussion on this closed PR, I created tracker issue for it: # 4075.

**Comment by xkaraman** [comment]
@linuxmaniac @miconda: Question regarding these checks! 

Are they enforced when pushing directly to master, if someone has not setup locally the pre-commit python module and not being warned? 

Ideally, when pushing to master, it must not accept code (either cmake or c), that does not conform to the format requested. 

On pull request we have the checks, so we can know about it. On the direct commit, if the author does not have locally the `pre-commit`, it seems to me that it can push with whatever format.

**Pull request merged**
