### PR TITLE
sipt: Add functions to work with forwarding info

### PR DESCRIPTION
**Pull request by sergey-vb**
#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
This commits adding some new functions to Get and Change forwarding info in ISUP part of SIP-I/SIP-T messages.

sipt_forwarding(origin, nai) - updates the IAM in the body if it exists, setting (or adding) the forwarding number to origin with the nature address specified in nai

$sipt_redirection_info - Returns "Redirecting reason" or -1 if no redirection info found.

$sipt_redirection_number - Returns number to which redirection will trigered

sipt_redirection_number_nai - Returns NAI for redirection number from ISUP

### CODE REVIEW

**Comment by miconda** [comment]
I think it would be good to have one variable class with inner names instead of many new variables, eventually added to the existing $sipt(...) variable -- maybe @tsearle can comment more.

**Comment by miconda** [comment]
@sergey-vb - would you consider having the new variables as part of $sipt(...)?

So instead of:

```
$sipt_redirection_info
$sipt_redirection_number_nai
$sipt_redirection_number
```

To have:

```
$sipt(redirection_info)
$sipt(redirection_number_nai)
$sipt(redirection_number)
```

I think it is better to have them grouped. You can push a new patch for it, no need to do a new PR. Then I can merge.

**Comment by sergey-vb** [comment]
Hi Daniel,
I will try to do this.

--
Best regards,
Sergey Basov                     e-mail: sergey.v.basov@gmail.com

2018-04-25 15:57 GMT+03:00 Daniel-Constantin Mierla <
notifications@github.com>:

**Comment by miconda** [comment]
Any estimation when you are going to work on updating the variables. I am reviewing the PRs in order to merge what's ready.

**Comment by sergey-vb** [comment]
In progress.
I have some problem with returning number from sipt_get_redirection_number function.
I can print it in c code using 
LM_INFO("REDIRECTION NUMBER : %s end \n", sb_s.s);

But when i do 
pv_get_strval(msg, param, res, &sb_s);
I got some binary value in kamailio script.

**Comment by sergey-vb** [comment]
Hi Daniel.

I have done adding new variables as a part of $sipt()
Now they are:
$sipt(redirection_info)
$sipt(redirection_number)
$sipt(redirection_number.nai)

**Comment by miconda** [comment]
Thanks, merged manually via 21b9694d4eb18e146692dedc2a2337216d58b5c2 .

The vars exported not part of $sipt(...) were removed.

**Pull request closed without merging**
