### PR TITLE
[ci skip] Get more Open Source Helpers

### PR DESCRIPTION
**Pull request by schneems**
[CodeTriage](https://www.codetriage.com/) is an app I have maintained
for the past 4-5 years with the goal of getting people involved in
Open Source projects like this one. The app sends subscribers a random
open issue for them to help "triage". For some languages you can also
suggested areas to add documentation.

The initial approach was inspired by seeing the work of the small
core team spending countless hours asking "what version was
this in" and "can you give us an example app". The idea is to
outsource these small interactions to a huge team of volunteers
and let the core team focus on their work.

I want to add a badge to the README of this project. The idea is to
provide an easy link for people to get started contributing to this
project. A badge indicates the number of people currently subscribed
to help the repo. The color is based off of open issues in the project.

Here are some examples of other projects that have a badge in their
README:

- https://github.com/crystal-lang/crystal
- https://github.com/rails/rails
- https://github.com/codetriage/codetriage

Thanks for building open source software, I would love to help you find some helpers.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks for the contribution! I didn't have time yet to look deeper at codetriage, sounds interesting, likely to merge the patch soon as I get time to check a bit more. I asked within the community to see if anyone had any experience with the service, but apparently is rather new to get something from there.

One aspect needs to be clarified, who is managing the related project on codetriage, respectively:

  * https://www.codetriage.com/kamailio

If it is going to be somehow officially referenced, we have to know who is behind it and can control it, ideally have one of our core developers be able to manage as well.

**Comment by schneems** [comment]
Thanks for the review. Right now there is no concept of organizations in CodeTriage, only individual repos.

For individual repos there’s not anything to manage yet, though I’m open to any ideas for things you might want to change or new features you might want to add.

**Comment by sergey-safarov** [comment]
Look interesting. I subscribed.

**Comment by schneems** [comment]
Great. Btw I published a page yesterday that talks more about the motivations and history of the project if you’re interested https://www.codetriage.com/what

**Comment by miconda** [comment]
Thanks, I pushed a slightly different commit (in order to have projet's style of commit message) adding the codetriage badge.

**Comment by schneems** [comment]
Thanks!

**Pull request closed without merging**
