### PR TITLE
dialog: adding dialog replication via DMQ

### PR DESCRIPTION
**Pull request by Soapnix**
- updating code base to actual state.
- adding repliation for DLG_STATE_EARLY to prevent hanging up unconfirmed dialogs and its infinite replication.
- fixing dialog removal on peers to prevent die on timeout and possible infinite replication.
- fixing dialog removal on peers when master node cleanly restart.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks, useful patch!

One thing, two new global variables are defined, exported as module parameters, but they are not actually used:

```
int dlg_id_offset = 1;
int dlg_id_increment = 1;
```

By name, I guess they are intended to be used for dialog id generation, but no code or docs related to them.

**Comment by Soapnix** [comment]
We are glad to help improving kamailio.
Our company is very interested in this feature (and some other - now troubleshooting dmq_usrloc).
Yeah, I'm so sorry - I missed this variables during last code clean - fuction which use them was removed.

**Comment by miconda** [comment]
So, you say they are not needed for the new functionality to work properly, right?

**Comment by Soapnix** [comment]
Of courese not. Do not get me wrong.
dlg_dmq works proprely, we double check they funcs and stability before I write for you.
I'm already have a commit, which removes those two unused variables.

**Comment by gaaf** [comment]
I quickly scanned the current code, but fail to see how hash id collisions are avoided now that dlg_id_offset/increment are removed. Can you elaborate on that?

**Comment by gaaf** [comment]
No explanation?

**Comment by Soapnix** [comment]
We are working on it.

**Pull request merged**
