### PR TITLE
Db redis cluster support

### PR DESCRIPTION
**Pull request by Riccardo-78**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #2977

#### Description
Add support for redis cluster protocol via hiredis-cluster library to db_redis module

### CODE REVIEW

**Comment by miconda** [comment]
@agranig: not sure you are still working with db_redis module, if yes, maybe you what to look over this PR.

**Comment by agranig** [comment]
Looks good to me from a visual point of view, but I currently don’t have a setup to test it in real life.

**Comment by Riccardo-78** [comment]
I can provide src rpm of hiredis and hiredis-cluster for testing.

**Comment by miconda** [comment]
Thanks, merging it!

@sergey-safarov: anything useful for packaging if src rpm of hiredis and hiredis-cluster are provided?

**Pull request merged**
