### PR TITLE
cnxcc: New improvement for the cnxcc module

### PR DESCRIPTION
**Pull request by Pepelux**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

With this changes it is possible to account the connect cost for the call. This is useful for calls to premium numbers that have connection charges.

### CODE REVIEW

**Comment by henningw** [comment]
@caruizdiaz - as you wrote the cnxcc module, can you have a look to the puil request?

**Comment by miconda** [comment]
Indeed, even still around the eco-system, @caruizdiaz is no much active within development of the project, so this can be merged without his review.

I will do a review and then can merge if all ok.

However, I wanted to make a note as I could see in the commit: @Pepelux - when adding a new feature or fixing a bug, do not do reformatting of the exiting code, it makes spotting the new code and reviewing it harder. Code formatting is more than welcome, but make it a dedicated commit only for that.

**Comment by Pepelux** [comment]
Ok. Sorry

**Comment by miconda** [comment]
It can be merged from my point of view. Thanks!

**Pull request merged**
