### PR TITLE
modules/cdp: added src_addr parameter in peer definition

### PR DESCRIPTION
**Pull request by grumvalski**
This patch add the possibility to specify the src ip addr we want to use when connecting to a peer.
Useful when we have several ip addresses in the same machine and we want diameter traffic goimg out from a specific one.

### CODE REVIEW

**Comment by miconda** [comment]
Apparently it doesn't work to assign more than one developer -- i wanted to ping the ims guys on this item.

**Comment by kamailio-sync** [comment]
Hey Daniel,

Received. will look into it!

**Comment by miconda** [comment]
Any update on reviewing this? The patch seems rather ok.

**Comment by miconda** [comment]
Going to merge this pull request, waiting here for a while. Patch looks ok. If any adjustments, then can be done directly on the merged code.

**Comment by grumvalski** [comment]
Thanks Daniel.

Cheers,

Federico

**Pull request merged**
