### PR TITLE
Added new auth module function auth_algorithm

### PR DESCRIPTION
**Pull request by juha-h**
#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
Added new Added new auth module function auth_algorithm that can be used to dynamically override algorithm parameter value.

#### Note
I was not able to test check README, because of this error:
```
/usr/src/orig/kamailio$ make modules-readme modules=modules/auth
make -C src/ modules-readme 
make[1]: Entering directory '/usr/src/orig/kamailio/src'
make --no-print-directory -C doc auth.txt
xsltproc  --novalid \
        --nonet \
        --novalid \
        --stringparam output "auth.d" \
        ../../../../doc/docbook/dep.xsl auth.xml 
xsltproc  --novalid \
	--xinclude \
        ../../../../doc/docbook/txt.xsl auth.xml | lynx -nolist -stdin -dump > auth.txt
error : Unknown IO error
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file ../../../../doc/docbook/txt.xsl line 6 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
```

### CODE REVIEW

**Comment by miconda** [comment]
The README must not be regenerated locally and part of the commit, it is going to be generated on server and pushed to git repository by a cron job.

One can generate readme locally only for checking it if it is correct, but then reverted before committing.

Of course, if one pushed a regenerated commit is not critical, but by using the server side generation, the READMEs look coherent.

I am going to merge the PR manually for make it consistent with the commit message guidelines.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> One can generate readme locally only for checking it if it is correct,
> but then reverted before committing.

That is exactly what I tried to do according to instructions, but
generation failed.

Also, there is something wrong with the format check.  It shows red even
when the Details shows OK:

6992d1784aa3e1f96aa3a406f25675178605108d... PASSED
3bcedc47e381d22521aeb544b0d27180786d7039... PASSED

-- Juha

**Comment by miconda** [comment]
If you want to test README generation locally, then you are missing some dockbook-relate packages, likely `docbook-xsl`.

**Comment by miconda** [comment]
Merged manually!

**Comment by juha-h** [comment]
> If you want to test README generation locally, then you are missing some dockbook-relate packages, likely `docbook-xsl`.

README generation worked after I installed Debian package `docbook-xsl`.  For some reason make command as described here [https://www.kamailio.org/wikidocs/devel/module-docbook-readme/]() was not able to load it from source repo.

**Comment by juha-h** [comment]
How about the failing format check?

**Comment by miconda** [comment]
As I said, I haven't looked much into it, not sure what was the reason ...

I installed `pre-commit` along with `clang-format` and before each commit the formatting is checked automatically, simplifying my coding process as I can do it without caring of formatting and it gets fixed at commit time. I sent an email about it a while ago:

  - https://kamailio.org/mailman3/hyperkitty/list/sr-users@lists.kamailio.org/message/7PSVLEKOMSCDMUYN4VZLIO4ZBRBJXMF6/

**Comment by linuxmaniac** [comment]
You can push --force the new commit with the format fixed squashing previous commits

**Pull request closed without merging**
