### PR TITLE
p_usrloc: add new update function

### PR DESCRIPTION
**Pull request by smititelu**
Add also new "uniq" column.
The new update function will use this new column.

#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the pull request.
I think it might be better to use a value of "2" to specify the new scheme (at least in the docs). This would be more similar to the way other modules mode parameter work.
Did I understand it correctly that you add a new DB column? Is this for the reg_db table or the (partitioned) location table?

**Comment by smititelu** [comment]
I've updated the pull request to consider only 0, 1, 2 values (docs and code).

I've added the new function to consider additional columns when updating database; "uniq_col" is one of them. We have some user agents that send "uniq" in Contact header of SIP REGISTER message.

**Comment by henningw** [comment]
Thank you. So I understand correctly that the "new way" is using the uniq column for updates.

The p_usrloc module is not using the generic DB scheme infrastructure. So it would be great if you could also update the _location.sql_ file in the p_usrloc module directory to include the new column definition, just to have it somewhere defined.

**Comment by smititelu** [comment]
Updated p_usrloc's location.sql to include "uniq" column.

**Comment by henningw** [comment]
Thanks again, you can merge.

**Comment by smititelu** [comment]
Thanks for review.

**Pull request merged**
