### PR TITLE
 kamdbctl: added verification before drop command 

### PR DESCRIPTION
**Pull request by fredposner**
- add get_answer and warning that drop command will drop existing database

#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [X] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [X] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Added verification to drop command. Allows for someone to change their mind before dropping existing database similar to #1852

### CODE REVIEW

**Comment by henningw** [comment]
Thank you. I merged it manually, as your branch still contains the previous commits related to the reinit change.

**Comment by fredposner** [comment]
Thanks. I'll get better.

**Comment by henningw** [comment]
@fredposner don't worry, all fine. :-)

**Comment by miconda** [comment]
For the records, when pushing manually a commit from a PR as it is, the initial author of the commit can be preserved via `git commit --author="..." ...`. The author can be taken from the patch of the PR.

**Pull request closed without merging**
