### PR TITLE
nats: Add one subscriber connection per nats_url

### LINKED ISSUE #2916: nats module subscriber issue when connected to more "nats_urls"
### Description, Troubleshooting, Reproduction

I have 3  go nats servers running and the following kamailio config for nats:
```
modparam("nats", "nats_url", "nats://127.0.0.1:4222")
modparam("nats", "nats_url", "nats://127.0.0.2:4222")
modparam("nats", "nats_url", "nats://127.0.0.3:4222")

modparam("nats", "subject_queue_group", "foo:2020")
...

event_route[nats:foo]
{
                xlog("L_ERR", "==============> received $natsData");
}
```
I try to publish using some nats publisher (e.g. nats.c example/libuv-pub.c), and nothing gets printed in event route:
```
./pub -s nats://127.0.0.1:4222 -txt "aaaaaaaaaaaa" -count 1 // event route log NOT printed
./pub -s nats://127.0.0.2:4222 -txt "aaaaaaaaaaaa" -count 1 // event route log NOT printed
``` 

However, if I try to publish on the last server "127.0.0.3", log *is* printed:
```
./pub -s nats://127.0.0.3:4222 -txt "aaaaaaaaaaaa" -count 1 // event route log IS printed
```

I expected to see 1 log message for each of the above publish(es). Found this while implementing and testing #2915 

Thanks,
Stefan

### PR DESCRIPTION
**Pull request by smititelu**
Updated doc.
Fixes #2916.

#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Add a separate connection for each nats_url, for subscriber workers. Basically tested it locally, with 3 nats_url and 2 workers.

Thanks,
Stefan

### CODE REVIEW

**Comment by miconda** [comment]
@eschmidbauer - any opinion on this?

**Comment by eschmidbauer** [comment]
i think we should take another approach to this. see https://github.com/kamailio/kamailio/pull/2934
and https://github.com/kamailio/kamailio/issues/2916#issuecomment-968372896

**Comment by eschmidbauer** [comment]
@smititelu im not sure this PR applies anymore. if you still think it should be merged, can you rebase it onto master?

**Comment by smititelu** [comment]
Closing this PR since it does not apply anymore

**Pull request closed without merging**
