### PR TITLE
pv: add monotonic clock to TimeVal pseudovariable

### PR DESCRIPTION
**Pull request by xadhoom**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Sometime is helpful to have a monotonic timer to attach to events in order to discard out-of-order ones on receiving side. Current time values are not ideal since are subject to clock skews, adjustment and so on. Since we have system monotonic clock we can use that value to have a monotonic counter. 

To be 100% fair CLOCK_MONOTONIC can still be skewed only by ntp adjustment, that's why we try to use CLOCK_MONOTONIC_RAW which is linux-only (afaik) that do not suffer from such adjustments.

The new pseudovariable is `$TV(Sm)`, which returns the monotonic counter as a string. Note that even if is based on clock, it starts from an unspecified point in time, so should really be treated as an always increasing counter.

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the pull-request. Could you also please add the documentation for the new PV in our [wiki](https://github.com/kamailio/kamailio-wiki/blob/main/docs/cookbooks/devel/pseudovariables.md)? Then it could be probably merged, if no other comments come in.

**Comment by xadhoom** [comment]
Ok,

I'm on vacation right now, will do by the end of August.

Il mer 10 ago 2022, 11:28 Henning Westerholt ***@***.***> ha
scritto:

**Comment by xadhoom** [comment]
Done in https://github.com/kamailio/kamailio-wiki/pull/14

**Comment by henningw** [comment]
Thanks, merged

**Pull request merged**
