### PR TITLE
usrloc: ul.dump fixes

### PR DESCRIPTION
**Pull request by vitalikvoip**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
ul.dump rpc procedure has two problems:
- it doesn't call unlock_ulslot() for "ul.dump brief" when aor creation fails
- json format of its reply is incorrect for multiple domains. They are not represented as an array of domains and this breaks "kamctl ul show" while "kamcmd ul.dump" still works.

Table unlocking is safe and needs to be backported to the stable branch. New output format of "ul.dump" can be considered as a breaking change since somebody can use this command to get registered users information and parse it.

### CODE REVIEW

**Comment by linuxmaniac** [comment]
First of all ... rebase

**Comment by vitalikvoip** [comment]
Ok. Probably missed this requirement. Will do fix it. 
Wasn't sure about the number of commits. It's required to merge several commits to the same module into one final commit, but in this case, the first one is a bug fix that most likely will be cherry-picked into 5.0 and the second one also a bugfix, but it also changes behavior and may be accepted only for master.

**Comment by linuxmaniac** [comment]
having two different commits is not a problem. Problem is having all that Merge branch master. It's quite difficult to review anything

**Comment by miconda** [comment]
Indeed, make a clean pull request. This one is not easy to review because there are many patches that are not related to your changes. Will you make a new pull request or will update this one?

**Comment by vitalikvoip** [comment]
I will make a new clean pull request.

**Comment by linuxmaniac** [comment]
JFYI no need to do that. Just rebase and push --force onto your branch the PR will be updated automatically

**Pull request closed without merging**
