### PR TITLE
dispatcher: remove destination from in-memory dispatcher set

### PR DESCRIPTION
**Pull request by tverlaan**
#### Pre-Submission Checklist

- [X] Commit message has the format required by CONTRIBUTING guide
- [X] Commits are split per component (core, individual modules, libs, utils, ...)
- [X] Each component has a single commit (if not, squash them into one commit)
- [X] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [X] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

- add dispatcher.remove call to remove entry from in-memory dispatcher
list
- allow arguments to callback in ds_iter_set()

### CODE REVIEW

**Comment by henningw** [comment]
Hello, thank you for the pull request. I had a quick look to the diff - looks fine for me. One question though, I noticed that you changed also the attr str handling in ds_add_dst() function, why was this changed as well?

**Comment by tverlaan** [comment]
Hi, thanks for taking a look. I changed it since I saw that pack_dest checks if attr is not NULL and now removing and adding through rpc both set it to NULL instead of creating a zeroed string when calling that function. It looks a bit more uniform to me.

**Comment by miconda** [comment]
Iirc, the attrs set to empty string was an workaround to be sure the AVPs with attrs value do not get shifted (associated) with a wrong destination. The AVP cannot be null, so if among selected destinations some of them were with attrs and some without, then the number of AVPs with attrs was lower than the number of destinations.

Maybe is no longer needed with xavps, as the fields related to a destination are kept in an XAVP sublist. But that has to be reviewed to see if there is any side effect. Might be better to split this chance in its own commit.

**Comment by tverlaan** [comment]
I removed the change from this commit and focused this PR entirely on the feature addition.

I'd have to do some more investigation to understand full scope. I'll reconsider a PR for that when I better understand. Thanks!

**Comment by miconda** [comment]
OK, merging, thanks!

**Pull request merged**
