### PR TITLE
dialog module : new rpc function for terminate

### PR DESCRIPTION
**Pull request by ycaner06**
- added new rpc command for terminate a dialog with callid, fromtag and totag.
- added new rpc command to doc and serctl is removed 
- added rpc return code  to dlg_terminate_dlg function
- added rpc return code to rpc domain reload function

### CODE REVIEW

**Comment by miconda** [comment]
I am going to apply manually the patched adding the new command for dialog to terminate by callid, from/to tag. I would change the name from dlg.dld_terminate_dlg in dlg.terminate_dlg.

For the rest of the patches, as they add embedded response code/text to a successful response, not data from dialogs. I would open a discussion on sr-users to decide on it, because it changes the current behaviour that is know to work and it can break many existing tools. Maybe this new behavior can be enabled by a modparam.

**Comment by ycaner06** [comment]
Thanks Daniel. it is pleasure to add a reponse code for xml rpc by me. i want to help about it.

**Comment by miconda** [comment]
First two patches are pushed in master now.

I noticed that the code was indented with whitespaces. Kamailio code uses tabs -- would be easier to apply the patches if you are going to use tabs for future patches.

**Comment by ycaner06** [comment]
okey, i will keep in my mind. Thanks Daniel.

**Comment by miconda** [comment]
For reference - the xmlrpc specs: http://xmlrpc.scripting.com/spec.html

You should open the discussion on sr-users mailing list, because you know better what you try to solve/improve with these patches. Describe what you don't like to current behaviour and the benefits after the patches, so the other users can comment and get to a solution.

**Comment by ycaner06** [comment]
after IRC meeting , when success , it returns empty string is ok.

**Pull request closed without merging**
