### PR TITLE
kex: add extended core stats

### PR DESCRIPTION
**Pull request by linuxmaniac**
* requests by method
* replies by status code

### CODE REVIEW

**Comment by linuxmaniac** [comment]
```
kamcmd> stats.get_statistics all
core:bad_URIs_rcvd = 2600
core:bad_msg_hdr = 0
core:drop_replies = 0
core:drop_requests = 6
core:err_replies = 0
core:err_requests = 0
core:fwd_replies = 0
core:fwd_requests = 7
core:rcv_replies = 28
core:rcv_replies_18x = 7
core:rcv_replies_1xx = 14
core:rcv_replies_2xx = 14
core:rcv_replies_3xx = 0
core:rcv_replies_401 = 0
core:rcv_replies_404 = 0
core:rcv_replies_407 = 0
core:rcv_replies_480 = 0
core:rcv_replies_486 = 0
core:rcv_replies_4xx = 0
core:rcv_replies_5xx = 0
core:rcv_replies_6xx = 0
core:rcv_requests = 86
core:rcv_requests_ack = 14
core:rcv_requests_bye = 7
core:rcv_requests_cancel = 0
core:rcv_requests_info = 0
core:rcv_requests_invite = 14
core:rcv_requests_message = 0
core:rcv_requests_notify = 0
core:rcv_requests_options = 0
core:rcv_requests_prack = 0
core:rcv_requests_publish = 0
core:rcv_requests_refer = 0
core:rcv_requests_register = 18
core:rcv_requests_subscribe = 0
core:rcv_requests_update = 0
core:unsupported_methods = 0
```

**Comment by linuxmaniac** [comment]
No complains about this one?

**Comment by miconda** [comment]
I was just looking at it -- looks good, can be committed.

**Comment by oej** [comment]
Do we need to update snmpstats too?

**Comment by oej** [comment]
Or is it a copy of the stats in that module?

**Comment by linuxmaniac** [comment]
> Do we need to update snmpstats too?

No idea about that.

> Or is it a copy of the stats in that module?

These are more detailed stats for _rcv_requests_ and _rcv_replies_. I don't know what you mean by copy

**Comment by oej** [comment]
snmpstats, sl and tmx all have various stats and I am not sure how they overlap, but we should try to sort this out. From a script output:
#       tmx:2xx_transactions = 377
#       tmx:3xx_transactions = 0
#       tmx:4xx_transactions = 457
#       tmx:5xx_transactions = 64
#       tmx:6xx_transactions = 0
#       tmx:UAC_transactions = 0
#       tmx:UAS_transactions = 887
#       tmx:active_transactions = 0
#       tmx:inuse_transactions = 0
#       tmx:local_replies = 903

#       sl:1xx_replies = 0
#       sl:200_replies = 10
#       sl:202_replies = 0
#       sl:2xx_replies = 0
#       sl:300_replies = 0
#       sl:301_replies = 0
#       sl:302_replies = 0
#       sl:3xx_replies = 0
#       sl:400_replies = 0
#       sl:401_replies = 0
#       sl:403_replies = 0
#       sl:404_replies = 0
#       sl:407_replies = 0
#       sl:408_replies = 0
#       sl:483_replies = 68
#       sl:4xx_replies = 37
#       sl:500_replies = 29
#       sl:5xx_replies = 0
#       sl:6xx_replies = 0
#       sl:failures = 0
#       sl:received_ACKs = 57
#       sl:sent_err_replies = 0
#       sl:sent_replies = 144
#       sl:xxx_replies = 0

I will check snmp later. If they don't overlap, I would like these new values to be exported in snmpstats too.

**Comment by oej** [comment]
And snmpstats:
´´´
*** snmpstats
     100_in : 0   (kamailio statistic (no description))
     100_out : 0   (kamailio statistic (no description))
     180_in : 0   (kamailio statistic (no description))
     180_out : 0   (kamailio statistic (no description))
     181_in : 0   (kamailio statistic (no description))
     181_out : 0   (kamailio statistic (no description))
     182_in : 0   (kamailio statistic (no description))
     182_out : 0   (kamailio statistic (no description))
     183_in : 0   (kamailio statistic (no description))
     183_out : 0   (kamailio statistic (no description))
     199_in : 0   (kamailio statistic (no description))
     199_out : 0   (kamailio statistic (no description))
     200_in : 0   (kamailio statistic (no description))
     200_out : 0   (kamailio statistic (no description))
     202_in : 0   (kamailio statistic (no description))
     202_out : 0   (kamailio statistic (no description))
     204_in : 0   (kamailio statistic (no description))
     204_out : 0   (kamailio statistic (no description))
     300_in : 0   (kamailio statistic (no description))
     300_out : 0   (kamailio statistic (no description))
     301_in : 0   (kamailio statistic (no description))
     301_out : 0   (kamailio statistic (no description))
     302_in : 0   (kamailio statistic (no description))
     302_out : 0   (kamailio statistic (no description))
     305_in : 0   (kamailio statistic (no description))
     305_out : 0   (kamailio statistic (no description))
     380_in : 0   (kamailio statistic (no description))
     380_out : 0   (kamailio statistic (no description))
     400_in : 0   (kamailio statistic (no description))
     400_out : 0   (kamailio statistic (no description))
     401_in : 0   (kamailio statistic (no description))
     401_out : 0   (kamailio statistic (no description))
     402_in : 0   (kamailio statistic (no description))
     402_out : 0   (kamailio statistic (no description))
     403_in : 0   (kamailio statistic (no description))
     403_out : 0   (kamailio statistic (no description))
     404_in : 0   (kamailio statistic (no description))
     404_out : 0   (kamailio statistic (no description))
     405_in : 0   (kamailio statistic (no description))
     405_out : 0   (kamailio statistic (no description))
     406_in : 0   (kamailio statistic (no description))
     406_out : 0   (kamailio statistic (no description))
     407_in : 0   (kamailio statistic (no description))
     407_out : 0   (kamailio statistic (no description))
     408_in : 0   (kamailio statistic (no description))
     408_out : 0   (kamailio statistic (no description))
     410_in : 0   (kamailio statistic (no description))
     410_out : 0   (kamailio statistic (no description))
     412_in : 0   (kamailio statistic (no description))
     412_out : 0   (kamailio statistic (no description))
     413_in : 0   (kamailio statistic (no description))
     413_out : 0   (kamailio statistic (no description))
     414_in : 0   (kamailio statistic (no description))
     414_out : 0   (kamailio statistic (no description))
     415_in : 0   (kamailio statistic (no description))
     415_out : 0   (kamailio statistic (no description))
     416_in : 0   (kamailio statistic (no description))
     416_out : 0   (kamailio statistic (no description))
     417_in : 0   (kamailio statistic (no description))
     417_out : 0   (kamailio statistic (no description))
     420_in : 0   (kamailio statistic (no description))
     420_out : 0   (kamailio statistic (no description))
     421_in : 0   (kamailio statistic (no description))
     421_out : 0   (kamailio statistic (no description))
     422_in : 0   (kamailio statistic (no description))
     422_out : 0   (kamailio statistic (no description))
     423_in : 0   (kamailio statistic (no description))
     423_out : 0   (kamailio statistic (no description))
     424_in : 0   (kamailio statistic (no description))
     424_out : 0   (kamailio statistic (no description))
     428_in : 0   (kamailio statistic (no description))
     428_out : 0   (kamailio statistic (no description))
     429_in : 0   (kamailio statistic (no description))
     429_out : 0   (kamailio statistic (no description))
     430_in : 0   (kamailio statistic (no description))
     430_out : 0   (kamailio statistic (no description))
     433_in : 0   (kamailio statistic (no description))
     433_out : 0   (kamailio statistic (no description))
     436_in : 0   (kamailio statistic (no description))
     436_out : 0   (kamailio statistic (no description))
     437_in : 0   (kamailio statistic (no description))
     437_out : 0   (kamailio statistic (no description))
     438_in : 0   (kamailio statistic (no description))
     438_out : 0   (kamailio statistic (no description))
     439_in : 0   (kamailio statistic (no description))
     439_out : 0   (kamailio statistic (no description))
     440_in : 0   (kamailio statistic (no description))
     440_out : 0   (kamailio statistic (no description))
     469_in : 0   (kamailio statistic (no description))
     469_out : 0   (kamailio statistic (no description))
     470_in : 0   (kamailio statistic (no description))
     470_out : 0   (kamailio statistic (no description))
     480_in : 0   (kamailio statistic (no description))
     480_out : 0   (kamailio statistic (no description))
     481_in : 0   (kamailio statistic (no description))
     481_out : 0   (kamailio statistic (no description))
     482_in : 0   (kamailio statistic (no description))
     482_out : 0   (kamailio statistic (no description))
     483_in : 0   (kamailio statistic (no description))
     483_out : 0   (kamailio statistic (no description))
     484_in : 0   (kamailio statistic (no description))
     484_out : 0   (kamailio statistic (no description))
     485_in : 0   (kamailio statistic (no description))
     485_out : 0   (kamailio statistic (no description))
     486_in : 0   (kamailio statistic (no description))
     486_out : 0   (kamailio statistic (no description))
     487_in : 0   (kamailio statistic (no description))
     487_out : 0   (kamailio statistic (no description))
     488_in : 0   (kamailio statistic (no description))
     488_out : 0   (kamailio statistic (no description))
     489_in : 0   (kamailio statistic (no description))
     489_out : 0   (kamailio statistic (no description))
     491_in : 0   (kamailio statistic (no description))
     491_out : 0   (kamailio statistic (no description))
     492_in : 0   (kamailio statistic (no description))
     492_out : 0   (kamailio statistic (no description))
     493_in : 0   (kamailio statistic (no description))
     493_out : 0   (kamailio statistic (no description))
     494_in : 0   (kamailio statistic (no description))
     494_out : 0   (kamailio statistic (no description))
     500_in : 0   (kamailio statistic (no description))
     500_out : 0   (kamailio statistic (no description))
     501_in : 0   (kamailio statistic (no description))
     501_out : 0   (kamailio statistic (no description))
     502_in : 0   (kamailio statistic (no description))
     502_out : 0   (kamailio statistic (no description))
     503_in : 0   (kamailio statistic (no description))
     503_out : 0   (kamailio statistic (no description))
     504_in : 0   (kamailio statistic (no description))
     504_out : 0   (kamailio statistic (no description))
     505_in : 0   (kamailio statistic (no description))
     505_out : 0   (kamailio statistic (no description))
     513_in : 0   (kamailio statistic (no description))
     513_out : 0   (kamailio statistic (no description))
     580_in : 0   (kamailio statistic (no description))
     580_out : 0   (kamailio statistic (no description))
     600_in : 0   (kamailio statistic (no description))
     600_out : 0   (kamailio statistic (no description))
     603_in : 0   (kamailio statistic (no description))
     603_out : 0   (kamailio statistic (no description))
     604_in : 0   (kamailio statistic (no description))
     604_out : 0   (kamailio statistic (no description))
     606_in : 0   (kamailio statistic (no description))
     606_out : 0   (kamailio statistic (no description))
´´

**Comment by oej** [comment]
We probably should add rcv_request_kdmq for our own request type :-)

From looking at all this, I think the ones you added are missing items which means it was a good addition and "someone" needs to add them to snmpstats too.

**Pull request merged**
