### PR TITLE
rtpengine: Add support for codec-accept and codec-consume flags

### PR DESCRIPTION
**Pull request by xkaraman**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

This PR add support for the `codec-accept` and `codec-consume` flags of rtpengine (supported since [mr9.2.1](https://github.com/sipwise/rtpengine/commit/336cb5b280079b0e7b24127ef987e10293604490)).

### CODE REVIEW

**Comment by rfuchs** [comment]
LGTM

**Comment by henningw** [comment]
Thanks for the fast review and merge. I would like to cherry-pick this to 5.7 stable branch, as it should be available according to the module readme (at least codec-accept). If necessary I can also create a dedicated commit only for the codec-accept.

**Comment by rfuchs** [comment]
These flags should work without this patch, as they would just be put into the `flags` list of strings and rtpengine does parse them out of there.

**Comment by henningw** [comment]
Unfortunately it does not seems to work at least with "codec-accept=XXX":
kam02 rtpengine[570041]: WARNING: [jKOBctrRd-]: [core] Unknown dictionary key encountered: 'codec-accept'

**Comment by rfuchs** [comment]
> Unfortunately it does not seems to work at least with "codec-accept=XXX": kam02 rtpengine[570041]: WARNING: [jKOBctrRd-]: [core] Unknown dictionary key encountered: 'codec-accept'

Right, you have to use `codec-flag-...` (dash instead of equals) for this to work.

**Comment by henningw** [comment]
Thanks, if there is a workaround there its of course not necessary to backport.

**Pull request merged**
