### PR TITLE
rtpengine: show errno and error string in more places where it is useful

### PR DESCRIPTION
**Pull request by guss77**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue 

#### Description

In `send_rtpp_command()` if socket operations fail with an error other than `EINTR` or `ENOBUFS`, the actual error is not reported - we just get a generic "Can't send command to/read reply from RTPEngine".

Other places in the module report `errno` and `strerror(errno)` using the log format "`(%s:%d)`" so added that to the error log.

Also fixed `bind_force_send_ip()` error log to use the same semantic as the other places.

### CODE REVIEW

**Comment by guss77** [comment]
I tried to match the line indentation formatting to what the CI action is showing, but it doesn't show the difference between tabs and spaces - and now I have the feeling that it showed extra indentation using spaces while all other indentation is tabs, and I overshot.

**Comment by rfuchs** [comment]
You should be able to just run `clang-format` over your edited code and that should reformat it to make the format checker happy.

There are some function calls (`close()` for example) between testing the `errno` value and printing out the log line. These functions might reset `errno` to something else. You should either reorder the code so that the log printing happens immediately after testing `errno`, or save the value to an intermediary variable and then print that.

**Comment by guss77** [comment]
> You should be able to just run `clang-format` over your edited code and that should reformat it to make the format checker happy.

I figured it out afterwards :sweat_smile: 

> There are some function calls (`close()` for example) between testing the `errno` value and printing out the log line. These functions might reset `errno` to something else. You should either reorder the code so that the log printing happens immediately after testing `errno`, or save the value to an intermediary variable and then print that.

I'll fix.

**Comment by guss77** [comment]
A heavier touch, but we can postpone `close(fd)` to the end and it also doesn't matter if we close needlessly - it is almost a no-op with `fd = -1`. If you disagree, I can try something else.

**Comment by rfuchs** [comment]
LGTM, thanks

**Pull request merged**
