### PR TITLE
nats: new nats message consumer module

### PR DESCRIPTION
**Pull request by eschmidbauer**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

New Module to consume messages from NATS messaging system. 

Initial Features:

- automatic reconnect with connected/disconnected event routes
- connect to up to 10 NATS URLs
- subscribe to any number of subjects
- receive messages via event route

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the pull request. The kamailio-dev is a bot account, so i removed the review request.
Just one quick question, in your code you state the copyright holder is "Weave Communication" but the module README (xml) states two other companies. Not sure if this is done intentional.

**Comment by eschmidbauer** [comment]
> Thanks for the pull request. The kamailio-dev is a bot account, so i removed the review request.
> Just one quick question, in your code you state the copyright holder is "Weave Communication" but the module README (xml) states two other companies. Not sure if this is done intentional.

Thanks for pointing that out! I pushed an update removing it.

**Comment by jmordica** [comment]
Woohoo!

**Comment by miconda** [comment]
Thanks for the new module!

I find the name with potential to create confusion, being closed to `NAT` and we all know how popular that is and what it refers to in VoIP, but at the end I am fine with it given that it is the name of the external project. Maybe in the future if we end up with many distributed messaging platform modules, we can add a common prefix to all of them like we added for db module in the past.

Regarding the code, I noticed that shm/pkg_malloc() results are not checked for NULL, which will result in crashes on low/out of memory cases. @eschmidbauer has already git commit access, so I am fine to merge it and then push follow up commits for memory allocation checks.

**Pull request merged**
