### PR TITLE
regex: migration to pcre2

### PR DESCRIPTION
**Pull request by linuxmaniac**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [x] Related to issue #2946

#### Description
migrate modules to pcre2

### CODE REVIEW

**Comment by sergey-safarov** [comment]
I have checkd `pcre2-config` config presence in the CentOS dists.
Looks like utility present in the CentOS 7, 8, 9 but does not exist.

Should you we drop CentOS 6 support?

**Comment by SirDMZ** [comment]
CentOS dropped CentOS 6 support years ago.

Anyone running Kamailio on CentOS 6 is most likely not updating their Kamailio either.
If you pay Redhat for extended support, you've got another year of RHEL6. Those users can run a mildly older branch of Kamailio until that day comes. Kamailio 5.7.x

I am saying this as someone this would affect. Drop us.

**Comment by linuxmaniac** [comment]
@miconda should I try to keep pcre3 and pcre2 at the same time or just drop cpre3? Is is worth the effort?

**Comment by miconda** [comment]
Fine for me to drop it and go now for the simpler way. If later proves to be high demand for the old variant, we can find solutions at that time.

**Comment by linuxmaniac** [comment]
Any regex user willing to check this? It seems to work

**Comment by miconda** [comment]
I don't think there are many users of this particular module. I would merge it and then see if later are reports about it.

**Pull request merged**
