### PR TITLE
utils/kamctl/kamdbctl: Merged patch from alpine packaging

### PR DESCRIPTION
**Pull request by sergey-safarov**
#### Pre-Submission Checklist
- [x] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description
This also fix docker packaging on alpine dist after eb3fd4c2672a18f3851ca255b9c6cb40cb0829ad

### CODE REVIEW

**Comment by henningw** [comment]
Thank you!

**Comment by henningw** [comment]
The change can't be applied by cherry-pick to 5.2, probably because of eb3fd4c in git master.

**Comment by sergey-safarov** [comment]
If eb3fd4c2672a18f3851ca255b9c6cb40cb0829ad is back ported to 5.2, then this PR we also backport.

**Comment by henningw** [comment]
As the secfilter module is not included in 5.2, the referenced commit will be not included in 5.2. I manually backported this patched to 5.2 and 5.1.

**Pull request merged**
