### PR TITLE
db_redis: fix broken pipe issue, if redis server with timeout setting.

### PR DESCRIPTION
**Pull request by FredWH**
- issue #2764

#### Pre-Submission Checklist

- [ ] Commit message has the format required by CONTRIBUTING guide
- [ ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ ] Each component has a single commit (if not, squash them into one commit)
- [ ] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [ ] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

### CODE REVIEW

**Comment by miconda** [comment]
Thanks! Not sure if @agranig is still interested in this module and look at this PR, knowing that he focuses on other things these days. 

Anyhow, we can wait a bit to see if someone else wants to check, before merging. From my point of view, the patch is simple enough, only changing return codes checking, but I can't test it easily at this moment, so if no other comments soon, it can be merged.

**Comment by agranig** [comment]
Thanks for the patch, looks good! I'll take care merging it.

**Comment by miconda** [comment]
@agranig - maybe this one got out of sight, if nothing else needs to be done, then it can be merged.

**Comment by miconda** [comment]
Merging, as it gets aged. Follow up updates can be pushed if needed. Thanks @FredWH!

**Pull request merged**
