### PR TITLE
Fixed saving dialogs on shutdown that are already loaded at startup in db_mode 3

### PR DESCRIPTION
**Pull request by Den4t**
#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [x] Related to issue #3669

### CODE REVIEW

**Comment by Den4t** [comment]
Some incorrect identation was found after initial commit, fixed in additional commits.

**Comment by linuxmaniac** [comment]
You have to squash them in one single commit and push force it

**Comment by Den4t** [comment]
Done

**Comment by miconda** [comment]
Thanks!

**Pull request merged**
